// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: recommend.proto

package server

import (
	"context"

	"short-drama-recommend/rpc/recommend-rpc/internal/logic"
	"short-drama-recommend/rpc/recommend-rpc/internal/svc"
	"short-drama-recommend/rpc/recommend-rpc/pb/short-drama-recommend/rpc/recommend-rpc/pb"
)

type RecommendServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedRecommendServiceServer
}

func NewRecommendServiceServer(svcCtx *svc.ServiceContext) *RecommendServiceServer {
	return &RecommendServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RecommendServiceServer) GetFeed(ctx context.Context, in *pb.FeedRequest) (*pb.FeedResponse, error) {
	l := logic.NewGetFeedLogic(ctx, s.svcCtx)
	return l.GetFeed(in)
}
