// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: payment.proto

package server

import (
	"context"

	"short-drama-recommend/rpc/payment-rpc/internal/logic"
	"short-drama-recommend/rpc/payment-rpc/internal/svc"
	"short-drama-recommend/rpc/payment-rpc/pb/short-drama-recommend/rpc/payment-rpc/pb"
)

type PaymentServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPaymentServiceServer
}

func NewPaymentServiceServer(svcCtx *svc.ServiceContext) *PaymentServiceServer {
	return &PaymentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServiceServer) CreateOrder(ctx context.Context, in *pb.CreateOrderRequest) (*pb.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *PaymentServiceServer) CapturePayment(ctx context.Context, in *pb.CapturePaymentRequest) (*pb.CapturePaymentResponse, error) {
	l := logic.NewCapturePaymentLogic(ctx, s.svcCtx)
	return l.CapturePayment(in)
}

func (s *PaymentServiceServer) GetOrder(ctx context.Context, in *pb.GetOrderRequest) (*pb.GetOrderResponse, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

func (s *PaymentServiceServer) ListOrders(ctx context.Context, in *pb.ListOrdersRequest) (*pb.ListOrdersResponse, error) {
	l := logic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

func (s *PaymentServiceServer) HandleWebhook(ctx context.Context, in *pb.WebhookRequest) (*pb.WebhookResponse, error) {
	l := logic.NewHandleWebhookLogic(ctx, s.svcCtx)
	return l.HandleWebhook(in)
}
