<script setup lang="ts">
import{onMounted,onBeforeUnmount,ref,nextTick}from'vue';import{useRoute,useRouter}from'vue-router';import{ElMessage}from'element-plus';import{request}from'../../api/client';import{loadStripe}from'@stripe/stripe-js'
const route=useRoute(),router=useRouter(),provider=ref<'STRIPE'|'PAYPAL'>('STRIPE'),creating=ref(false),paying=ref(false),result=ref<any>(null),cardHost=ref<HTMLElement|null>(null),stripe=ref<any>(null),card=ref<any>(null),stripeError=ref(''),returning=ref(false)
async function mountStripe(){if(!result.value?.client_secret||!cardHost.value)return;const key=(import.meta as any).env.VITE_STRIPE_PUBLISHABLE_KEY;if(!key){stripeError.value='未配置 VITE_STRIPE_PUBLISHABLE_KEY';return}stripe.value=await loadStripe(key);if(!stripe.value){stripeError.value='Stripe 初始化失败';return}const elements=stripe.value.elements();card.value=elements.create('card');card.value.mount(cardHost.value)}
async function buy(){creating.value=true;stripeError.value='';try{result.value=await request('/api/v1/payments/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:1,drama_id:Number(route.params.dramaId),provider:provider.value,currency:'USD',return_url:location.origin+'/#/checkout/'+route.params.dramaId,cancel_url:location.origin+'/#/checkout/'+route.params.dramaId})});localStorage.setItem('pending_payment_order',JSON.stringify({order_id:result.value.order_id,provider:provider.value,provider_order_id:result.value.provider_order_id}));if(provider.value==='PAYPAL'&&result.value.approve_url){window.location.href=result.value.approve_url;return}if(provider.value==='STRIPE'){await nextTick();await mountStripe()};ElMessage.success('支付订单已创建')}catch(e:any){ElMessage.error(e.message)}finally{creating.value=false}}
async function payStripe(){if(!stripe.value||!card.value||!result.value?.client_secret)return;paying.value=true;try{const r=await stripe.value.confirmCardPayment(result.value.client_secret,{payment_method:{card:card.value}});if(r.error){stripeError.value=r.error.message||'Stripe 支付失败';return}await refreshOrder(result.value.order_id)}finally{paying.value=false}}
async function refreshOrder(id:number){const o=await request('/api/v1/payments/orders/'+id);result.value={...result.value,...o};if(o.status==='PAID'){ElMessage.success('支付成功，剧集已解锁');localStorage.removeItem('pending_payment_order');setTimeout(()=>router.push('/drama/'+route.params.dramaId),500)}else ElMessage.info('支付已提交，等待支付确认')}
async function capturePaypal(){if(returning.value)return;const token=String(route.query.token||'');const pending=JSON.parse(localStorage.getItem('pending_payment_order')||'null');if(!token||!pending||pending.provider!=='PAYPAL')return;returning.value=true;try{const r=await request('/api/v1/payments/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order_id:pending.order_id,provider_order_id:token})});result.value={...pending,...r};if(r.status==='PAID'){localStorage.removeItem('pending_payment_order');ElMessage.success('PayPal 支付成功，剧集已解锁');router.replace('/drama/'+route.params.dramaId)}else ElMessage.info('PayPal 支付状态：'+r.status)}catch(e:any){ElMessage.error(e.message)}finally{returning.value=false}}
onMounted(capturePaypal);onBeforeUnmount(()=>{try{card.value?.destroy()}catch{}})
</script>
<template><section><div class="page-title"><p class="eyebrow">CHECKOUT</p><h1>Complete your purchase</h1><p>Secure payment · Instant unlock after confirmation</p></div><el-card class="checkout"><h2>Drama #{{route.params.dramaId}}</h2><el-radio-group v-model="provider" class="providers" :disabled="!!result"><el-radio-button label="STRIPE">Stripe</el-radio-button><el-radio-button label="PAYPAL">PayPal</el-radio-button></el-radio-group><el-alert :title="provider+' 支付'" description="订单金额由后台短剧价格决定，支付成功后自动获得本剧观看权益。" type="info" show-icon/><el-button v-if="!result" type="primary" size="large" class="pay-btn" :loading="creating" @click="buy">继续使用 {{provider}} 支付</el-button><template v-if="result&&provider==='STRIPE'"><div class="stripe-box"><p>银行卡支付</p><div ref="cardHost" class="card-host"></div><el-button type="primary" size="large" :loading="paying" @click="payStripe">确认支付 {{result.amount}} {{result.currency}}</el-button><p v-if="stripeError" class="error">{{stripeError}}</p></div></template><div v-if="result&&provider==='PAYPAL'" class="payment-result"><p>PayPal 订单：{{result.provider_order_id}}</p><p>状态：{{result.status}}</p></div><div v-if="result" class="payment-result"><p>本地订单：{{result.order_no||result.order_id}}</p><p>支付状态：{{result.status}}</p></div></el-card></section></template>