// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: behavior.proto

package server

import (
	"context"

	"short-drama-recommend/rpc/behavior-rpc/internal/logic"
	"short-drama-recommend/rpc/behavior-rpc/internal/svc"
	"short-drama-recommend/rpc/behavior-rpc/pb/short-drama-recommend/rpc/behavior-rpc/pb"
)

type BehaviorServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedBehaviorServiceServer
}

func NewBehaviorServiceServer(svcCtx *svc.ServiceContext) *BehaviorServiceServer {
	return &BehaviorServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *BehaviorServiceServer) RecordEvent(ctx context.Context, in *pb.RecordEventRequest) (*pb.RecordEventResponse, error) {
	l := logic.NewRecordEventLogic(ctx, s.svcCtx)
	return l.RecordEvent(in)
}
