// Code generated by ent, DO NOT EDIT.

package dramatag

import (
	"short-drama-recommend/rpc/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// DramaID applies equality check predicate on the "drama_id" field. It's identical to DramaIDEQ.
func DramaID(v uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldEQ(FieldDramaID, v))
}

// TagID applies equality check predicate on the "tag_id" field. It's identical to TagIDEQ.
func TagID(v uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldEQ(FieldTagID, v))
}

// DramaIDEQ applies the EQ predicate on the "drama_id" field.
func DramaIDEQ(v uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldEQ(FieldDramaID, v))
}

// DramaIDNEQ applies the NEQ predicate on the "drama_id" field.
func DramaIDNEQ(v uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldNEQ(FieldDramaID, v))
}

// DramaIDIn applies the In predicate on the "drama_id" field.
func DramaIDIn(vs ...uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldIn(FieldDramaID, vs...))
}

// DramaIDNotIn applies the NotIn predicate on the "drama_id" field.
func DramaIDNotIn(vs ...uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldNotIn(FieldDramaID, vs...))
}

// TagIDEQ applies the EQ predicate on the "tag_id" field.
func TagIDEQ(v uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldEQ(FieldTagID, v))
}

// TagIDNEQ applies the NEQ predicate on the "tag_id" field.
func TagIDNEQ(v uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldNEQ(FieldTagID, v))
}

// TagIDIn applies the In predicate on the "tag_id" field.
func TagIDIn(vs ...uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldIn(FieldTagID, vs...))
}

// TagIDNotIn applies the NotIn predicate on the "tag_id" field.
func TagIDNotIn(vs ...uint64) predicate.DramaTag {
	return predicate.DramaTag(sql.FieldNotIn(FieldTagID, vs...))
}

// HasDrama applies the HasEdge predicate on the "drama" edge.
func HasDrama() predicate.DramaTag {
	return predicate.DramaTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, DramaColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, DramaTable, DramaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDramaWith applies the HasEdge predicate on the "drama" edge with a given conditions (other predicates).
func HasDramaWith(preds ...predicate.Drama) predicate.DramaTag {
	return predicate.DramaTag(func(s *sql.Selector) {
		step := newDramaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTag applies the HasEdge predicate on the "tag" edge.
func HasTag() predicate.DramaTag {
	return predicate.DramaTag(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, TagColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, TagTable, TagColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagWith applies the HasEdge predicate on the "tag" edge with a given conditions (other predicates).
func HasTagWith(preds ...predicate.Tag) predicate.DramaTag {
	return predicate.DramaTag(func(s *sql.Selector) {
		step := newTagStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DramaTag) predicate.DramaTag {
	return predicate.DramaTag(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DramaTag) predicate.DramaTag {
	return predicate.DramaTag(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DramaTag) predicate.DramaTag {
	return predicate.DramaTag(sql.NotPredicates(p))
}
