// Code generated by ent, DO NOT EDIT.

package behaviorevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the behaviorevent type in the database.
	Label = "behavior_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldDramaID holds the string denoting the drama_id field in the database.
	FieldDramaID = "drama_id"
	// FieldEpisodeID holds the string denoting the episode_id field in the database.
	FieldEpisodeID = "episode_id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldWatchSeconds holds the string denoting the watch_seconds field in the database.
	FieldWatchSeconds = "watch_seconds"
	// FieldDurationSeconds holds the string denoting the duration_seconds field in the database.
	FieldDurationSeconds = "duration_seconds"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldDevice holds the string denoting the device field in the database.
	FieldDevice = "device"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldEventAt holds the string denoting the event_at field in the database.
	FieldEventAt = "event_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the behaviorevent in the database.
	Table = "behavior_events"
)

// Columns holds all SQL columns for behaviorevent fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldDramaID,
	FieldEpisodeID,
	FieldEventType,
	FieldWatchSeconds,
	FieldDurationSeconds,
	FieldCountry,
	FieldLanguage,
	FieldDevice,
	FieldSource,
	FieldRequestID,
	FieldEventAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUserID holds the default value on creation for the "user_id" field.
	DefaultUserID uint64
	// DefaultDramaID holds the default value on creation for the "drama_id" field.
	DefaultDramaID uint64
	// DefaultEpisodeID holds the default value on creation for the "episode_id" field.
	DefaultEpisodeID uint64
	// DefaultWatchSeconds holds the default value on creation for the "watch_seconds" field.
	DefaultWatchSeconds uint32
	// DefaultDurationSeconds holds the default value on creation for the "duration_seconds" field.
	DefaultDurationSeconds uint32
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultDevice holds the default value on creation for the "device" field.
	DefaultDevice string
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultRequestID holds the default value on creation for the "request_id" field.
	DefaultRequestID string
	// DefaultEventAt holds the default value on creation for the "event_at" field.
	DefaultEventAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the BehaviorEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByDramaID orders the results by the drama_id field.
func ByDramaID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDramaID, opts...).ToFunc()
}

// ByEpisodeID orders the results by the episode_id field.
func ByEpisodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEpisodeID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByWatchSeconds orders the results by the watch_seconds field.
func ByWatchSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWatchSeconds, opts...).ToFunc()
}

// ByDurationSeconds orders the results by the duration_seconds field.
func ByDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationSeconds, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByDevice orders the results by the device field.
func ByDevice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDevice, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByEventAt orders the results by the event_at field.
func ByEventAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
