// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"short-drama-recommend/rpc/ent/behaviorevent"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BehaviorEvent is the model entity for the BehaviorEvent schema.
type BehaviorEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uint64 `json:"user_id,omitempty"`
	// DramaID holds the value of the "drama_id" field.
	DramaID uint64 `json:"drama_id,omitempty"`
	// EpisodeID holds the value of the "episode_id" field.
	EpisodeID uint64 `json:"episode_id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// WatchSeconds holds the value of the "watch_seconds" field.
	WatchSeconds uint32 `json:"watch_seconds,omitempty"`
	// DurationSeconds holds the value of the "duration_seconds" field.
	DurationSeconds uint32 `json:"duration_seconds,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// Device holds the value of the "device" field.
	Device string `json:"device,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// EventAt holds the value of the "event_at" field.
	EventAt time.Time `json:"event_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BehaviorEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case behaviorevent.FieldID, behaviorevent.FieldUserID, behaviorevent.FieldDramaID, behaviorevent.FieldEpisodeID, behaviorevent.FieldWatchSeconds, behaviorevent.FieldDurationSeconds:
			values[i] = new(sql.NullInt64)
		case behaviorevent.FieldEventType, behaviorevent.FieldCountry, behaviorevent.FieldLanguage, behaviorevent.FieldDevice, behaviorevent.FieldSource, behaviorevent.FieldRequestID:
			values[i] = new(sql.NullString)
		case behaviorevent.FieldEventAt, behaviorevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BehaviorEvent fields.
func (_m *BehaviorEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case behaviorevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case behaviorevent.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint64(value.Int64)
			}
		case behaviorevent.FieldDramaID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field drama_id", values[i])
			} else if value.Valid {
				_m.DramaID = uint64(value.Int64)
			}
		case behaviorevent.FieldEpisodeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field episode_id", values[i])
			} else if value.Valid {
				_m.EpisodeID = uint64(value.Int64)
			}
		case behaviorevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case behaviorevent.FieldWatchSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field watch_seconds", values[i])
			} else if value.Valid {
				_m.WatchSeconds = uint32(value.Int64)
			}
		case behaviorevent.FieldDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_seconds", values[i])
			} else if value.Valid {
				_m.DurationSeconds = uint32(value.Int64)
			}
		case behaviorevent.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case behaviorevent.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case behaviorevent.FieldDevice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device", values[i])
			} else if value.Valid {
				_m.Device = value.String
			}
		case behaviorevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case behaviorevent.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case behaviorevent.FieldEventAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field event_at", values[i])
			} else if value.Valid {
				_m.EventAt = value.Time
			}
		case behaviorevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BehaviorEvent.
// This includes values selected through modifiers, order, etc.
func (_m *BehaviorEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BehaviorEvent.
// Note that you need to call BehaviorEvent.Unwrap() before calling this method if this BehaviorEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BehaviorEvent) Update() *BehaviorEventUpdateOne {
	return NewBehaviorEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BehaviorEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BehaviorEvent) Unwrap() *BehaviorEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BehaviorEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BehaviorEvent) String() string {
	var builder strings.Builder
	builder.WriteString("BehaviorEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("drama_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DramaID))
	builder.WriteString(", ")
	builder.WriteString("episode_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EpisodeID))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("watch_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.WatchSeconds))
	builder.WriteString(", ")
	builder.WriteString("duration_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationSeconds))
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("device=")
	builder.WriteString(_m.Device)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("event_at=")
	builder.WriteString(_m.EventAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BehaviorEvents is a parsable slice of BehaviorEvent.
type BehaviorEvents []*BehaviorEvent
