// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"short-drama-recommend/rpc/ent/behaviorevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BehaviorEventCreate is the builder for creating a BehaviorEvent entity.
type BehaviorEventCreate struct {
	config
	mutation *BehaviorEventMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *BehaviorEventCreate) SetUserID(v uint64) *BehaviorEventCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableUserID(v *uint64) *BehaviorEventCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetDramaID sets the "drama_id" field.
func (_c *BehaviorEventCreate) SetDramaID(v uint64) *BehaviorEventCreate {
	_c.mutation.SetDramaID(v)
	return _c
}

// SetNillableDramaID sets the "drama_id" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableDramaID(v *uint64) *BehaviorEventCreate {
	if v != nil {
		_c.SetDramaID(*v)
	}
	return _c
}

// SetEpisodeID sets the "episode_id" field.
func (_c *BehaviorEventCreate) SetEpisodeID(v uint64) *BehaviorEventCreate {
	_c.mutation.SetEpisodeID(v)
	return _c
}

// SetNillableEpisodeID sets the "episode_id" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableEpisodeID(v *uint64) *BehaviorEventCreate {
	if v != nil {
		_c.SetEpisodeID(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *BehaviorEventCreate) SetEventType(v string) *BehaviorEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetWatchSeconds sets the "watch_seconds" field.
func (_c *BehaviorEventCreate) SetWatchSeconds(v uint32) *BehaviorEventCreate {
	_c.mutation.SetWatchSeconds(v)
	return _c
}

// SetNillableWatchSeconds sets the "watch_seconds" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableWatchSeconds(v *uint32) *BehaviorEventCreate {
	if v != nil {
		_c.SetWatchSeconds(*v)
	}
	return _c
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_c *BehaviorEventCreate) SetDurationSeconds(v uint32) *BehaviorEventCreate {
	_c.mutation.SetDurationSeconds(v)
	return _c
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableDurationSeconds(v *uint32) *BehaviorEventCreate {
	if v != nil {
		_c.SetDurationSeconds(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *BehaviorEventCreate) SetCountry(v string) *BehaviorEventCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableCountry(v *string) *BehaviorEventCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetLanguage sets the "language" field.
func (_c *BehaviorEventCreate) SetLanguage(v string) *BehaviorEventCreate {
	_c.mutation.SetLanguage(v)
	return _c
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableLanguage(v *string) *BehaviorEventCreate {
	if v != nil {
		_c.SetLanguage(*v)
	}
	return _c
}

// SetDevice sets the "device" field.
func (_c *BehaviorEventCreate) SetDevice(v string) *BehaviorEventCreate {
	_c.mutation.SetDevice(v)
	return _c
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableDevice(v *string) *BehaviorEventCreate {
	if v != nil {
		_c.SetDevice(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *BehaviorEventCreate) SetSource(v string) *BehaviorEventCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableSource(v *string) *BehaviorEventCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *BehaviorEventCreate) SetRequestID(v string) *BehaviorEventCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableRequestID(v *string) *BehaviorEventCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetEventAt sets the "event_at" field.
func (_c *BehaviorEventCreate) SetEventAt(v time.Time) *BehaviorEventCreate {
	_c.mutation.SetEventAt(v)
	return _c
}

// SetNillableEventAt sets the "event_at" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableEventAt(v *time.Time) *BehaviorEventCreate {
	if v != nil {
		_c.SetEventAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *BehaviorEventCreate) SetCreatedAt(v time.Time) *BehaviorEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *BehaviorEventCreate) SetNillableCreatedAt(v *time.Time) *BehaviorEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BehaviorEventCreate) SetID(v uint64) *BehaviorEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BehaviorEventMutation object of the builder.
func (_c *BehaviorEventCreate) Mutation() *BehaviorEventMutation {
	return _c.mutation
}

// Save creates the BehaviorEvent in the database.
func (_c *BehaviorEventCreate) Save(ctx context.Context) (*BehaviorEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BehaviorEventCreate) SaveX(ctx context.Context) *BehaviorEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BehaviorEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BehaviorEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BehaviorEventCreate) defaults() {
	if _, ok := _c.mutation.UserID(); !ok {
		v := behaviorevent.DefaultUserID
		_c.mutation.SetUserID(v)
	}
	if _, ok := _c.mutation.DramaID(); !ok {
		v := behaviorevent.DefaultDramaID
		_c.mutation.SetDramaID(v)
	}
	if _, ok := _c.mutation.EpisodeID(); !ok {
		v := behaviorevent.DefaultEpisodeID
		_c.mutation.SetEpisodeID(v)
	}
	if _, ok := _c.mutation.WatchSeconds(); !ok {
		v := behaviorevent.DefaultWatchSeconds
		_c.mutation.SetWatchSeconds(v)
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		v := behaviorevent.DefaultDurationSeconds
		_c.mutation.SetDurationSeconds(v)
	}
	if _, ok := _c.mutation.Country(); !ok {
		v := behaviorevent.DefaultCountry
		_c.mutation.SetCountry(v)
	}
	if _, ok := _c.mutation.Language(); !ok {
		v := behaviorevent.DefaultLanguage
		_c.mutation.SetLanguage(v)
	}
	if _, ok := _c.mutation.Device(); !ok {
		v := behaviorevent.DefaultDevice
		_c.mutation.SetDevice(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := behaviorevent.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		v := behaviorevent.DefaultRequestID
		_c.mutation.SetRequestID(v)
	}
	if _, ok := _c.mutation.EventAt(); !ok {
		v := behaviorevent.DefaultEventAt()
		_c.mutation.SetEventAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := behaviorevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BehaviorEventCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "BehaviorEvent.user_id"`)}
	}
	if _, ok := _c.mutation.DramaID(); !ok {
		return &ValidationError{Name: "drama_id", err: errors.New(`ent: missing required field "BehaviorEvent.drama_id"`)}
	}
	if _, ok := _c.mutation.EpisodeID(); !ok {
		return &ValidationError{Name: "episode_id", err: errors.New(`ent: missing required field "BehaviorEvent.episode_id"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "BehaviorEvent.event_type"`)}
	}
	if _, ok := _c.mutation.WatchSeconds(); !ok {
		return &ValidationError{Name: "watch_seconds", err: errors.New(`ent: missing required field "BehaviorEvent.watch_seconds"`)}
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		return &ValidationError{Name: "duration_seconds", err: errors.New(`ent: missing required field "BehaviorEvent.duration_seconds"`)}
	}
	if _, ok := _c.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "BehaviorEvent.country"`)}
	}
	if _, ok := _c.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`ent: missing required field "BehaviorEvent.language"`)}
	}
	if _, ok := _c.mutation.Device(); !ok {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required field "BehaviorEvent.device"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "BehaviorEvent.source"`)}
	}
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "BehaviorEvent.request_id"`)}
	}
	if _, ok := _c.mutation.EventAt(); !ok {
		return &ValidationError{Name: "event_at", err: errors.New(`ent: missing required field "BehaviorEvent.event_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "BehaviorEvent.created_at"`)}
	}
	return nil
}

func (_c *BehaviorEventCreate) sqlSave(ctx context.Context) (*BehaviorEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BehaviorEventCreate) createSpec() (*BehaviorEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &BehaviorEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(behaviorevent.Table, sqlgraph.NewFieldSpec(behaviorevent.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(behaviorevent.FieldUserID, field.TypeUint64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.DramaID(); ok {
		_spec.SetField(behaviorevent.FieldDramaID, field.TypeUint64, value)
		_node.DramaID = value
	}
	if value, ok := _c.mutation.EpisodeID(); ok {
		_spec.SetField(behaviorevent.FieldEpisodeID, field.TypeUint64, value)
		_node.EpisodeID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(behaviorevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.WatchSeconds(); ok {
		_spec.SetField(behaviorevent.FieldWatchSeconds, field.TypeUint32, value)
		_node.WatchSeconds = value
	}
	if value, ok := _c.mutation.DurationSeconds(); ok {
		_spec.SetField(behaviorevent.FieldDurationSeconds, field.TypeUint32, value)
		_node.DurationSeconds = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(behaviorevent.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.Language(); ok {
		_spec.SetField(behaviorevent.FieldLanguage, field.TypeString, value)
		_node.Language = value
	}
	if value, ok := _c.mutation.Device(); ok {
		_spec.SetField(behaviorevent.FieldDevice, field.TypeString, value)
		_node.Device = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(behaviorevent.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(behaviorevent.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.EventAt(); ok {
		_spec.SetField(behaviorevent.FieldEventAt, field.TypeTime, value)
		_node.EventAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(behaviorevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// BehaviorEventCreateBulk is the builder for creating many BehaviorEvent entities in bulk.
type BehaviorEventCreateBulk struct {
	config
	err      error
	builders []*BehaviorEventCreate
}

// Save creates the BehaviorEvent entities in the database.
func (_c *BehaviorEventCreateBulk) Save(ctx context.Context) ([]*BehaviorEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BehaviorEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BehaviorEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BehaviorEventCreateBulk) SaveX(ctx context.Context) []*BehaviorEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BehaviorEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BehaviorEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
