// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"short-drama-recommend/rpc/ent/behaviorevent"
	"short-drama-recommend/rpc/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BehaviorEventDelete is the builder for deleting a BehaviorEvent entity.
type BehaviorEventDelete struct {
	config
	hooks    []Hook
	mutation *BehaviorEventMutation
}

// Where appends a list predicates to the BehaviorEventDelete builder.
func (_d *BehaviorEventDelete) Where(ps ...predicate.BehaviorEvent) *BehaviorEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *BehaviorEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BehaviorEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *BehaviorEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(behaviorevent.Table, sqlgraph.NewFieldSpec(behaviorevent.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// BehaviorEventDeleteOne is the builder for deleting a single BehaviorEvent entity.
type BehaviorEventDeleteOne struct {
	_d *BehaviorEventDelete
}

// Where appends a list predicates to the BehaviorEventDelete builder.
func (_d *BehaviorEventDeleteOne) Where(ps ...predicate.BehaviorEvent) *BehaviorEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *BehaviorEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{behaviorevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *BehaviorEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
