// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"short-drama-recommend/rpc/ent/behaviorevent"
	"short-drama-recommend/rpc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BehaviorEventUpdate is the builder for updating BehaviorEvent entities.
type BehaviorEventUpdate struct {
	config
	hooks     []Hook
	mutation  *BehaviorEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BehaviorEventUpdate builder.
func (_u *BehaviorEventUpdate) Where(ps ...predicate.BehaviorEvent) *BehaviorEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BehaviorEventUpdate) SetUserID(v uint64) *BehaviorEventUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableUserID(v *uint64) *BehaviorEventUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BehaviorEventUpdate) AddUserID(v int64) *BehaviorEventUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDramaID sets the "drama_id" field.
func (_u *BehaviorEventUpdate) SetDramaID(v uint64) *BehaviorEventUpdate {
	_u.mutation.ResetDramaID()
	_u.mutation.SetDramaID(v)
	return _u
}

// SetNillableDramaID sets the "drama_id" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableDramaID(v *uint64) *BehaviorEventUpdate {
	if v != nil {
		_u.SetDramaID(*v)
	}
	return _u
}

// AddDramaID adds value to the "drama_id" field.
func (_u *BehaviorEventUpdate) AddDramaID(v int64) *BehaviorEventUpdate {
	_u.mutation.AddDramaID(v)
	return _u
}

// SetEpisodeID sets the "episode_id" field.
func (_u *BehaviorEventUpdate) SetEpisodeID(v uint64) *BehaviorEventUpdate {
	_u.mutation.ResetEpisodeID()
	_u.mutation.SetEpisodeID(v)
	return _u
}

// SetNillableEpisodeID sets the "episode_id" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableEpisodeID(v *uint64) *BehaviorEventUpdate {
	if v != nil {
		_u.SetEpisodeID(*v)
	}
	return _u
}

// AddEpisodeID adds value to the "episode_id" field.
func (_u *BehaviorEventUpdate) AddEpisodeID(v int64) *BehaviorEventUpdate {
	_u.mutation.AddEpisodeID(v)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *BehaviorEventUpdate) SetEventType(v string) *BehaviorEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableEventType(v *string) *BehaviorEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetWatchSeconds sets the "watch_seconds" field.
func (_u *BehaviorEventUpdate) SetWatchSeconds(v uint32) *BehaviorEventUpdate {
	_u.mutation.ResetWatchSeconds()
	_u.mutation.SetWatchSeconds(v)
	return _u
}

// SetNillableWatchSeconds sets the "watch_seconds" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableWatchSeconds(v *uint32) *BehaviorEventUpdate {
	if v != nil {
		_u.SetWatchSeconds(*v)
	}
	return _u
}

// AddWatchSeconds adds value to the "watch_seconds" field.
func (_u *BehaviorEventUpdate) AddWatchSeconds(v int32) *BehaviorEventUpdate {
	_u.mutation.AddWatchSeconds(v)
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *BehaviorEventUpdate) SetDurationSeconds(v uint32) *BehaviorEventUpdate {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableDurationSeconds(v *uint32) *BehaviorEventUpdate {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *BehaviorEventUpdate) AddDurationSeconds(v int32) *BehaviorEventUpdate {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// SetCountry sets the "country" field.
func (_u *BehaviorEventUpdate) SetCountry(v string) *BehaviorEventUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableCountry(v *string) *BehaviorEventUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BehaviorEventUpdate) SetLanguage(v string) *BehaviorEventUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableLanguage(v *string) *BehaviorEventUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetDevice sets the "device" field.
func (_u *BehaviorEventUpdate) SetDevice(v string) *BehaviorEventUpdate {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableDevice(v *string) *BehaviorEventUpdate {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *BehaviorEventUpdate) SetSource(v string) *BehaviorEventUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableSource(v *string) *BehaviorEventUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *BehaviorEventUpdate) SetRequestID(v string) *BehaviorEventUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableRequestID(v *string) *BehaviorEventUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetEventAt sets the "event_at" field.
func (_u *BehaviorEventUpdate) SetEventAt(v time.Time) *BehaviorEventUpdate {
	_u.mutation.SetEventAt(v)
	return _u
}

// SetNillableEventAt sets the "event_at" field if the given value is not nil.
func (_u *BehaviorEventUpdate) SetNillableEventAt(v *time.Time) *BehaviorEventUpdate {
	if v != nil {
		_u.SetEventAt(*v)
	}
	return _u
}

// Mutation returns the BehaviorEventMutation object of the builder.
func (_u *BehaviorEventUpdate) Mutation() *BehaviorEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BehaviorEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BehaviorEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BehaviorEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BehaviorEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BehaviorEventUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BehaviorEventUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BehaviorEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(behaviorevent.Table, behaviorevent.Columns, sqlgraph.NewFieldSpec(behaviorevent.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(behaviorevent.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(behaviorevent.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DramaID(); ok {
		_spec.SetField(behaviorevent.FieldDramaID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDramaID(); ok {
		_spec.AddField(behaviorevent.FieldDramaID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.EpisodeID(); ok {
		_spec.SetField(behaviorevent.FieldEpisodeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedEpisodeID(); ok {
		_spec.AddField(behaviorevent.FieldEpisodeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(behaviorevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.WatchSeconds(); ok {
		_spec.SetField(behaviorevent.FieldWatchSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedWatchSeconds(); ok {
		_spec.AddField(behaviorevent.FieldWatchSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(behaviorevent.FieldDurationSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(behaviorevent.FieldDurationSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(behaviorevent.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(behaviorevent.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(behaviorevent.FieldDevice, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(behaviorevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(behaviorevent.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventAt(); ok {
		_spec.SetField(behaviorevent.FieldEventAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{behaviorevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BehaviorEventUpdateOne is the builder for updating a single BehaviorEvent entity.
type BehaviorEventUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BehaviorEventMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *BehaviorEventUpdateOne) SetUserID(v uint64) *BehaviorEventUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableUserID(v *uint64) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BehaviorEventUpdateOne) AddUserID(v int64) *BehaviorEventUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetDramaID sets the "drama_id" field.
func (_u *BehaviorEventUpdateOne) SetDramaID(v uint64) *BehaviorEventUpdateOne {
	_u.mutation.ResetDramaID()
	_u.mutation.SetDramaID(v)
	return _u
}

// SetNillableDramaID sets the "drama_id" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableDramaID(v *uint64) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetDramaID(*v)
	}
	return _u
}

// AddDramaID adds value to the "drama_id" field.
func (_u *BehaviorEventUpdateOne) AddDramaID(v int64) *BehaviorEventUpdateOne {
	_u.mutation.AddDramaID(v)
	return _u
}

// SetEpisodeID sets the "episode_id" field.
func (_u *BehaviorEventUpdateOne) SetEpisodeID(v uint64) *BehaviorEventUpdateOne {
	_u.mutation.ResetEpisodeID()
	_u.mutation.SetEpisodeID(v)
	return _u
}

// SetNillableEpisodeID sets the "episode_id" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableEpisodeID(v *uint64) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetEpisodeID(*v)
	}
	return _u
}

// AddEpisodeID adds value to the "episode_id" field.
func (_u *BehaviorEventUpdateOne) AddEpisodeID(v int64) *BehaviorEventUpdateOne {
	_u.mutation.AddEpisodeID(v)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *BehaviorEventUpdateOne) SetEventType(v string) *BehaviorEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableEventType(v *string) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetWatchSeconds sets the "watch_seconds" field.
func (_u *BehaviorEventUpdateOne) SetWatchSeconds(v uint32) *BehaviorEventUpdateOne {
	_u.mutation.ResetWatchSeconds()
	_u.mutation.SetWatchSeconds(v)
	return _u
}

// SetNillableWatchSeconds sets the "watch_seconds" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableWatchSeconds(v *uint32) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetWatchSeconds(*v)
	}
	return _u
}

// AddWatchSeconds adds value to the "watch_seconds" field.
func (_u *BehaviorEventUpdateOne) AddWatchSeconds(v int32) *BehaviorEventUpdateOne {
	_u.mutation.AddWatchSeconds(v)
	return _u
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_u *BehaviorEventUpdateOne) SetDurationSeconds(v uint32) *BehaviorEventUpdateOne {
	_u.mutation.ResetDurationSeconds()
	_u.mutation.SetDurationSeconds(v)
	return _u
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableDurationSeconds(v *uint32) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetDurationSeconds(*v)
	}
	return _u
}

// AddDurationSeconds adds value to the "duration_seconds" field.
func (_u *BehaviorEventUpdateOne) AddDurationSeconds(v int32) *BehaviorEventUpdateOne {
	_u.mutation.AddDurationSeconds(v)
	return _u
}

// SetCountry sets the "country" field.
func (_u *BehaviorEventUpdateOne) SetCountry(v string) *BehaviorEventUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableCountry(v *string) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *BehaviorEventUpdateOne) SetLanguage(v string) *BehaviorEventUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableLanguage(v *string) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetDevice sets the "device" field.
func (_u *BehaviorEventUpdateOne) SetDevice(v string) *BehaviorEventUpdateOne {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableDevice(v *string) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *BehaviorEventUpdateOne) SetSource(v string) *BehaviorEventUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableSource(v *string) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *BehaviorEventUpdateOne) SetRequestID(v string) *BehaviorEventUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableRequestID(v *string) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetEventAt sets the "event_at" field.
func (_u *BehaviorEventUpdateOne) SetEventAt(v time.Time) *BehaviorEventUpdateOne {
	_u.mutation.SetEventAt(v)
	return _u
}

// SetNillableEventAt sets the "event_at" field if the given value is not nil.
func (_u *BehaviorEventUpdateOne) SetNillableEventAt(v *time.Time) *BehaviorEventUpdateOne {
	if v != nil {
		_u.SetEventAt(*v)
	}
	return _u
}

// Mutation returns the BehaviorEventMutation object of the builder.
func (_u *BehaviorEventUpdateOne) Mutation() *BehaviorEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the BehaviorEventUpdate builder.
func (_u *BehaviorEventUpdateOne) Where(ps ...predicate.BehaviorEvent) *BehaviorEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BehaviorEventUpdateOne) Select(field string, fields ...string) *BehaviorEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BehaviorEvent entity.
func (_u *BehaviorEventUpdateOne) Save(ctx context.Context) (*BehaviorEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BehaviorEventUpdateOne) SaveX(ctx context.Context) *BehaviorEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BehaviorEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BehaviorEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *BehaviorEventUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BehaviorEventUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *BehaviorEventUpdateOne) sqlSave(ctx context.Context) (_node *BehaviorEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(behaviorevent.Table, behaviorevent.Columns, sqlgraph.NewFieldSpec(behaviorevent.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BehaviorEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, behaviorevent.FieldID)
		for _, f := range fields {
			if !behaviorevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != behaviorevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(behaviorevent.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(behaviorevent.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.DramaID(); ok {
		_spec.SetField(behaviorevent.FieldDramaID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDramaID(); ok {
		_spec.AddField(behaviorevent.FieldDramaID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.EpisodeID(); ok {
		_spec.SetField(behaviorevent.FieldEpisodeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedEpisodeID(); ok {
		_spec.AddField(behaviorevent.FieldEpisodeID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(behaviorevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.WatchSeconds(); ok {
		_spec.SetField(behaviorevent.FieldWatchSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedWatchSeconds(); ok {
		_spec.AddField(behaviorevent.FieldWatchSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.DurationSeconds(); ok {
		_spec.SetField(behaviorevent.FieldDurationSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedDurationSeconds(); ok {
		_spec.AddField(behaviorevent.FieldDurationSeconds, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(behaviorevent.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(behaviorevent.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(behaviorevent.FieldDevice, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(behaviorevent.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(behaviorevent.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.EventAt(); ok {
		_spec.SetField(behaviorevent.FieldEventAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &BehaviorEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{behaviorevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
