// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"short-drama-recommend/rpc/ent/migrate"

	"short-drama-recommend/rpc/ent/behaviorevent"
	"short-drama-recommend/rpc/ent/drama"
	"short-drama-recommend/rpc/ent/dramagenre"
	"short-drama-recommend/rpc/ent/dramatag"
	"short-drama-recommend/rpc/ent/episode"
	"short-drama-recommend/rpc/ent/genre"
	"short-drama-recommend/rpc/ent/tag"
	"short-drama-recommend/rpc/ent/user"
	"short-drama-recommend/rpc/ent/usertagprofile"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BehaviorEvent is the client for interacting with the BehaviorEvent builders.
	BehaviorEvent *BehaviorEventClient
	// Drama is the client for interacting with the Drama builders.
	Drama *DramaClient
	// DramaGenre is the client for interacting with the DramaGenre builders.
	DramaGenre *DramaGenreClient
	// DramaTag is the client for interacting with the DramaTag builders.
	DramaTag *DramaTagClient
	// Episode is the client for interacting with the Episode builders.
	Episode *EpisodeClient
	// Genre is the client for interacting with the Genre builders.
	Genre *GenreClient
	// Tag is the client for interacting with the Tag builders.
	Tag *TagClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// UserTagProfile is the client for interacting with the UserTagProfile builders.
	UserTagProfile *UserTagProfileClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BehaviorEvent = NewBehaviorEventClient(c.config)
	c.Drama = NewDramaClient(c.config)
	c.DramaGenre = NewDramaGenreClient(c.config)
	c.DramaTag = NewDramaTagClient(c.config)
	c.Episode = NewEpisodeClient(c.config)
	c.Genre = NewGenreClient(c.config)
	c.Tag = NewTagClient(c.config)
	c.User = NewUserClient(c.config)
	c.UserTagProfile = NewUserTagProfileClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		BehaviorEvent:  NewBehaviorEventClient(cfg),
		Drama:          NewDramaClient(cfg),
		DramaGenre:     NewDramaGenreClient(cfg),
		DramaTag:       NewDramaTagClient(cfg),
		Episode:        NewEpisodeClient(cfg),
		Genre:          NewGenreClient(cfg),
		Tag:            NewTagClient(cfg),
		User:           NewUserClient(cfg),
		UserTagProfile: NewUserTagProfileClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:            ctx,
		config:         cfg,
		BehaviorEvent:  NewBehaviorEventClient(cfg),
		Drama:          NewDramaClient(cfg),
		DramaGenre:     NewDramaGenreClient(cfg),
		DramaTag:       NewDramaTagClient(cfg),
		Episode:        NewEpisodeClient(cfg),
		Genre:          NewGenreClient(cfg),
		Tag:            NewTagClient(cfg),
		User:           NewUserClient(cfg),
		UserTagProfile: NewUserTagProfileClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BehaviorEvent.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.BehaviorEvent, c.Drama, c.DramaGenre, c.DramaTag, c.Episode, c.Genre, c.Tag,
		c.User, c.UserTagProfile,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.BehaviorEvent, c.Drama, c.DramaGenre, c.DramaTag, c.Episode, c.Genre, c.Tag,
		c.User, c.UserTagProfile,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BehaviorEventMutation:
		return c.BehaviorEvent.mutate(ctx, m)
	case *DramaMutation:
		return c.Drama.mutate(ctx, m)
	case *DramaGenreMutation:
		return c.DramaGenre.mutate(ctx, m)
	case *DramaTagMutation:
		return c.DramaTag.mutate(ctx, m)
	case *EpisodeMutation:
		return c.Episode.mutate(ctx, m)
	case *GenreMutation:
		return c.Genre.mutate(ctx, m)
	case *TagMutation:
		return c.Tag.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	case *UserTagProfileMutation:
		return c.UserTagProfile.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BehaviorEventClient is a client for the BehaviorEvent schema.
type BehaviorEventClient struct {
	config
}

// NewBehaviorEventClient returns a client for the BehaviorEvent from the given config.
func NewBehaviorEventClient(c config) *BehaviorEventClient {
	return &BehaviorEventClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `behaviorevent.Hooks(f(g(h())))`.
func (c *BehaviorEventClient) Use(hooks ...Hook) {
	c.hooks.BehaviorEvent = append(c.hooks.BehaviorEvent, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `behaviorevent.Intercept(f(g(h())))`.
func (c *BehaviorEventClient) Intercept(interceptors ...Interceptor) {
	c.inters.BehaviorEvent = append(c.inters.BehaviorEvent, interceptors...)
}

// Create returns a builder for creating a BehaviorEvent entity.
func (c *BehaviorEventClient) Create() *BehaviorEventCreate {
	mutation := newBehaviorEventMutation(c.config, OpCreate)
	return &BehaviorEventCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BehaviorEvent entities.
func (c *BehaviorEventClient) CreateBulk(builders ...*BehaviorEventCreate) *BehaviorEventCreateBulk {
	return &BehaviorEventCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BehaviorEventClient) MapCreateBulk(slice any, setFunc func(*BehaviorEventCreate, int)) *BehaviorEventCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BehaviorEventCreateBulk{err: fmt.Errorf("calling to BehaviorEventClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BehaviorEventCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BehaviorEventCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BehaviorEvent.
func (c *BehaviorEventClient) Update() *BehaviorEventUpdate {
	mutation := newBehaviorEventMutation(c.config, OpUpdate)
	return &BehaviorEventUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BehaviorEventClient) UpdateOne(_m *BehaviorEvent) *BehaviorEventUpdateOne {
	mutation := newBehaviorEventMutation(c.config, OpUpdateOne, withBehaviorEvent(_m))
	return &BehaviorEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BehaviorEventClient) UpdateOneID(id uint64) *BehaviorEventUpdateOne {
	mutation := newBehaviorEventMutation(c.config, OpUpdateOne, withBehaviorEventID(id))
	return &BehaviorEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BehaviorEvent.
func (c *BehaviorEventClient) Delete() *BehaviorEventDelete {
	mutation := newBehaviorEventMutation(c.config, OpDelete)
	return &BehaviorEventDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BehaviorEventClient) DeleteOne(_m *BehaviorEvent) *BehaviorEventDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BehaviorEventClient) DeleteOneID(id uint64) *BehaviorEventDeleteOne {
	builder := c.Delete().Where(behaviorevent.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BehaviorEventDeleteOne{builder}
}

// Query returns a query builder for BehaviorEvent.
func (c *BehaviorEventClient) Query() *BehaviorEventQuery {
	return &BehaviorEventQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBehaviorEvent},
		inters: c.Interceptors(),
	}
}

// Get returns a BehaviorEvent entity by its id.
func (c *BehaviorEventClient) Get(ctx context.Context, id uint64) (*BehaviorEvent, error) {
	return c.Query().Where(behaviorevent.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BehaviorEventClient) GetX(ctx context.Context, id uint64) *BehaviorEvent {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BehaviorEventClient) Hooks() []Hook {
	return c.hooks.BehaviorEvent
}

// Interceptors returns the client interceptors.
func (c *BehaviorEventClient) Interceptors() []Interceptor {
	return c.inters.BehaviorEvent
}

func (c *BehaviorEventClient) mutate(ctx context.Context, m *BehaviorEventMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BehaviorEventCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BehaviorEventUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BehaviorEventUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BehaviorEventDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BehaviorEvent mutation op: %q", m.Op())
	}
}

// DramaClient is a client for the Drama schema.
type DramaClient struct {
	config
}

// NewDramaClient returns a client for the Drama from the given config.
func NewDramaClient(c config) *DramaClient {
	return &DramaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `drama.Hooks(f(g(h())))`.
func (c *DramaClient) Use(hooks ...Hook) {
	c.hooks.Drama = append(c.hooks.Drama, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `drama.Intercept(f(g(h())))`.
func (c *DramaClient) Intercept(interceptors ...Interceptor) {
	c.inters.Drama = append(c.inters.Drama, interceptors...)
}

// Create returns a builder for creating a Drama entity.
func (c *DramaClient) Create() *DramaCreate {
	mutation := newDramaMutation(c.config, OpCreate)
	return &DramaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Drama entities.
func (c *DramaClient) CreateBulk(builders ...*DramaCreate) *DramaCreateBulk {
	return &DramaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DramaClient) MapCreateBulk(slice any, setFunc func(*DramaCreate, int)) *DramaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DramaCreateBulk{err: fmt.Errorf("calling to DramaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DramaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DramaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Drama.
func (c *DramaClient) Update() *DramaUpdate {
	mutation := newDramaMutation(c.config, OpUpdate)
	return &DramaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DramaClient) UpdateOne(_m *Drama) *DramaUpdateOne {
	mutation := newDramaMutation(c.config, OpUpdateOne, withDrama(_m))
	return &DramaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DramaClient) UpdateOneID(id uint64) *DramaUpdateOne {
	mutation := newDramaMutation(c.config, OpUpdateOne, withDramaID(id))
	return &DramaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Drama.
func (c *DramaClient) Delete() *DramaDelete {
	mutation := newDramaMutation(c.config, OpDelete)
	return &DramaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *DramaClient) DeleteOne(_m *Drama) *DramaDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *DramaClient) DeleteOneID(id uint64) *DramaDeleteOne {
	builder := c.Delete().Where(drama.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DramaDeleteOne{builder}
}

// Query returns a query builder for Drama.
func (c *DramaClient) Query() *DramaQuery {
	return &DramaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDrama},
		inters: c.Interceptors(),
	}
}

// Get returns a Drama entity by its id.
func (c *DramaClient) Get(ctx context.Context, id uint64) (*Drama, error) {
	return c.Query().Where(drama.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DramaClient) GetX(ctx context.Context, id uint64) *Drama {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryEpisodes queries the episodes edge of a Drama.
func (c *DramaClient) QueryEpisodes(_m *Drama) *EpisodeQuery {
	query := (&EpisodeClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(drama.Table, drama.FieldID, id),
			sqlgraph.To(episode.Table, episode.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, drama.EpisodesTable, drama.EpisodesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryGenres queries the genres edge of a Drama.
func (c *DramaClient) QueryGenres(_m *Drama) *GenreQuery {
	query := (&GenreClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(drama.Table, drama.FieldID, id),
			sqlgraph.To(genre.Table, genre.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, drama.GenresTable, drama.GenresPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryTags queries the tags edge of a Drama.
func (c *DramaClient) QueryTags(_m *Drama) *TagQuery {
	query := (&TagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(drama.Table, drama.FieldID, id),
			sqlgraph.To(tag.Table, tag.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, drama.TagsTable, drama.TagsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDramaGenres queries the drama_genres edge of a Drama.
func (c *DramaClient) QueryDramaGenres(_m *Drama) *DramaGenreQuery {
	query := (&DramaGenreClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(drama.Table, drama.FieldID, id),
			sqlgraph.To(dramagenre.Table, dramagenre.DramaColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, drama.DramaGenresTable, drama.DramaGenresColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDramaTags queries the drama_tags edge of a Drama.
func (c *DramaClient) QueryDramaTags(_m *Drama) *DramaTagQuery {
	query := (&DramaTagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(drama.Table, drama.FieldID, id),
			sqlgraph.To(dramatag.Table, dramatag.DramaColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, drama.DramaTagsTable, drama.DramaTagsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *DramaClient) Hooks() []Hook {
	return c.hooks.Drama
}

// Interceptors returns the client interceptors.
func (c *DramaClient) Interceptors() []Interceptor {
	return c.inters.Drama
}

func (c *DramaClient) mutate(ctx context.Context, m *DramaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DramaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DramaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DramaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DramaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Drama mutation op: %q", m.Op())
	}
}

// DramaGenreClient is a client for the DramaGenre schema.
type DramaGenreClient struct {
	config
}

// NewDramaGenreClient returns a client for the DramaGenre from the given config.
func NewDramaGenreClient(c config) *DramaGenreClient {
	return &DramaGenreClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dramagenre.Hooks(f(g(h())))`.
func (c *DramaGenreClient) Use(hooks ...Hook) {
	c.hooks.DramaGenre = append(c.hooks.DramaGenre, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dramagenre.Intercept(f(g(h())))`.
func (c *DramaGenreClient) Intercept(interceptors ...Interceptor) {
	c.inters.DramaGenre = append(c.inters.DramaGenre, interceptors...)
}

// Create returns a builder for creating a DramaGenre entity.
func (c *DramaGenreClient) Create() *DramaGenreCreate {
	mutation := newDramaGenreMutation(c.config, OpCreate)
	return &DramaGenreCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DramaGenre entities.
func (c *DramaGenreClient) CreateBulk(builders ...*DramaGenreCreate) *DramaGenreCreateBulk {
	return &DramaGenreCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DramaGenreClient) MapCreateBulk(slice any, setFunc func(*DramaGenreCreate, int)) *DramaGenreCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DramaGenreCreateBulk{err: fmt.Errorf("calling to DramaGenreClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DramaGenreCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DramaGenreCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DramaGenre.
func (c *DramaGenreClient) Update() *DramaGenreUpdate {
	mutation := newDramaGenreMutation(c.config, OpUpdate)
	return &DramaGenreUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DramaGenreClient) UpdateOne(_m *DramaGenre) *DramaGenreUpdateOne {
	mutation := newDramaGenreMutation(c.config, OpUpdateOne)
	mutation.drama = &_m.DramaID
	mutation.genre = &_m.GenreID
	return &DramaGenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DramaGenre.
func (c *DramaGenreClient) Delete() *DramaGenreDelete {
	mutation := newDramaGenreMutation(c.config, OpDelete)
	return &DramaGenreDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for DramaGenre.
func (c *DramaGenreClient) Query() *DramaGenreQuery {
	return &DramaGenreQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDramaGenre},
		inters: c.Interceptors(),
	}
}

// QueryDrama queries the drama edge of a DramaGenre.
func (c *DramaGenreClient) QueryDrama(_m *DramaGenre) *DramaQuery {
	return c.Query().
		Where(dramagenre.DramaID(_m.DramaID), dramagenre.GenreID(_m.GenreID)).
		QueryDrama()
}

// QueryGenre queries the genre edge of a DramaGenre.
func (c *DramaGenreClient) QueryGenre(_m *DramaGenre) *GenreQuery {
	return c.Query().
		Where(dramagenre.DramaID(_m.DramaID), dramagenre.GenreID(_m.GenreID)).
		QueryGenre()
}

// Hooks returns the client hooks.
func (c *DramaGenreClient) Hooks() []Hook {
	return c.hooks.DramaGenre
}

// Interceptors returns the client interceptors.
func (c *DramaGenreClient) Interceptors() []Interceptor {
	return c.inters.DramaGenre
}

func (c *DramaGenreClient) mutate(ctx context.Context, m *DramaGenreMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DramaGenreCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DramaGenreUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DramaGenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DramaGenreDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DramaGenre mutation op: %q", m.Op())
	}
}

// DramaTagClient is a client for the DramaTag schema.
type DramaTagClient struct {
	config
}

// NewDramaTagClient returns a client for the DramaTag from the given config.
func NewDramaTagClient(c config) *DramaTagClient {
	return &DramaTagClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dramatag.Hooks(f(g(h())))`.
func (c *DramaTagClient) Use(hooks ...Hook) {
	c.hooks.DramaTag = append(c.hooks.DramaTag, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `dramatag.Intercept(f(g(h())))`.
func (c *DramaTagClient) Intercept(interceptors ...Interceptor) {
	c.inters.DramaTag = append(c.inters.DramaTag, interceptors...)
}

// Create returns a builder for creating a DramaTag entity.
func (c *DramaTagClient) Create() *DramaTagCreate {
	mutation := newDramaTagMutation(c.config, OpCreate)
	return &DramaTagCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DramaTag entities.
func (c *DramaTagClient) CreateBulk(builders ...*DramaTagCreate) *DramaTagCreateBulk {
	return &DramaTagCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *DramaTagClient) MapCreateBulk(slice any, setFunc func(*DramaTagCreate, int)) *DramaTagCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &DramaTagCreateBulk{err: fmt.Errorf("calling to DramaTagClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*DramaTagCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &DramaTagCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DramaTag.
func (c *DramaTagClient) Update() *DramaTagUpdate {
	mutation := newDramaTagMutation(c.config, OpUpdate)
	return &DramaTagUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DramaTagClient) UpdateOne(_m *DramaTag) *DramaTagUpdateOne {
	mutation := newDramaTagMutation(c.config, OpUpdateOne)
	mutation.drama = &_m.DramaID
	mutation.tag = &_m.TagID
	return &DramaTagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DramaTag.
func (c *DramaTagClient) Delete() *DramaTagDelete {
	mutation := newDramaTagMutation(c.config, OpDelete)
	return &DramaTagDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Query returns a query builder for DramaTag.
func (c *DramaTagClient) Query() *DramaTagQuery {
	return &DramaTagQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeDramaTag},
		inters: c.Interceptors(),
	}
}

// QueryDrama queries the drama edge of a DramaTag.
func (c *DramaTagClient) QueryDrama(_m *DramaTag) *DramaQuery {
	return c.Query().
		Where(dramatag.DramaID(_m.DramaID), dramatag.TagID(_m.TagID)).
		QueryDrama()
}

// QueryTag queries the tag edge of a DramaTag.
func (c *DramaTagClient) QueryTag(_m *DramaTag) *TagQuery {
	return c.Query().
		Where(dramatag.DramaID(_m.DramaID), dramatag.TagID(_m.TagID)).
		QueryTag()
}

// Hooks returns the client hooks.
func (c *DramaTagClient) Hooks() []Hook {
	return c.hooks.DramaTag
}

// Interceptors returns the client interceptors.
func (c *DramaTagClient) Interceptors() []Interceptor {
	return c.inters.DramaTag
}

func (c *DramaTagClient) mutate(ctx context.Context, m *DramaTagMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&DramaTagCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&DramaTagUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&DramaTagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&DramaTagDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown DramaTag mutation op: %q", m.Op())
	}
}

// EpisodeClient is a client for the Episode schema.
type EpisodeClient struct {
	config
}

// NewEpisodeClient returns a client for the Episode from the given config.
func NewEpisodeClient(c config) *EpisodeClient {
	return &EpisodeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `episode.Hooks(f(g(h())))`.
func (c *EpisodeClient) Use(hooks ...Hook) {
	c.hooks.Episode = append(c.hooks.Episode, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `episode.Intercept(f(g(h())))`.
func (c *EpisodeClient) Intercept(interceptors ...Interceptor) {
	c.inters.Episode = append(c.inters.Episode, interceptors...)
}

// Create returns a builder for creating a Episode entity.
func (c *EpisodeClient) Create() *EpisodeCreate {
	mutation := newEpisodeMutation(c.config, OpCreate)
	return &EpisodeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Episode entities.
func (c *EpisodeClient) CreateBulk(builders ...*EpisodeCreate) *EpisodeCreateBulk {
	return &EpisodeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *EpisodeClient) MapCreateBulk(slice any, setFunc func(*EpisodeCreate, int)) *EpisodeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &EpisodeCreateBulk{err: fmt.Errorf("calling to EpisodeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*EpisodeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &EpisodeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Episode.
func (c *EpisodeClient) Update() *EpisodeUpdate {
	mutation := newEpisodeMutation(c.config, OpUpdate)
	return &EpisodeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *EpisodeClient) UpdateOne(_m *Episode) *EpisodeUpdateOne {
	mutation := newEpisodeMutation(c.config, OpUpdateOne, withEpisode(_m))
	return &EpisodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *EpisodeClient) UpdateOneID(id uint64) *EpisodeUpdateOne {
	mutation := newEpisodeMutation(c.config, OpUpdateOne, withEpisodeID(id))
	return &EpisodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Episode.
func (c *EpisodeClient) Delete() *EpisodeDelete {
	mutation := newEpisodeMutation(c.config, OpDelete)
	return &EpisodeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *EpisodeClient) DeleteOne(_m *Episode) *EpisodeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *EpisodeClient) DeleteOneID(id uint64) *EpisodeDeleteOne {
	builder := c.Delete().Where(episode.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &EpisodeDeleteOne{builder}
}

// Query returns a query builder for Episode.
func (c *EpisodeClient) Query() *EpisodeQuery {
	return &EpisodeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeEpisode},
		inters: c.Interceptors(),
	}
}

// Get returns a Episode entity by its id.
func (c *EpisodeClient) Get(ctx context.Context, id uint64) (*Episode, error) {
	return c.Query().Where(episode.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *EpisodeClient) GetX(ctx context.Context, id uint64) *Episode {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDrama queries the drama edge of a Episode.
func (c *EpisodeClient) QueryDrama(_m *Episode) *DramaQuery {
	query := (&DramaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(episode.Table, episode.FieldID, id),
			sqlgraph.To(drama.Table, drama.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, episode.DramaTable, episode.DramaColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *EpisodeClient) Hooks() []Hook {
	return c.hooks.Episode
}

// Interceptors returns the client interceptors.
func (c *EpisodeClient) Interceptors() []Interceptor {
	return c.inters.Episode
}

func (c *EpisodeClient) mutate(ctx context.Context, m *EpisodeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&EpisodeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&EpisodeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&EpisodeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&EpisodeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Episode mutation op: %q", m.Op())
	}
}

// GenreClient is a client for the Genre schema.
type GenreClient struct {
	config
}

// NewGenreClient returns a client for the Genre from the given config.
func NewGenreClient(c config) *GenreClient {
	return &GenreClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `genre.Hooks(f(g(h())))`.
func (c *GenreClient) Use(hooks ...Hook) {
	c.hooks.Genre = append(c.hooks.Genre, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `genre.Intercept(f(g(h())))`.
func (c *GenreClient) Intercept(interceptors ...Interceptor) {
	c.inters.Genre = append(c.inters.Genre, interceptors...)
}

// Create returns a builder for creating a Genre entity.
func (c *GenreClient) Create() *GenreCreate {
	mutation := newGenreMutation(c.config, OpCreate)
	return &GenreCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Genre entities.
func (c *GenreClient) CreateBulk(builders ...*GenreCreate) *GenreCreateBulk {
	return &GenreCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *GenreClient) MapCreateBulk(slice any, setFunc func(*GenreCreate, int)) *GenreCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &GenreCreateBulk{err: fmt.Errorf("calling to GenreClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*GenreCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &GenreCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Genre.
func (c *GenreClient) Update() *GenreUpdate {
	mutation := newGenreMutation(c.config, OpUpdate)
	return &GenreUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *GenreClient) UpdateOne(_m *Genre) *GenreUpdateOne {
	mutation := newGenreMutation(c.config, OpUpdateOne, withGenre(_m))
	return &GenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *GenreClient) UpdateOneID(id uint64) *GenreUpdateOne {
	mutation := newGenreMutation(c.config, OpUpdateOne, withGenreID(id))
	return &GenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Genre.
func (c *GenreClient) Delete() *GenreDelete {
	mutation := newGenreMutation(c.config, OpDelete)
	return &GenreDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *GenreClient) DeleteOne(_m *Genre) *GenreDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *GenreClient) DeleteOneID(id uint64) *GenreDeleteOne {
	builder := c.Delete().Where(genre.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &GenreDeleteOne{builder}
}

// Query returns a query builder for Genre.
func (c *GenreClient) Query() *GenreQuery {
	return &GenreQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeGenre},
		inters: c.Interceptors(),
	}
}

// Get returns a Genre entity by its id.
func (c *GenreClient) Get(ctx context.Context, id uint64) (*Genre, error) {
	return c.Query().Where(genre.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *GenreClient) GetX(ctx context.Context, id uint64) *Genre {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDramas queries the dramas edge of a Genre.
func (c *GenreClient) QueryDramas(_m *Genre) *DramaQuery {
	query := (&DramaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(genre.Table, genre.FieldID, id),
			sqlgraph.To(drama.Table, drama.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, genre.DramasTable, genre.DramasPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDramaGenres queries the drama_genres edge of a Genre.
func (c *GenreClient) QueryDramaGenres(_m *Genre) *DramaGenreQuery {
	query := (&DramaGenreClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(genre.Table, genre.FieldID, id),
			sqlgraph.To(dramagenre.Table, dramagenre.GenreColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, genre.DramaGenresTable, genre.DramaGenresColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *GenreClient) Hooks() []Hook {
	return c.hooks.Genre
}

// Interceptors returns the client interceptors.
func (c *GenreClient) Interceptors() []Interceptor {
	return c.inters.Genre
}

func (c *GenreClient) mutate(ctx context.Context, m *GenreMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&GenreCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&GenreUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&GenreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&GenreDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Genre mutation op: %q", m.Op())
	}
}

// TagClient is a client for the Tag schema.
type TagClient struct {
	config
}

// NewTagClient returns a client for the Tag from the given config.
func NewTagClient(c config) *TagClient {
	return &TagClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tag.Hooks(f(g(h())))`.
func (c *TagClient) Use(hooks ...Hook) {
	c.hooks.Tag = append(c.hooks.Tag, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tag.Intercept(f(g(h())))`.
func (c *TagClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tag = append(c.inters.Tag, interceptors...)
}

// Create returns a builder for creating a Tag entity.
func (c *TagClient) Create() *TagCreate {
	mutation := newTagMutation(c.config, OpCreate)
	return &TagCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tag entities.
func (c *TagClient) CreateBulk(builders ...*TagCreate) *TagCreateBulk {
	return &TagCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TagClient) MapCreateBulk(slice any, setFunc func(*TagCreate, int)) *TagCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TagCreateBulk{err: fmt.Errorf("calling to TagClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TagCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TagCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tag.
func (c *TagClient) Update() *TagUpdate {
	mutation := newTagMutation(c.config, OpUpdate)
	return &TagUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TagClient) UpdateOne(_m *Tag) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTag(_m))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TagClient) UpdateOneID(id uint64) *TagUpdateOne {
	mutation := newTagMutation(c.config, OpUpdateOne, withTagID(id))
	return &TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tag.
func (c *TagClient) Delete() *TagDelete {
	mutation := newTagMutation(c.config, OpDelete)
	return &TagDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TagClient) DeleteOne(_m *Tag) *TagDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TagClient) DeleteOneID(id uint64) *TagDeleteOne {
	builder := c.Delete().Where(tag.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TagDeleteOne{builder}
}

// Query returns a query builder for Tag.
func (c *TagClient) Query() *TagQuery {
	return &TagQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTag},
		inters: c.Interceptors(),
	}
}

// Get returns a Tag entity by its id.
func (c *TagClient) Get(ctx context.Context, id uint64) (*Tag, error) {
	return c.Query().Where(tag.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TagClient) GetX(ctx context.Context, id uint64) *Tag {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryDramas queries the dramas edge of a Tag.
func (c *TagClient) QueryDramas(_m *Tag) *DramaQuery {
	query := (&DramaClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(drama.Table, drama.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, tag.DramasTable, tag.DramasPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryDramaTags queries the drama_tags edge of a Tag.
func (c *TagClient) QueryDramaTags(_m *Tag) *DramaTagQuery {
	query := (&DramaTagClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tag.Table, tag.FieldID, id),
			sqlgraph.To(dramatag.Table, dramatag.TagColumn),
			sqlgraph.Edge(sqlgraph.O2M, true, tag.DramaTagsTable, tag.DramaTagsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TagClient) Hooks() []Hook {
	return c.hooks.Tag
}

// Interceptors returns the client interceptors.
func (c *TagClient) Interceptors() []Interceptor {
	return c.inters.Tag
}

func (c *TagClient) mutate(ctx context.Context, m *TagMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TagCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TagUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TagUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TagDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tag mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id uint64) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id uint64) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id uint64) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id uint64) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// UserTagProfileClient is a client for the UserTagProfile schema.
type UserTagProfileClient struct {
	config
}

// NewUserTagProfileClient returns a client for the UserTagProfile from the given config.
func NewUserTagProfileClient(c config) *UserTagProfileClient {
	return &UserTagProfileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `usertagprofile.Hooks(f(g(h())))`.
func (c *UserTagProfileClient) Use(hooks ...Hook) {
	c.hooks.UserTagProfile = append(c.hooks.UserTagProfile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `usertagprofile.Intercept(f(g(h())))`.
func (c *UserTagProfileClient) Intercept(interceptors ...Interceptor) {
	c.inters.UserTagProfile = append(c.inters.UserTagProfile, interceptors...)
}

// Create returns a builder for creating a UserTagProfile entity.
func (c *UserTagProfileClient) Create() *UserTagProfileCreate {
	mutation := newUserTagProfileMutation(c.config, OpCreate)
	return &UserTagProfileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of UserTagProfile entities.
func (c *UserTagProfileClient) CreateBulk(builders ...*UserTagProfileCreate) *UserTagProfileCreateBulk {
	return &UserTagProfileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserTagProfileClient) MapCreateBulk(slice any, setFunc func(*UserTagProfileCreate, int)) *UserTagProfileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserTagProfileCreateBulk{err: fmt.Errorf("calling to UserTagProfileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserTagProfileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserTagProfileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for UserTagProfile.
func (c *UserTagProfileClient) Update() *UserTagProfileUpdate {
	mutation := newUserTagProfileMutation(c.config, OpUpdate)
	return &UserTagProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserTagProfileClient) UpdateOne(_m *UserTagProfile) *UserTagProfileUpdateOne {
	mutation := newUserTagProfileMutation(c.config, OpUpdateOne, withUserTagProfile(_m))
	return &UserTagProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserTagProfileClient) UpdateOneID(id int) *UserTagProfileUpdateOne {
	mutation := newUserTagProfileMutation(c.config, OpUpdateOne, withUserTagProfileID(id))
	return &UserTagProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for UserTagProfile.
func (c *UserTagProfileClient) Delete() *UserTagProfileDelete {
	mutation := newUserTagProfileMutation(c.config, OpDelete)
	return &UserTagProfileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserTagProfileClient) DeleteOne(_m *UserTagProfile) *UserTagProfileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserTagProfileClient) DeleteOneID(id int) *UserTagProfileDeleteOne {
	builder := c.Delete().Where(usertagprofile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserTagProfileDeleteOne{builder}
}

// Query returns a query builder for UserTagProfile.
func (c *UserTagProfileClient) Query() *UserTagProfileQuery {
	return &UserTagProfileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUserTagProfile},
		inters: c.Interceptors(),
	}
}

// Get returns a UserTagProfile entity by its id.
func (c *UserTagProfileClient) Get(ctx context.Context, id int) (*UserTagProfile, error) {
	return c.Query().Where(usertagprofile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserTagProfileClient) GetX(ctx context.Context, id int) *UserTagProfile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserTagProfileClient) Hooks() []Hook {
	return c.hooks.UserTagProfile
}

// Interceptors returns the client interceptors.
func (c *UserTagProfileClient) Interceptors() []Interceptor {
	return c.inters.UserTagProfile
}

func (c *UserTagProfileClient) mutate(ctx context.Context, m *UserTagProfileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserTagProfileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserTagProfileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserTagProfileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserTagProfileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown UserTagProfile mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BehaviorEvent, Drama, DramaGenre, DramaTag, Episode, Genre, Tag, User,
		UserTagProfile []ent.Hook
	}
	inters struct {
		BehaviorEvent, Drama, DramaGenre, DramaTag, Episode, Genre, Tag, User,
		UserTagProfile []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
