// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"short-drama-recommend/rpc/ent/drama"
	"short-drama-recommend/rpc/ent/dramagenre"
	"short-drama-recommend/rpc/ent/genre"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DramaGenreCreate is the builder for creating a DramaGenre entity.
type DramaGenreCreate struct {
	config
	mutation *DramaGenreMutation
	hooks    []Hook
}

// SetDramaID sets the "drama_id" field.
func (_c *DramaGenreCreate) SetDramaID(v uint64) *DramaGenreCreate {
	_c.mutation.SetDramaID(v)
	return _c
}

// SetGenreID sets the "genre_id" field.
func (_c *DramaGenreCreate) SetGenreID(v uint64) *DramaGenreCreate {
	_c.mutation.SetGenreID(v)
	return _c
}

// SetDrama sets the "drama" edge to the Drama entity.
func (_c *DramaGenreCreate) SetDrama(v *Drama) *DramaGenreCreate {
	return _c.SetDramaID(v.ID)
}

// SetGenre sets the "genre" edge to the Genre entity.
func (_c *DramaGenreCreate) SetGenre(v *Genre) *DramaGenreCreate {
	return _c.SetGenreID(v.ID)
}

// Mutation returns the DramaGenreMutation object of the builder.
func (_c *DramaGenreCreate) Mutation() *DramaGenreMutation {
	return _c.mutation
}

// Save creates the DramaGenre in the database.
func (_c *DramaGenreCreate) Save(ctx context.Context) (*DramaGenre, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DramaGenreCreate) SaveX(ctx context.Context) *DramaGenre {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DramaGenreCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DramaGenreCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DramaGenreCreate) check() error {
	if _, ok := _c.mutation.DramaID(); !ok {
		return &ValidationError{Name: "drama_id", err: errors.New(`ent: missing required field "DramaGenre.drama_id"`)}
	}
	if _, ok := _c.mutation.GenreID(); !ok {
		return &ValidationError{Name: "genre_id", err: errors.New(`ent: missing required field "DramaGenre.genre_id"`)}
	}
	if len(_c.mutation.DramaIDs()) == 0 {
		return &ValidationError{Name: "drama", err: errors.New(`ent: missing required edge "DramaGenre.drama"`)}
	}
	if len(_c.mutation.GenreIDs()) == 0 {
		return &ValidationError{Name: "genre", err: errors.New(`ent: missing required edge "DramaGenre.genre"`)}
	}
	return nil
}

func (_c *DramaGenreCreate) sqlSave(ctx context.Context) (*DramaGenre, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *DramaGenreCreate) createSpec() (*DramaGenre, *sqlgraph.CreateSpec) {
	var (
		_node = &DramaGenre{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dramagenre.Table, nil)
	)
	if nodes := _c.mutation.DramaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dramagenre.DramaTable,
			Columns: []string{dramagenre.DramaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DramaID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GenreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   dramagenre.GenreTable,
			Columns: []string{dramagenre.GenreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GenreID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DramaGenreCreateBulk is the builder for creating many DramaGenre entities in bulk.
type DramaGenreCreateBulk struct {
	config
	err      error
	builders []*DramaGenreCreate
}

// Save creates the DramaGenre entities in the database.
func (_c *DramaGenreCreateBulk) Save(ctx context.Context) ([]*DramaGenre, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DramaGenre, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DramaGenreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DramaGenreCreateBulk) SaveX(ctx context.Context) []*DramaGenre {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DramaGenreCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DramaGenreCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
