// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"short-drama-recommend/rpc/ent/drama"
	"short-drama-recommend/rpc/ent/dramatag"
	"short-drama-recommend/rpc/ent/tag"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DramaTag is the model entity for the DramaTag schema.
type DramaTag struct {
	config `json:"-"`
	// DramaID holds the value of the "drama_id" field.
	DramaID uint64 `json:"drama_id,omitempty"`
	// TagID holds the value of the "tag_id" field.
	TagID uint64 `json:"tag_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DramaTagQuery when eager-loading is set.
	Edges        DramaTagEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DramaTagEdges holds the relations/edges for other nodes in the graph.
type DramaTagEdges struct {
	// Drama holds the value of the drama edge.
	Drama *Drama `json:"drama,omitempty"`
	// Tag holds the value of the tag edge.
	Tag *Tag `json:"tag,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DramaOrErr returns the Drama value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DramaTagEdges) DramaOrErr() (*Drama, error) {
	if e.Drama != nil {
		return e.Drama, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: drama.Label}
	}
	return nil, &NotLoadedError{edge: "drama"}
}

// TagOrErr returns the Tag value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DramaTagEdges) TagOrErr() (*Tag, error) {
	if e.Tag != nil {
		return e.Tag, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tag.Label}
	}
	return nil, &NotLoadedError{edge: "tag"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DramaTag) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dramatag.FieldDramaID, dramatag.FieldTagID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DramaTag fields.
func (_m *DramaTag) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dramatag.FieldDramaID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field drama_id", values[i])
			} else if value.Valid {
				_m.DramaID = uint64(value.Int64)
			}
		case dramatag.FieldTagID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tag_id", values[i])
			} else if value.Valid {
				_m.TagID = uint64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DramaTag.
// This includes values selected through modifiers, order, etc.
func (_m *DramaTag) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDrama queries the "drama" edge of the DramaTag entity.
func (_m *DramaTag) QueryDrama() *DramaQuery {
	return NewDramaTagClient(_m.config).QueryDrama(_m)
}

// QueryTag queries the "tag" edge of the DramaTag entity.
func (_m *DramaTag) QueryTag() *TagQuery {
	return NewDramaTagClient(_m.config).QueryTag(_m)
}

// Update returns a builder for updating this DramaTag.
// Note that you need to call DramaTag.Unwrap() before calling this method if this DramaTag
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DramaTag) Update() *DramaTagUpdateOne {
	return NewDramaTagClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DramaTag entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DramaTag) Unwrap() *DramaTag {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DramaTag is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DramaTag) String() string {
	var builder strings.Builder
	builder.WriteString("DramaTag(")
	builder.WriteString("drama_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DramaID))
	builder.WriteString(", ")
	builder.WriteString("tag_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TagID))
	builder.WriteByte(')')
	return builder.String()
}

// DramaTags is a parsable slice of DramaTag.
type DramaTags []*DramaTag
