// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"short-drama-recommend/rpc/ent/drama"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Drama is the model entity for the Drama schema.
type Drama struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Subtitle holds the value of the "subtitle" field.
	Subtitle string `json:"subtitle,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Cover holds the value of the "cover" field.
	Cover string `json:"cover,omitempty"`
	// Country holds the value of the "country" field.
	Country string `json:"country,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// TotalEpisodes holds the value of the "total_episodes" field.
	TotalEpisodes uint32 `json:"total_episodes,omitempty"`
	// IsPaid holds the value of the "is_paid" field.
	IsPaid bool `json:"is_paid,omitempty"`
	// PriceCents holds the value of the "price_cents" field.
	PriceCents uint64 `json:"price_cents,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Status holds the value of the "status" field.
	Status int8 `json:"status,omitempty"`
	// Popularity holds the value of the "popularity" field.
	Popularity float64 `json:"popularity,omitempty"`
	// CompletionRate holds the value of the "completion_rate" field.
	CompletionRate float64 `json:"completion_rate,omitempty"`
	// PayRate holds the value of the "pay_rate" field.
	PayRate float64 `json:"pay_rate,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DramaQuery when eager-loading is set.
	Edges        DramaEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DramaEdges holds the relations/edges for other nodes in the graph.
type DramaEdges struct {
	// Episodes holds the value of the episodes edge.
	Episodes []*Episode `json:"episodes,omitempty"`
	// Genres holds the value of the genres edge.
	Genres []*Genre `json:"genres,omitempty"`
	// Tags holds the value of the tags edge.
	Tags []*Tag `json:"tags,omitempty"`
	// DramaGenres holds the value of the drama_genres edge.
	DramaGenres []*DramaGenre `json:"drama_genres,omitempty"`
	// DramaTags holds the value of the drama_tags edge.
	DramaTags []*DramaTag `json:"drama_tags,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// EpisodesOrErr returns the Episodes value or an error if the edge
// was not loaded in eager-loading.
func (e DramaEdges) EpisodesOrErr() ([]*Episode, error) {
	if e.loadedTypes[0] {
		return e.Episodes, nil
	}
	return nil, &NotLoadedError{edge: "episodes"}
}

// GenresOrErr returns the Genres value or an error if the edge
// was not loaded in eager-loading.
func (e DramaEdges) GenresOrErr() ([]*Genre, error) {
	if e.loadedTypes[1] {
		return e.Genres, nil
	}
	return nil, &NotLoadedError{edge: "genres"}
}

// TagsOrErr returns the Tags value or an error if the edge
// was not loaded in eager-loading.
func (e DramaEdges) TagsOrErr() ([]*Tag, error) {
	if e.loadedTypes[2] {
		return e.Tags, nil
	}
	return nil, &NotLoadedError{edge: "tags"}
}

// DramaGenresOrErr returns the DramaGenres value or an error if the edge
// was not loaded in eager-loading.
func (e DramaEdges) DramaGenresOrErr() ([]*DramaGenre, error) {
	if e.loadedTypes[3] {
		return e.DramaGenres, nil
	}
	return nil, &NotLoadedError{edge: "drama_genres"}
}

// DramaTagsOrErr returns the DramaTags value or an error if the edge
// was not loaded in eager-loading.
func (e DramaEdges) DramaTagsOrErr() ([]*DramaTag, error) {
	if e.loadedTypes[4] {
		return e.DramaTags, nil
	}
	return nil, &NotLoadedError{edge: "drama_tags"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Drama) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case drama.FieldIsPaid:
			values[i] = new(sql.NullBool)
		case drama.FieldPopularity, drama.FieldCompletionRate, drama.FieldPayRate:
			values[i] = new(sql.NullFloat64)
		case drama.FieldID, drama.FieldTotalEpisodes, drama.FieldPriceCents, drama.FieldStatus:
			values[i] = new(sql.NullInt64)
		case drama.FieldTitle, drama.FieldSubtitle, drama.FieldDescription, drama.FieldCover, drama.FieldCountry, drama.FieldLanguage, drama.FieldCurrency:
			values[i] = new(sql.NullString)
		case drama.FieldPublishedAt, drama.FieldCreatedAt, drama.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Drama fields.
func (_m *Drama) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case drama.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case drama.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case drama.FieldSubtitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subtitle", values[i])
			} else if value.Valid {
				_m.Subtitle = value.String
			}
		case drama.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case drama.FieldCover:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cover", values[i])
			} else if value.Valid {
				_m.Cover = value.String
			}
		case drama.FieldCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field country", values[i])
			} else if value.Valid {
				_m.Country = value.String
			}
		case drama.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case drama.FieldTotalEpisodes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_episodes", values[i])
			} else if value.Valid {
				_m.TotalEpisodes = uint32(value.Int64)
			}
		case drama.FieldIsPaid:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_paid", values[i])
			} else if value.Valid {
				_m.IsPaid = value.Bool
			}
		case drama.FieldPriceCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_cents", values[i])
			} else if value.Valid {
				_m.PriceCents = uint64(value.Int64)
			}
		case drama.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case drama.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int8(value.Int64)
			}
		case drama.FieldPopularity:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field popularity", values[i])
			} else if value.Valid {
				_m.Popularity = value.Float64
			}
		case drama.FieldCompletionRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field completion_rate", values[i])
			} else if value.Valid {
				_m.CompletionRate = value.Float64
			}
		case drama.FieldPayRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pay_rate", values[i])
			} else if value.Valid {
				_m.PayRate = value.Float64
			}
		case drama.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case drama.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case drama.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Drama.
// This includes values selected through modifiers, order, etc.
func (_m *Drama) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEpisodes queries the "episodes" edge of the Drama entity.
func (_m *Drama) QueryEpisodes() *EpisodeQuery {
	return NewDramaClient(_m.config).QueryEpisodes(_m)
}

// QueryGenres queries the "genres" edge of the Drama entity.
func (_m *Drama) QueryGenres() *GenreQuery {
	return NewDramaClient(_m.config).QueryGenres(_m)
}

// QueryTags queries the "tags" edge of the Drama entity.
func (_m *Drama) QueryTags() *TagQuery {
	return NewDramaClient(_m.config).QueryTags(_m)
}

// QueryDramaGenres queries the "drama_genres" edge of the Drama entity.
func (_m *Drama) QueryDramaGenres() *DramaGenreQuery {
	return NewDramaClient(_m.config).QueryDramaGenres(_m)
}

// QueryDramaTags queries the "drama_tags" edge of the Drama entity.
func (_m *Drama) QueryDramaTags() *DramaTagQuery {
	return NewDramaClient(_m.config).QueryDramaTags(_m)
}

// Update returns a builder for updating this Drama.
// Note that you need to call Drama.Unwrap() before calling this method if this Drama
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Drama) Update() *DramaUpdateOne {
	return NewDramaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Drama entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Drama) Unwrap() *Drama {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Drama is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Drama) String() string {
	var builder strings.Builder
	builder.WriteString("Drama(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("subtitle=")
	builder.WriteString(_m.Subtitle)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("cover=")
	builder.WriteString(_m.Cover)
	builder.WriteString(", ")
	builder.WriteString("country=")
	builder.WriteString(_m.Country)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("total_episodes=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalEpisodes))
	builder.WriteString(", ")
	builder.WriteString("is_paid=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPaid))
	builder.WriteString(", ")
	builder.WriteString("price_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceCents))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("popularity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Popularity))
	builder.WriteString(", ")
	builder.WriteString("completion_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletionRate))
	builder.WriteString(", ")
	builder.WriteString("pay_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.PayRate))
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Dramas is a parsable slice of Drama.
type Dramas []*Drama
