// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"short-drama-recommend/rpc/ent/drama"
	"short-drama-recommend/rpc/ent/dramagenre"
	"short-drama-recommend/rpc/ent/genre"
	"short-drama-recommend/rpc/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// DramaGenreQuery is the builder for querying DramaGenre entities.
type DramaGenreQuery struct {
	config
	ctx        *QueryContext
	order      []dramagenre.OrderOption
	inters     []Interceptor
	predicates []predicate.DramaGenre
	withDrama  *DramaQuery
	withGenre  *GenreQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DramaGenreQuery builder.
func (_q *DramaGenreQuery) Where(ps ...predicate.DramaGenre) *DramaGenreQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *DramaGenreQuery) Limit(limit int) *DramaGenreQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *DramaGenreQuery) Offset(offset int) *DramaGenreQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *DramaGenreQuery) Unique(unique bool) *DramaGenreQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *DramaGenreQuery) Order(o ...dramagenre.OrderOption) *DramaGenreQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryDrama chains the current query on the "drama" edge.
func (_q *DramaGenreQuery) QueryDrama() *DramaQuery {
	query := (&DramaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dramagenre.Table, dramagenre.DramaColumn, selector),
			sqlgraph.To(drama.Table, drama.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, dramagenre.DramaTable, dramagenre.DramaColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGenre chains the current query on the "genre" edge.
func (_q *DramaGenreQuery) QueryGenre() *GenreQuery {
	query := (&GenreClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(dramagenre.Table, dramagenre.GenreColumn, selector),
			sqlgraph.To(genre.Table, genre.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, dramagenre.GenreTable, dramagenre.GenreColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DramaGenre entity from the query.
// Returns a *NotFoundError when no DramaGenre was found.
func (_q *DramaGenreQuery) First(ctx context.Context) (*DramaGenre, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{dramagenre.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *DramaGenreQuery) FirstX(ctx context.Context) *DramaGenre {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single DramaGenre entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DramaGenre entity is found.
// Returns a *NotFoundError when no DramaGenre entities are found.
func (_q *DramaGenreQuery) Only(ctx context.Context) (*DramaGenre, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{dramagenre.Label}
	default:
		return nil, &NotSingularError{dramagenre.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *DramaGenreQuery) OnlyX(ctx context.Context) *DramaGenre {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of DramaGenres.
func (_q *DramaGenreQuery) All(ctx context.Context) ([]*DramaGenre, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DramaGenre, *DramaGenreQuery]()
	return withInterceptors[[]*DramaGenre](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *DramaGenreQuery) AllX(ctx context.Context) []*DramaGenre {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *DramaGenreQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*DramaGenreQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *DramaGenreQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *DramaGenreQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *DramaGenreQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DramaGenreQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *DramaGenreQuery) Clone() *DramaGenreQuery {
	if _q == nil {
		return nil
	}
	return &DramaGenreQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]dramagenre.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.DramaGenre{}, _q.predicates...),
		withDrama:  _q.withDrama.Clone(),
		withGenre:  _q.withGenre.Clone(),
		// clone intermediate query.
		sql:       _q.sql.Clone(),
		path:      _q.path,
		modifiers: append([]func(*sql.Selector){}, _q.modifiers...),
	}
}

// WithDrama tells the query-builder to eager-load the nodes that are connected to
// the "drama" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DramaGenreQuery) WithDrama(opts ...func(*DramaQuery)) *DramaGenreQuery {
	query := (&DramaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDrama = query
	return _q
}

// WithGenre tells the query-builder to eager-load the nodes that are connected to
// the "genre" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *DramaGenreQuery) WithGenre(opts ...func(*GenreQuery)) *DramaGenreQuery {
	query := (&GenreClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGenre = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DramaID uint64 `json:"drama_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DramaGenre.Query().
//		GroupBy(dramagenre.FieldDramaID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *DramaGenreQuery) GroupBy(field string, fields ...string) *DramaGenreGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DramaGenreGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = dramagenre.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DramaID uint64 `json:"drama_id,omitempty"`
//	}
//
//	client.DramaGenre.Query().
//		Select(dramagenre.FieldDramaID).
//		Scan(ctx, &v)
func (_q *DramaGenreQuery) Select(fields ...string) *DramaGenreSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &DramaGenreSelect{DramaGenreQuery: _q}
	sbuild.label = dramagenre.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DramaGenreSelect configured with the given aggregations.
func (_q *DramaGenreQuery) Aggregate(fns ...AggregateFunc) *DramaGenreSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *DramaGenreQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !dramagenre.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *DramaGenreQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DramaGenre, error) {
	var (
		nodes       = []*DramaGenre{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withDrama != nil,
			_q.withGenre != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DramaGenre).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DramaGenre{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withDrama; query != nil {
		if err := _q.loadDrama(ctx, query, nodes, nil,
			func(n *DramaGenre, e *Drama) { n.Edges.Drama = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGenre; query != nil {
		if err := _q.loadGenre(ctx, query, nodes, nil,
			func(n *DramaGenre, e *Genre) { n.Edges.Genre = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *DramaGenreQuery) loadDrama(ctx context.Context, query *DramaQuery, nodes []*DramaGenre, init func(*DramaGenre), assign func(*DramaGenre, *Drama)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*DramaGenre)
	for i := range nodes {
		fk := nodes[i].DramaID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(drama.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "drama_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *DramaGenreQuery) loadGenre(ctx context.Context, query *GenreQuery, nodes []*DramaGenre, init func(*DramaGenre), assign func(*DramaGenre, *Genre)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*DramaGenre)
	for i := range nodes {
		fk := nodes[i].GenreID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(genre.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "genre_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *DramaGenreQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *DramaGenreQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(dramagenre.Table, dramagenre.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withDrama != nil {
			_spec.Node.AddColumnOnce(dramagenre.FieldDramaID)
		}
		if _q.withGenre != nil {
			_spec.Node.AddColumnOnce(dramagenre.FieldGenreID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *DramaGenreQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(dramagenre.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = dramagenre.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_q *DramaGenreQuery) Modify(modifiers ...func(s *sql.Selector)) *DramaGenreSelect {
	_q.modifiers = append(_q.modifiers, modifiers...)
	return _q.Select()
}

// DramaGenreGroupBy is the group-by builder for DramaGenre entities.
type DramaGenreGroupBy struct {
	selector
	build *DramaGenreQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *DramaGenreGroupBy) Aggregate(fns ...AggregateFunc) *DramaGenreGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *DramaGenreGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DramaGenreQuery, *DramaGenreGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *DramaGenreGroupBy) sqlScan(ctx context.Context, root *DramaGenreQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DramaGenreSelect is the builder for selecting fields of DramaGenre entities.
type DramaGenreSelect struct {
	*DramaGenreQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *DramaGenreSelect) Aggregate(fns ...AggregateFunc) *DramaGenreSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *DramaGenreSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DramaGenreQuery, *DramaGenreSelect](ctx, _s.DramaGenreQuery, _s, _s.inters, v)
}

func (_s *DramaGenreSelect) sqlScan(ctx context.Context, root *DramaGenreQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (_s *DramaGenreSelect) Modify(modifiers ...func(s *sql.Selector)) *DramaGenreSelect {
	_s.modifiers = append(_s.modifiers, modifiers...)
	return _s
}
