// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"short-drama-recommend/rpc/ent/drama"
	"short-drama-recommend/rpc/ent/episode"
	"short-drama-recommend/rpc/ent/genre"
	"short-drama-recommend/rpc/ent/predicate"
	"short-drama-recommend/rpc/ent/tag"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DramaUpdate is the builder for updating Drama entities.
type DramaUpdate struct {
	config
	hooks     []Hook
	mutation  *DramaMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the DramaUpdate builder.
func (_u *DramaUpdate) Where(ps ...predicate.Drama) *DramaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *DramaUpdate) SetTitle(v string) *DramaUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableTitle(v *string) *DramaUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *DramaUpdate) SetSubtitle(v string) *DramaUpdate {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableSubtitle(v *string) *DramaUpdate {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DramaUpdate) SetDescription(v string) *DramaUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableDescription(v *string) *DramaUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *DramaUpdate) SetCover(v string) *DramaUpdate {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableCover(v *string) *DramaUpdate {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *DramaUpdate) SetCountry(v string) *DramaUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableCountry(v *string) *DramaUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *DramaUpdate) SetLanguage(v string) *DramaUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableLanguage(v *string) *DramaUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTotalEpisodes sets the "total_episodes" field.
func (_u *DramaUpdate) SetTotalEpisodes(v uint32) *DramaUpdate {
	_u.mutation.ResetTotalEpisodes()
	_u.mutation.SetTotalEpisodes(v)
	return _u
}

// SetNillableTotalEpisodes sets the "total_episodes" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableTotalEpisodes(v *uint32) *DramaUpdate {
	if v != nil {
		_u.SetTotalEpisodes(*v)
	}
	return _u
}

// AddTotalEpisodes adds value to the "total_episodes" field.
func (_u *DramaUpdate) AddTotalEpisodes(v int32) *DramaUpdate {
	_u.mutation.AddTotalEpisodes(v)
	return _u
}

// SetIsPaid sets the "is_paid" field.
func (_u *DramaUpdate) SetIsPaid(v bool) *DramaUpdate {
	_u.mutation.SetIsPaid(v)
	return _u
}

// SetNillableIsPaid sets the "is_paid" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableIsPaid(v *bool) *DramaUpdate {
	if v != nil {
		_u.SetIsPaid(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *DramaUpdate) SetPriceCents(v uint64) *DramaUpdate {
	_u.mutation.ResetPriceCents()
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *DramaUpdate) SetNillablePriceCents(v *uint64) *DramaUpdate {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds value to the "price_cents" field.
func (_u *DramaUpdate) AddPriceCents(v int64) *DramaUpdate {
	_u.mutation.AddPriceCents(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *DramaUpdate) SetCurrency(v string) *DramaUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableCurrency(v *string) *DramaUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DramaUpdate) SetStatus(v int8) *DramaUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableStatus(v *int8) *DramaUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DramaUpdate) AddStatus(v int8) *DramaUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPopularity sets the "popularity" field.
func (_u *DramaUpdate) SetPopularity(v float64) *DramaUpdate {
	_u.mutation.ResetPopularity()
	_u.mutation.SetPopularity(v)
	return _u
}

// SetNillablePopularity sets the "popularity" field if the given value is not nil.
func (_u *DramaUpdate) SetNillablePopularity(v *float64) *DramaUpdate {
	if v != nil {
		_u.SetPopularity(*v)
	}
	return _u
}

// AddPopularity adds value to the "popularity" field.
func (_u *DramaUpdate) AddPopularity(v float64) *DramaUpdate {
	_u.mutation.AddPopularity(v)
	return _u
}

// SetCompletionRate sets the "completion_rate" field.
func (_u *DramaUpdate) SetCompletionRate(v float64) *DramaUpdate {
	_u.mutation.ResetCompletionRate()
	_u.mutation.SetCompletionRate(v)
	return _u
}

// SetNillableCompletionRate sets the "completion_rate" field if the given value is not nil.
func (_u *DramaUpdate) SetNillableCompletionRate(v *float64) *DramaUpdate {
	if v != nil {
		_u.SetCompletionRate(*v)
	}
	return _u
}

// AddCompletionRate adds value to the "completion_rate" field.
func (_u *DramaUpdate) AddCompletionRate(v float64) *DramaUpdate {
	_u.mutation.AddCompletionRate(v)
	return _u
}

// SetPayRate sets the "pay_rate" field.
func (_u *DramaUpdate) SetPayRate(v float64) *DramaUpdate {
	_u.mutation.ResetPayRate()
	_u.mutation.SetPayRate(v)
	return _u
}

// SetNillablePayRate sets the "pay_rate" field if the given value is not nil.
func (_u *DramaUpdate) SetNillablePayRate(v *float64) *DramaUpdate {
	if v != nil {
		_u.SetPayRate(*v)
	}
	return _u
}

// AddPayRate adds value to the "pay_rate" field.
func (_u *DramaUpdate) AddPayRate(v float64) *DramaUpdate {
	_u.mutation.AddPayRate(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *DramaUpdate) SetPublishedAt(v time.Time) *DramaUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *DramaUpdate) SetNillablePublishedAt(v *time.Time) *DramaUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *DramaUpdate) ClearPublishedAt() *DramaUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DramaUpdate) SetUpdatedAt(v time.Time) *DramaUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEpisodeIDs adds the "episodes" edge to the Episode entity by IDs.
func (_u *DramaUpdate) AddEpisodeIDs(ids ...uint64) *DramaUpdate {
	_u.mutation.AddEpisodeIDs(ids...)
	return _u
}

// AddEpisodes adds the "episodes" edges to the Episode entity.
func (_u *DramaUpdate) AddEpisodes(v ...*Episode) *DramaUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEpisodeIDs(ids...)
}

// AddGenreIDs adds the "genres" edge to the Genre entity by IDs.
func (_u *DramaUpdate) AddGenreIDs(ids ...uint64) *DramaUpdate {
	_u.mutation.AddGenreIDs(ids...)
	return _u
}

// AddGenres adds the "genres" edges to the Genre entity.
func (_u *DramaUpdate) AddGenres(v ...*Genre) *DramaUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGenreIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *DramaUpdate) AddTagIDs(ids ...uint64) *DramaUpdate {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *DramaUpdate) AddTags(v ...*Tag) *DramaUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the DramaMutation object of the builder.
func (_u *DramaUpdate) Mutation() *DramaMutation {
	return _u.mutation
}

// ClearEpisodes clears all "episodes" edges to the Episode entity.
func (_u *DramaUpdate) ClearEpisodes() *DramaUpdate {
	_u.mutation.ClearEpisodes()
	return _u
}

// RemoveEpisodeIDs removes the "episodes" edge to Episode entities by IDs.
func (_u *DramaUpdate) RemoveEpisodeIDs(ids ...uint64) *DramaUpdate {
	_u.mutation.RemoveEpisodeIDs(ids...)
	return _u
}

// RemoveEpisodes removes "episodes" edges to Episode entities.
func (_u *DramaUpdate) RemoveEpisodes(v ...*Episode) *DramaUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEpisodeIDs(ids...)
}

// ClearGenres clears all "genres" edges to the Genre entity.
func (_u *DramaUpdate) ClearGenres() *DramaUpdate {
	_u.mutation.ClearGenres()
	return _u
}

// RemoveGenreIDs removes the "genres" edge to Genre entities by IDs.
func (_u *DramaUpdate) RemoveGenreIDs(ids ...uint64) *DramaUpdate {
	_u.mutation.RemoveGenreIDs(ids...)
	return _u
}

// RemoveGenres removes "genres" edges to Genre entities.
func (_u *DramaUpdate) RemoveGenres(v ...*Genre) *DramaUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGenreIDs(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *DramaUpdate) ClearTags() *DramaUpdate {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *DramaUpdate) RemoveTagIDs(ids ...uint64) *DramaUpdate {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *DramaUpdate) RemoveTags(v ...*Tag) *DramaUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DramaUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DramaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DramaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DramaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DramaUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := drama.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DramaUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DramaUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DramaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(drama.Table, drama.Columns, sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(drama.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(drama.FieldSubtitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(drama.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(drama.FieldCover, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(drama.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(drama.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalEpisodes(); ok {
		_spec.SetField(drama.FieldTotalEpisodes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTotalEpisodes(); ok {
		_spec.AddField(drama.FieldTotalEpisodes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.IsPaid(); ok {
		_spec.SetField(drama.FieldIsPaid, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PriceCents(); ok {
		_spec.SetField(drama.FieldPriceCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedPriceCents(); ok {
		_spec.AddField(drama.FieldPriceCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(drama.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(drama.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(drama.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Popularity(); ok {
		_spec.SetField(drama.FieldPopularity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPopularity(); ok {
		_spec.AddField(drama.FieldPopularity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CompletionRate(); ok {
		_spec.SetField(drama.FieldCompletionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCompletionRate(); ok {
		_spec.AddField(drama.FieldCompletionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PayRate(); ok {
		_spec.SetField(drama.FieldPayRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPayRate(); ok {
		_spec.AddField(drama.FieldPayRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(drama.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(drama.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(drama.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EpisodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drama.EpisodesTable,
			Columns: []string{drama.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEpisodesIDs(); len(nodes) > 0 && !_u.mutation.EpisodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drama.EpisodesTable,
			Columns: []string{drama.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EpisodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drama.EpisodesTable,
			Columns: []string{drama.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.GenresTable,
			Columns: drama.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGenresIDs(); len(nodes) > 0 && !_u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.GenresTable,
			Columns: drama.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GenresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.GenresTable,
			Columns: drama.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.TagsTable,
			Columns: drama.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.TagsTable,
			Columns: drama.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.TagsTable,
			Columns: drama.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drama.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DramaUpdateOne is the builder for updating a single Drama entity.
type DramaUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *DramaMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTitle sets the "title" field.
func (_u *DramaUpdateOne) SetTitle(v string) *DramaUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableTitle(v *string) *DramaUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetSubtitle sets the "subtitle" field.
func (_u *DramaUpdateOne) SetSubtitle(v string) *DramaUpdateOne {
	_u.mutation.SetSubtitle(v)
	return _u
}

// SetNillableSubtitle sets the "subtitle" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableSubtitle(v *string) *DramaUpdateOne {
	if v != nil {
		_u.SetSubtitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *DramaUpdateOne) SetDescription(v string) *DramaUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableDescription(v *string) *DramaUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *DramaUpdateOne) SetCover(v string) *DramaUpdateOne {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableCover(v *string) *DramaUpdateOne {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *DramaUpdateOne) SetCountry(v string) *DramaUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableCountry(v *string) *DramaUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *DramaUpdateOne) SetLanguage(v string) *DramaUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableLanguage(v *string) *DramaUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// SetTotalEpisodes sets the "total_episodes" field.
func (_u *DramaUpdateOne) SetTotalEpisodes(v uint32) *DramaUpdateOne {
	_u.mutation.ResetTotalEpisodes()
	_u.mutation.SetTotalEpisodes(v)
	return _u
}

// SetNillableTotalEpisodes sets the "total_episodes" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableTotalEpisodes(v *uint32) *DramaUpdateOne {
	if v != nil {
		_u.SetTotalEpisodes(*v)
	}
	return _u
}

// AddTotalEpisodes adds value to the "total_episodes" field.
func (_u *DramaUpdateOne) AddTotalEpisodes(v int32) *DramaUpdateOne {
	_u.mutation.AddTotalEpisodes(v)
	return _u
}

// SetIsPaid sets the "is_paid" field.
func (_u *DramaUpdateOne) SetIsPaid(v bool) *DramaUpdateOne {
	_u.mutation.SetIsPaid(v)
	return _u
}

// SetNillableIsPaid sets the "is_paid" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableIsPaid(v *bool) *DramaUpdateOne {
	if v != nil {
		_u.SetIsPaid(*v)
	}
	return _u
}

// SetPriceCents sets the "price_cents" field.
func (_u *DramaUpdateOne) SetPriceCents(v uint64) *DramaUpdateOne {
	_u.mutation.ResetPriceCents()
	_u.mutation.SetPriceCents(v)
	return _u
}

// SetNillablePriceCents sets the "price_cents" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillablePriceCents(v *uint64) *DramaUpdateOne {
	if v != nil {
		_u.SetPriceCents(*v)
	}
	return _u
}

// AddPriceCents adds value to the "price_cents" field.
func (_u *DramaUpdateOne) AddPriceCents(v int64) *DramaUpdateOne {
	_u.mutation.AddPriceCents(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *DramaUpdateOne) SetCurrency(v string) *DramaUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableCurrency(v *string) *DramaUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DramaUpdateOne) SetStatus(v int8) *DramaUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableStatus(v *int8) *DramaUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DramaUpdateOne) AddStatus(v int8) *DramaUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPopularity sets the "popularity" field.
func (_u *DramaUpdateOne) SetPopularity(v float64) *DramaUpdateOne {
	_u.mutation.ResetPopularity()
	_u.mutation.SetPopularity(v)
	return _u
}

// SetNillablePopularity sets the "popularity" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillablePopularity(v *float64) *DramaUpdateOne {
	if v != nil {
		_u.SetPopularity(*v)
	}
	return _u
}

// AddPopularity adds value to the "popularity" field.
func (_u *DramaUpdateOne) AddPopularity(v float64) *DramaUpdateOne {
	_u.mutation.AddPopularity(v)
	return _u
}

// SetCompletionRate sets the "completion_rate" field.
func (_u *DramaUpdateOne) SetCompletionRate(v float64) *DramaUpdateOne {
	_u.mutation.ResetCompletionRate()
	_u.mutation.SetCompletionRate(v)
	return _u
}

// SetNillableCompletionRate sets the "completion_rate" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillableCompletionRate(v *float64) *DramaUpdateOne {
	if v != nil {
		_u.SetCompletionRate(*v)
	}
	return _u
}

// AddCompletionRate adds value to the "completion_rate" field.
func (_u *DramaUpdateOne) AddCompletionRate(v float64) *DramaUpdateOne {
	_u.mutation.AddCompletionRate(v)
	return _u
}

// SetPayRate sets the "pay_rate" field.
func (_u *DramaUpdateOne) SetPayRate(v float64) *DramaUpdateOne {
	_u.mutation.ResetPayRate()
	_u.mutation.SetPayRate(v)
	return _u
}

// SetNillablePayRate sets the "pay_rate" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillablePayRate(v *float64) *DramaUpdateOne {
	if v != nil {
		_u.SetPayRate(*v)
	}
	return _u
}

// AddPayRate adds value to the "pay_rate" field.
func (_u *DramaUpdateOne) AddPayRate(v float64) *DramaUpdateOne {
	_u.mutation.AddPayRate(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *DramaUpdateOne) SetPublishedAt(v time.Time) *DramaUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *DramaUpdateOne) SetNillablePublishedAt(v *time.Time) *DramaUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *DramaUpdateOne) ClearPublishedAt() *DramaUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DramaUpdateOne) SetUpdatedAt(v time.Time) *DramaUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddEpisodeIDs adds the "episodes" edge to the Episode entity by IDs.
func (_u *DramaUpdateOne) AddEpisodeIDs(ids ...uint64) *DramaUpdateOne {
	_u.mutation.AddEpisodeIDs(ids...)
	return _u
}

// AddEpisodes adds the "episodes" edges to the Episode entity.
func (_u *DramaUpdateOne) AddEpisodes(v ...*Episode) *DramaUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEpisodeIDs(ids...)
}

// AddGenreIDs adds the "genres" edge to the Genre entity by IDs.
func (_u *DramaUpdateOne) AddGenreIDs(ids ...uint64) *DramaUpdateOne {
	_u.mutation.AddGenreIDs(ids...)
	return _u
}

// AddGenres adds the "genres" edges to the Genre entity.
func (_u *DramaUpdateOne) AddGenres(v ...*Genre) *DramaUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddGenreIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (_u *DramaUpdateOne) AddTagIDs(ids ...uint64) *DramaUpdateOne {
	_u.mutation.AddTagIDs(ids...)
	return _u
}

// AddTags adds the "tags" edges to the Tag entity.
func (_u *DramaUpdateOne) AddTags(v ...*Tag) *DramaUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTagIDs(ids...)
}

// Mutation returns the DramaMutation object of the builder.
func (_u *DramaUpdateOne) Mutation() *DramaMutation {
	return _u.mutation
}

// ClearEpisodes clears all "episodes" edges to the Episode entity.
func (_u *DramaUpdateOne) ClearEpisodes() *DramaUpdateOne {
	_u.mutation.ClearEpisodes()
	return _u
}

// RemoveEpisodeIDs removes the "episodes" edge to Episode entities by IDs.
func (_u *DramaUpdateOne) RemoveEpisodeIDs(ids ...uint64) *DramaUpdateOne {
	_u.mutation.RemoveEpisodeIDs(ids...)
	return _u
}

// RemoveEpisodes removes "episodes" edges to Episode entities.
func (_u *DramaUpdateOne) RemoveEpisodes(v ...*Episode) *DramaUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEpisodeIDs(ids...)
}

// ClearGenres clears all "genres" edges to the Genre entity.
func (_u *DramaUpdateOne) ClearGenres() *DramaUpdateOne {
	_u.mutation.ClearGenres()
	return _u
}

// RemoveGenreIDs removes the "genres" edge to Genre entities by IDs.
func (_u *DramaUpdateOne) RemoveGenreIDs(ids ...uint64) *DramaUpdateOne {
	_u.mutation.RemoveGenreIDs(ids...)
	return _u
}

// RemoveGenres removes "genres" edges to Genre entities.
func (_u *DramaUpdateOne) RemoveGenres(v ...*Genre) *DramaUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveGenreIDs(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (_u *DramaUpdateOne) ClearTags() *DramaUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (_u *DramaUpdateOne) RemoveTagIDs(ids ...uint64) *DramaUpdateOne {
	_u.mutation.RemoveTagIDs(ids...)
	return _u
}

// RemoveTags removes "tags" edges to Tag entities.
func (_u *DramaUpdateOne) RemoveTags(v ...*Tag) *DramaUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTagIDs(ids...)
}

// Where appends a list predicates to the DramaUpdate builder.
func (_u *DramaUpdateOne) Where(ps ...predicate.Drama) *DramaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DramaUpdateOne) Select(field string, fields ...string) *DramaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Drama entity.
func (_u *DramaUpdateOne) Save(ctx context.Context) (*Drama, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DramaUpdateOne) SaveX(ctx context.Context) *Drama {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DramaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DramaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DramaUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := drama.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *DramaUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *DramaUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *DramaUpdateOne) sqlSave(ctx context.Context) (_node *Drama, err error) {
	_spec := sqlgraph.NewUpdateSpec(drama.Table, drama.Columns, sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Drama.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, drama.FieldID)
		for _, f := range fields {
			if !drama.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != drama.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(drama.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Subtitle(); ok {
		_spec.SetField(drama.FieldSubtitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(drama.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(drama.FieldCover, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(drama.FieldCountry, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(drama.FieldLanguage, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalEpisodes(); ok {
		_spec.SetField(drama.FieldTotalEpisodes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTotalEpisodes(); ok {
		_spec.AddField(drama.FieldTotalEpisodes, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.IsPaid(); ok {
		_spec.SetField(drama.FieldIsPaid, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PriceCents(); ok {
		_spec.SetField(drama.FieldPriceCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedPriceCents(); ok {
		_spec.AddField(drama.FieldPriceCents, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(drama.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(drama.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(drama.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Popularity(); ok {
		_spec.SetField(drama.FieldPopularity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPopularity(); ok {
		_spec.AddField(drama.FieldPopularity, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CompletionRate(); ok {
		_spec.SetField(drama.FieldCompletionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCompletionRate(); ok {
		_spec.AddField(drama.FieldCompletionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PayRate(); ok {
		_spec.SetField(drama.FieldPayRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPayRate(); ok {
		_spec.AddField(drama.FieldPayRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(drama.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(drama.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(drama.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.EpisodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drama.EpisodesTable,
			Columns: []string{drama.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEpisodesIDs(); len(nodes) > 0 && !_u.mutation.EpisodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drama.EpisodesTable,
			Columns: []string{drama.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EpisodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   drama.EpisodesTable,
			Columns: []string{drama.EpisodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.GenresTable,
			Columns: drama.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedGenresIDs(); len(nodes) > 0 && !_u.mutation.GenresCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.GenresTable,
			Columns: drama.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GenresIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.GenresTable,
			Columns: drama.GenresPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.TagsTable,
			Columns: drama.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTagsIDs(); len(nodes) > 0 && !_u.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.TagsTable,
			Columns: drama.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   drama.TagsTable,
			Columns: drama.TagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Drama{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{drama.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
