// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"short-drama-recommend/rpc/ent/drama"
	"short-drama-recommend/rpc/ent/episode"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EpisodeCreate is the builder for creating a Episode entity.
type EpisodeCreate struct {
	config
	mutation *EpisodeMutation
	hooks    []Hook
}

// SetDramaID sets the "drama_id" field.
func (_c *EpisodeCreate) SetDramaID(v uint64) *EpisodeCreate {
	_c.mutation.SetDramaID(v)
	return _c
}

// SetEpisodeNo sets the "episode_no" field.
func (_c *EpisodeCreate) SetEpisodeNo(v uint32) *EpisodeCreate {
	_c.mutation.SetEpisodeNo(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *EpisodeCreate) SetTitle(v string) *EpisodeCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableTitle(v *string) *EpisodeCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *EpisodeCreate) SetDescription(v string) *EpisodeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableDescription(v *string) *EpisodeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_c *EpisodeCreate) SetDurationSeconds(v uint32) *EpisodeCreate {
	_c.mutation.SetDurationSeconds(v)
	return _c
}

// SetNillableDurationSeconds sets the "duration_seconds" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableDurationSeconds(v *uint32) *EpisodeCreate {
	if v != nil {
		_c.SetDurationSeconds(*v)
	}
	return _c
}

// SetVideoURL sets the "video_url" field.
func (_c *EpisodeCreate) SetVideoURL(v string) *EpisodeCreate {
	_c.mutation.SetVideoURL(v)
	return _c
}

// SetNillableVideoURL sets the "video_url" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableVideoURL(v *string) *EpisodeCreate {
	if v != nil {
		_c.SetVideoURL(*v)
	}
	return _c
}

// SetPosterURL sets the "poster_url" field.
func (_c *EpisodeCreate) SetPosterURL(v string) *EpisodeCreate {
	_c.mutation.SetPosterURL(v)
	return _c
}

// SetNillablePosterURL sets the "poster_url" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillablePosterURL(v *string) *EpisodeCreate {
	if v != nil {
		_c.SetPosterURL(*v)
	}
	return _c
}

// SetIsPaid sets the "is_paid" field.
func (_c *EpisodeCreate) SetIsPaid(v bool) *EpisodeCreate {
	_c.mutation.SetIsPaid(v)
	return _c
}

// SetNillableIsPaid sets the "is_paid" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableIsPaid(v *bool) *EpisodeCreate {
	if v != nil {
		_c.SetIsPaid(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *EpisodeCreate) SetStatus(v int8) *EpisodeCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableStatus(v *int8) *EpisodeCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *EpisodeCreate) SetCreatedAt(v time.Time) *EpisodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableCreatedAt(v *time.Time) *EpisodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *EpisodeCreate) SetUpdatedAt(v time.Time) *EpisodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *EpisodeCreate) SetNillableUpdatedAt(v *time.Time) *EpisodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *EpisodeCreate) SetID(v uint64) *EpisodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetDrama sets the "drama" edge to the Drama entity.
func (_c *EpisodeCreate) SetDrama(v *Drama) *EpisodeCreate {
	return _c.SetDramaID(v.ID)
}

// Mutation returns the EpisodeMutation object of the builder.
func (_c *EpisodeCreate) Mutation() *EpisodeMutation {
	return _c.mutation
}

// Save creates the Episode in the database.
func (_c *EpisodeCreate) Save(ctx context.Context) (*Episode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EpisodeCreate) SaveX(ctx context.Context) *Episode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EpisodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EpisodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EpisodeCreate) defaults() {
	if _, ok := _c.mutation.Title(); !ok {
		v := episode.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := episode.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		v := episode.DefaultDurationSeconds
		_c.mutation.SetDurationSeconds(v)
	}
	if _, ok := _c.mutation.VideoURL(); !ok {
		v := episode.DefaultVideoURL
		_c.mutation.SetVideoURL(v)
	}
	if _, ok := _c.mutation.PosterURL(); !ok {
		v := episode.DefaultPosterURL
		_c.mutation.SetPosterURL(v)
	}
	if _, ok := _c.mutation.IsPaid(); !ok {
		v := episode.DefaultIsPaid
		_c.mutation.SetIsPaid(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := episode.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := episode.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := episode.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EpisodeCreate) check() error {
	if _, ok := _c.mutation.DramaID(); !ok {
		return &ValidationError{Name: "drama_id", err: errors.New(`ent: missing required field "Episode.drama_id"`)}
	}
	if _, ok := _c.mutation.EpisodeNo(); !ok {
		return &ValidationError{Name: "episode_no", err: errors.New(`ent: missing required field "Episode.episode_no"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Episode.title"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Episode.description"`)}
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		return &ValidationError{Name: "duration_seconds", err: errors.New(`ent: missing required field "Episode.duration_seconds"`)}
	}
	if _, ok := _c.mutation.VideoURL(); !ok {
		return &ValidationError{Name: "video_url", err: errors.New(`ent: missing required field "Episode.video_url"`)}
	}
	if _, ok := _c.mutation.PosterURL(); !ok {
		return &ValidationError{Name: "poster_url", err: errors.New(`ent: missing required field "Episode.poster_url"`)}
	}
	if _, ok := _c.mutation.IsPaid(); !ok {
		return &ValidationError{Name: "is_paid", err: errors.New(`ent: missing required field "Episode.is_paid"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Episode.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Episode.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Episode.updated_at"`)}
	}
	if len(_c.mutation.DramaIDs()) == 0 {
		return &ValidationError{Name: "drama", err: errors.New(`ent: missing required edge "Episode.drama"`)}
	}
	return nil
}

func (_c *EpisodeCreate) sqlSave(ctx context.Context) (*Episode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EpisodeCreate) createSpec() (*Episode, *sqlgraph.CreateSpec) {
	var (
		_node = &Episode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(episode.Table, sqlgraph.NewFieldSpec(episode.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.EpisodeNo(); ok {
		_spec.SetField(episode.FieldEpisodeNo, field.TypeUint32, value)
		_node.EpisodeNo = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(episode.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(episode.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.DurationSeconds(); ok {
		_spec.SetField(episode.FieldDurationSeconds, field.TypeUint32, value)
		_node.DurationSeconds = value
	}
	if value, ok := _c.mutation.VideoURL(); ok {
		_spec.SetField(episode.FieldVideoURL, field.TypeString, value)
		_node.VideoURL = value
	}
	if value, ok := _c.mutation.PosterURL(); ok {
		_spec.SetField(episode.FieldPosterURL, field.TypeString, value)
		_node.PosterURL = value
	}
	if value, ok := _c.mutation.IsPaid(); ok {
		_spec.SetField(episode.FieldIsPaid, field.TypeBool, value)
		_node.IsPaid = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(episode.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(episode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(episode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.DramaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   episode.DramaTable,
			Columns: []string{episode.DramaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DramaID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EpisodeCreateBulk is the builder for creating many Episode entities in bulk.
type EpisodeCreateBulk struct {
	config
	err      error
	builders []*EpisodeCreate
}

// Save creates the Episode entities in the database.
func (_c *EpisodeCreateBulk) Save(ctx context.Context) ([]*Episode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Episode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EpisodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EpisodeCreateBulk) SaveX(ctx context.Context) []*Episode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EpisodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EpisodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
