// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"short-drama-recommend/rpc/ent/drama"
	"short-drama-recommend/rpc/ent/genre"
	"short-drama-recommend/rpc/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GenreUpdate is the builder for updating Genre entities.
type GenreUpdate struct {
	config
	hooks     []Hook
	mutation  *GenreMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the GenreUpdate builder.
func (_u *GenreUpdate) Where(ps ...predicate.Genre) *GenreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *GenreUpdate) SetName(v string) *GenreUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GenreUpdate) SetNillableName(v *string) *GenreUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *GenreUpdate) SetLanguage(v string) *GenreUpdate {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *GenreUpdate) SetNillableLanguage(v *string) *GenreUpdate {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// AddDramaIDs adds the "dramas" edge to the Drama entity by IDs.
func (_u *GenreUpdate) AddDramaIDs(ids ...uint64) *GenreUpdate {
	_u.mutation.AddDramaIDs(ids...)
	return _u
}

// AddDramas adds the "dramas" edges to the Drama entity.
func (_u *GenreUpdate) AddDramas(v ...*Drama) *GenreUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDramaIDs(ids...)
}

// Mutation returns the GenreMutation object of the builder.
func (_u *GenreUpdate) Mutation() *GenreMutation {
	return _u.mutation
}

// ClearDramas clears all "dramas" edges to the Drama entity.
func (_u *GenreUpdate) ClearDramas() *GenreUpdate {
	_u.mutation.ClearDramas()
	return _u
}

// RemoveDramaIDs removes the "dramas" edge to Drama entities by IDs.
func (_u *GenreUpdate) RemoveDramaIDs(ids ...uint64) *GenreUpdate {
	_u.mutation.RemoveDramaIDs(ids...)
	return _u
}

// RemoveDramas removes "dramas" edges to Drama entities.
func (_u *GenreUpdate) RemoveDramas(v ...*Drama) *GenreUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDramaIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GenreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GenreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GenreUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GenreUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GenreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(genre.Table, genre.Columns, sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(genre.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(genre.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.DramasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.DramasTable,
			Columns: genre.DramasPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDramasIDs(); len(nodes) > 0 && !_u.mutation.DramasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.DramasTable,
			Columns: genre.DramasPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DramasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.DramasTable,
			Columns: genre.DramasPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{genre.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GenreUpdateOne is the builder for updating a single Genre entity.
type GenreUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *GenreMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (_u *GenreUpdateOne) SetName(v string) *GenreUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GenreUpdateOne) SetNillableName(v *string) *GenreUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLanguage sets the "language" field.
func (_u *GenreUpdateOne) SetLanguage(v string) *GenreUpdateOne {
	_u.mutation.SetLanguage(v)
	return _u
}

// SetNillableLanguage sets the "language" field if the given value is not nil.
func (_u *GenreUpdateOne) SetNillableLanguage(v *string) *GenreUpdateOne {
	if v != nil {
		_u.SetLanguage(*v)
	}
	return _u
}

// AddDramaIDs adds the "dramas" edge to the Drama entity by IDs.
func (_u *GenreUpdateOne) AddDramaIDs(ids ...uint64) *GenreUpdateOne {
	_u.mutation.AddDramaIDs(ids...)
	return _u
}

// AddDramas adds the "dramas" edges to the Drama entity.
func (_u *GenreUpdateOne) AddDramas(v ...*Drama) *GenreUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDramaIDs(ids...)
}

// Mutation returns the GenreMutation object of the builder.
func (_u *GenreUpdateOne) Mutation() *GenreMutation {
	return _u.mutation
}

// ClearDramas clears all "dramas" edges to the Drama entity.
func (_u *GenreUpdateOne) ClearDramas() *GenreUpdateOne {
	_u.mutation.ClearDramas()
	return _u
}

// RemoveDramaIDs removes the "dramas" edge to Drama entities by IDs.
func (_u *GenreUpdateOne) RemoveDramaIDs(ids ...uint64) *GenreUpdateOne {
	_u.mutation.RemoveDramaIDs(ids...)
	return _u
}

// RemoveDramas removes "dramas" edges to Drama entities.
func (_u *GenreUpdateOne) RemoveDramas(v ...*Drama) *GenreUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDramaIDs(ids...)
}

// Where appends a list predicates to the GenreUpdate builder.
func (_u *GenreUpdateOne) Where(ps ...predicate.Genre) *GenreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GenreUpdateOne) Select(field string, fields ...string) *GenreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Genre entity.
func (_u *GenreUpdateOne) Save(ctx context.Context) (*Genre, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GenreUpdateOne) SaveX(ctx context.Context) *Genre {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GenreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GenreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *GenreUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *GenreUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *GenreUpdateOne) sqlSave(ctx context.Context) (_node *Genre, err error) {
	_spec := sqlgraph.NewUpdateSpec(genre.Table, genre.Columns, sqlgraph.NewFieldSpec(genre.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Genre.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, genre.FieldID)
		for _, f := range fields {
			if !genre.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != genre.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(genre.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Language(); ok {
		_spec.SetField(genre.FieldLanguage, field.TypeString, value)
	}
	if _u.mutation.DramasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.DramasTable,
			Columns: genre.DramasPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDramasIDs(); len(nodes) > 0 && !_u.mutation.DramasCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.DramasTable,
			Columns: genre.DramasPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DramasIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   genre.DramasTable,
			Columns: genre.DramasPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(drama.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Genre{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{genre.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
