// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"short-drama-recommend/rpc/ent/genre"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Genre is the model entity for the Genre schema.
type Genre struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Language holds the value of the "language" field.
	Language string `json:"language,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GenreQuery when eager-loading is set.
	Edges        GenreEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GenreEdges holds the relations/edges for other nodes in the graph.
type GenreEdges struct {
	// Dramas holds the value of the dramas edge.
	Dramas []*Drama `json:"dramas,omitempty"`
	// DramaGenres holds the value of the drama_genres edge.
	DramaGenres []*DramaGenre `json:"drama_genres,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// DramasOrErr returns the Dramas value or an error if the edge
// was not loaded in eager-loading.
func (e GenreEdges) DramasOrErr() ([]*Drama, error) {
	if e.loadedTypes[0] {
		return e.Dramas, nil
	}
	return nil, &NotLoadedError{edge: "dramas"}
}

// DramaGenresOrErr returns the DramaGenres value or an error if the edge
// was not loaded in eager-loading.
func (e GenreEdges) DramaGenresOrErr() ([]*DramaGenre, error) {
	if e.loadedTypes[1] {
		return e.DramaGenres, nil
	}
	return nil, &NotLoadedError{edge: "drama_genres"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Genre) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case genre.FieldID:
			values[i] = new(sql.NullInt64)
		case genre.FieldName, genre.FieldLanguage:
			values[i] = new(sql.NullString)
		case genre.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Genre fields.
func (_m *Genre) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case genre.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case genre.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case genre.FieldLanguage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field language", values[i])
			} else if value.Valid {
				_m.Language = value.String
			}
		case genre.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Genre.
// This includes values selected through modifiers, order, etc.
func (_m *Genre) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDramas queries the "dramas" edge of the Genre entity.
func (_m *Genre) QueryDramas() *DramaQuery {
	return NewGenreClient(_m.config).QueryDramas(_m)
}

// QueryDramaGenres queries the "drama_genres" edge of the Genre entity.
func (_m *Genre) QueryDramaGenres() *DramaGenreQuery {
	return NewGenreClient(_m.config).QueryDramaGenres(_m)
}

// Update returns a builder for updating this Genre.
// Note that you need to call Genre.Unwrap() before calling this method if this Genre
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Genre) Update() *GenreUpdateOne {
	return NewGenreClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Genre entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Genre) Unwrap() *Genre {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Genre is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Genre) String() string {
	var builder strings.Builder
	builder.WriteString("Genre(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("language=")
	builder.WriteString(_m.Language)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Genres is a parsable slice of Genre.
type Genres []*Genre
