// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"short-drama-recommend/rpc/ent/predicate"
	"short-drama-recommend/rpc/ent/usertagprofile"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTagProfileDelete is the builder for deleting a UserTagProfile entity.
type UserTagProfileDelete struct {
	config
	hooks    []Hook
	mutation *UserTagProfileMutation
}

// Where appends a list predicates to the UserTagProfileDelete builder.
func (_d *UserTagProfileDelete) Where(ps ...predicate.UserTagProfile) *UserTagProfileDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserTagProfileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserTagProfileDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserTagProfileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usertagprofile.Table, sqlgraph.NewFieldSpec(usertagprofile.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserTagProfileDeleteOne is the builder for deleting a single UserTagProfile entity.
type UserTagProfileDeleteOne struct {
	_d *UserTagProfileDelete
}

// Where appends a list predicates to the UserTagProfileDelete builder.
func (_d *UserTagProfileDeleteOne) Where(ps ...predicate.UserTagProfile) *UserTagProfileDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserTagProfileDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usertagprofile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserTagProfileDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
