// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"short-drama-recommend/rpc/ent/predicate"
	"short-drama-recommend/rpc/ent/usertagprofile"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTagProfileUpdate is the builder for updating UserTagProfile entities.
type UserTagProfileUpdate struct {
	config
	hooks     []Hook
	mutation  *UserTagProfileMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UserTagProfileUpdate builder.
func (_u *UserTagProfileUpdate) Where(ps ...predicate.UserTagProfile) *UserTagProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserTagProfileUpdate) SetUserID(v uint64) *UserTagProfileUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserTagProfileUpdate) SetNillableUserID(v *uint64) *UserTagProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserTagProfileUpdate) AddUserID(v int64) *UserTagProfileUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *UserTagProfileUpdate) SetTagID(v uint64) *UserTagProfileUpdate {
	_u.mutation.ResetTagID()
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *UserTagProfileUpdate) SetNillableTagID(v *uint64) *UserTagProfileUpdate {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// AddTagID adds value to the "tag_id" field.
func (_u *UserTagProfileUpdate) AddTagID(v int64) *UserTagProfileUpdate {
	_u.mutation.AddTagID(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *UserTagProfileUpdate) SetWeight(v float64) *UserTagProfileUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *UserTagProfileUpdate) SetNillableWeight(v *float64) *UserTagProfileUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *UserTagProfileUpdate) AddWeight(v float64) *UserTagProfileUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserTagProfileUpdate) SetUpdatedAt(v time.Time) *UserTagProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserTagProfileMutation object of the builder.
func (_u *UserTagProfileUpdate) Mutation() *UserTagProfileMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserTagProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTagProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserTagProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTagProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTagProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usertagprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserTagProfileUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserTagProfileUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserTagProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(usertagprofile.Table, usertagprofile.Columns, sqlgraph.NewFieldSpec(usertagprofile.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usertagprofile.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usertagprofile.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.TagID(); ok {
		_spec.SetField(usertagprofile.FieldTagID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTagID(); ok {
		_spec.AddField(usertagprofile.FieldTagID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(usertagprofile.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(usertagprofile.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usertagprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertagprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserTagProfileUpdateOne is the builder for updating a single UserTagProfile entity.
type UserTagProfileUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UserTagProfileMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (_u *UserTagProfileUpdateOne) SetUserID(v uint64) *UserTagProfileUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserTagProfileUpdateOne) SetNillableUserID(v *uint64) *UserTagProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UserTagProfileUpdateOne) AddUserID(v int64) *UserTagProfileUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetTagID sets the "tag_id" field.
func (_u *UserTagProfileUpdateOne) SetTagID(v uint64) *UserTagProfileUpdateOne {
	_u.mutation.ResetTagID()
	_u.mutation.SetTagID(v)
	return _u
}

// SetNillableTagID sets the "tag_id" field if the given value is not nil.
func (_u *UserTagProfileUpdateOne) SetNillableTagID(v *uint64) *UserTagProfileUpdateOne {
	if v != nil {
		_u.SetTagID(*v)
	}
	return _u
}

// AddTagID adds value to the "tag_id" field.
func (_u *UserTagProfileUpdateOne) AddTagID(v int64) *UserTagProfileUpdateOne {
	_u.mutation.AddTagID(v)
	return _u
}

// SetWeight sets the "weight" field.
func (_u *UserTagProfileUpdateOne) SetWeight(v float64) *UserTagProfileUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *UserTagProfileUpdateOne) SetNillableWeight(v *float64) *UserTagProfileUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *UserTagProfileUpdateOne) AddWeight(v float64) *UserTagProfileUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserTagProfileUpdateOne) SetUpdatedAt(v time.Time) *UserTagProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserTagProfileMutation object of the builder.
func (_u *UserTagProfileUpdateOne) Mutation() *UserTagProfileMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserTagProfileUpdate builder.
func (_u *UserTagProfileUpdateOne) Where(ps ...predicate.UserTagProfile) *UserTagProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserTagProfileUpdateOne) Select(field string, fields ...string) *UserTagProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserTagProfile entity.
func (_u *UserTagProfileUpdateOne) Save(ctx context.Context) (*UserTagProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTagProfileUpdateOne) SaveX(ctx context.Context) *UserTagProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserTagProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTagProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTagProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usertagprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *UserTagProfileUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UserTagProfileUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *UserTagProfileUpdateOne) sqlSave(ctx context.Context) (_node *UserTagProfile, err error) {
	_spec := sqlgraph.NewUpdateSpec(usertagprofile.Table, usertagprofile.Columns, sqlgraph.NewFieldSpec(usertagprofile.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserTagProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usertagprofile.FieldID)
		for _, f := range fields {
			if !usertagprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usertagprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usertagprofile.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usertagprofile.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.TagID(); ok {
		_spec.SetField(usertagprofile.FieldTagID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTagID(); ok {
		_spec.AddField(usertagprofile.FieldTagID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(usertagprofile.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(usertagprofile.FieldWeight, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usertagprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &UserTagProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usertagprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
