package rank

import("bytes";"context";"encoding/json";"fmt";"math";"net/http";"strings";"time")
type MMoEClient struct{address,model string;http *http.Client}
type Prediction struct{CTR float64;WatchProbs []float64;Completion float64;Pay float64}
func NewMMoEClient(address,model string)*MMoEClient{return &MMoEClient{address:strings.TrimRight(address,"/"),model:model,http:&http.Client{Timeout:120*time.Millisecond}}}
func(c *MMoEClient)Predict(ctx context.Context,features []float32)(Prediction,error){if c.address==""||c.model==""{return Prediction{},fmt.Errorf("mmoe endpoint/model is empty")};body:=map[string]any{"inputs":[]any{map[string]any{"name":"features","shape":[]int{1,len(features)},"datatype":"FP32","data":features}},"outputs":[]any{map[string]any{"name":"p_ctr"},map[string]any{"name":"watch_logits"},map[string]any{"name":"p_completion"},map[string]any{"name":"p_pay"}}};raw,err:=json.Marshal(body);if err!=nil{return Prediction{},err};req,err:=http.NewRequestWithContext(ctx,http.MethodPost,c.address+"/v2/models/"+c.model+"/infer",bytes.NewReader(raw));if err!=nil{return Prediction{},err};req.Header.Set("Content-Type","application/json");resp,err:=c.http.Do(req);if err!=nil{return Prediction{},err};defer resp.Body.Close();if resp.StatusCode<200||resp.StatusCode>=300{return Prediction{},fmt.Errorf("triton status=%d",resp.StatusCode)};var out map[string]any;if err=json.NewDecoder(resp.Body).Decode(&out);err!=nil{return Prediction{},err};p:=Prediction{};arr,_:=out["outputs"].([]any);for _,rawOut:=range arr{m,_:=rawOut.(map[string]any);name,_:=m["name"].(string);data,_:=m["data"].([]any);vals:=make([]float64,len(data));for i,v:=range data{vals[i],_=v.(float64)};switch name{case"p_ctr":p.CTR=sigmoid(first(vals));case"watch_logits":p.WatchProbs=softmax(vals);case"p_completion":p.Completion=sigmoid(first(vals));case"p_pay":p.Pay=sigmoid(first(vals))}};if len(p.WatchProbs)==0{return Prediction{},fmt.Errorf("triton missing watch_logits")};return p,nil}
func first(v []float64)float64{if len(v)==0{return 0};return v[0]}
func sigmoid(x float64)float64{return 1/(1+math.Exp(-x))}
func softmax(v []float64)[]float64{if len(v)==0{return nil};m:=v[0];for _,x:=range v[1:]{if x>m{m=x}};sum:=0.0;out:=make([]float64,len(v));for i,x:=range v{out[i]=math.Exp(x-m);sum+=out[i]};for i:=range out{out[i]/=sum};return out}
