USE short_drama;

ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name VARCHAR(128) NOT NULL DEFAULT '';

UPDATE users SET email=NULL WHERE email='';

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON users(email);
