// Code generated by ent, DO NOT EDIT.

package genre

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the genre type in the database.
	Label = "genre"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDramas holds the string denoting the dramas edge name in mutations.
	EdgeDramas = "dramas"
	// EdgeDramaGenres holds the string denoting the drama_genres edge name in mutations.
	EdgeDramaGenres = "drama_genres"
	// Table holds the table name of the genre in the database.
	Table = "genres"
	// DramasTable is the table that holds the dramas relation/edge. The primary key declared below.
	DramasTable = "drama_genres"
	// DramasInverseTable is the table name for the Drama entity.
	// It exists in this package in order to avoid circular dependency with the "drama" package.
	DramasInverseTable = "dramas"
	// DramaGenresTable is the table that holds the drama_genres relation/edge.
	DramaGenresTable = "drama_genres"
	// DramaGenresInverseTable is the table name for the DramaGenre entity.
	// It exists in this package in order to avoid circular dependency with the "dramagenre" package.
	DramaGenresInverseTable = "drama_genres"
	// DramaGenresColumn is the table column denoting the drama_genres relation/edge.
	DramaGenresColumn = "genre_id"
)

// Columns holds all SQL columns for genre fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldLanguage,
	FieldCreatedAt,
}

var (
	// DramasPrimaryKey and DramasColumn2 are the table columns denoting the
	// primary key for the dramas relation (M2M).
	DramasPrimaryKey = []string{"drama_id", "genre_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the Genre queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByDramasCount orders the results by dramas count.
func ByDramasCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDramasStep(), opts...)
	}
}

// ByDramas orders the results by dramas terms.
func ByDramas(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDramasStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDramaGenresCount orders the results by drama_genres count.
func ByDramaGenresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDramaGenresStep(), opts...)
	}
}

// ByDramaGenres orders the results by drama_genres terms.
func ByDramaGenres(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDramaGenresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDramasStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DramasInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, DramasTable, DramasPrimaryKey...),
	)
}
func newDramaGenresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DramaGenresInverseTable, DramaGenresColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, DramaGenresTable, DramaGenresColumn),
	)
}
