// Code generated by ent, DO NOT EDIT.

package dramagenre

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dramagenre type in the database.
	Label = "drama_genre"
	// FieldDramaID holds the string denoting the drama_id field in the database.
	FieldDramaID = "drama_id"
	// FieldGenreID holds the string denoting the genre_id field in the database.
	FieldGenreID = "genre_id"
	// EdgeDrama holds the string denoting the drama edge name in mutations.
	EdgeDrama = "drama"
	// EdgeGenre holds the string denoting the genre edge name in mutations.
	EdgeGenre = "genre"
	// DramaFieldID holds the string denoting the ID field of the Drama.
	DramaFieldID = "id"
	// GenreFieldID holds the string denoting the ID field of the Genre.
	GenreFieldID = "id"
	// Table holds the table name of the dramagenre in the database.
	Table = "drama_genres"
	// DramaTable is the table that holds the drama relation/edge.
	DramaTable = "drama_genres"
	// DramaInverseTable is the table name for the Drama entity.
	// It exists in this package in order to avoid circular dependency with the "drama" package.
	DramaInverseTable = "dramas"
	// DramaColumn is the table column denoting the drama relation/edge.
	DramaColumn = "drama_id"
	// GenreTable is the table that holds the genre relation/edge.
	GenreTable = "drama_genres"
	// GenreInverseTable is the table name for the Genre entity.
	// It exists in this package in order to avoid circular dependency with the "genre" package.
	GenreInverseTable = "genres"
	// GenreColumn is the table column denoting the genre relation/edge.
	GenreColumn = "genre_id"
)

// Columns holds all SQL columns for dramagenre fields.
var Columns = []string{
	FieldDramaID,
	FieldGenreID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the DramaGenre queries.
type OrderOption func(*sql.Selector)

// ByDramaID orders the results by the drama_id field.
func ByDramaID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDramaID, opts...).ToFunc()
}

// ByGenreID orders the results by the genre_id field.
func ByGenreID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenreID, opts...).ToFunc()
}

// ByDramaField orders the results by drama field.
func ByDramaField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDramaStep(), sql.OrderByField(field, opts...))
	}
}

// ByGenreField orders the results by genre field.
func ByGenreField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGenreStep(), sql.OrderByField(field, opts...))
	}
}
func newDramaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, DramaColumn),
		sqlgraph.To(DramaInverseTable, DramaFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, DramaTable, DramaColumn),
	)
}
func newGenreStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, GenreColumn),
		sqlgraph.To(GenreInverseTable, GenreFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GenreTable, GenreColumn),
	)
}
