// Code generated by ent, DO NOT EDIT.

package dramagenre

import (
	"short-drama-recommend/rpc/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// DramaID applies equality check predicate on the "drama_id" field. It's identical to DramaIDEQ.
func DramaID(v uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldEQ(FieldDramaID, v))
}

// GenreID applies equality check predicate on the "genre_id" field. It's identical to GenreIDEQ.
func GenreID(v uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldEQ(FieldGenreID, v))
}

// DramaIDEQ applies the EQ predicate on the "drama_id" field.
func DramaIDEQ(v uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldEQ(FieldDramaID, v))
}

// DramaIDNEQ applies the NEQ predicate on the "drama_id" field.
func DramaIDNEQ(v uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldNEQ(FieldDramaID, v))
}

// DramaIDIn applies the In predicate on the "drama_id" field.
func DramaIDIn(vs ...uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldIn(FieldDramaID, vs...))
}

// DramaIDNotIn applies the NotIn predicate on the "drama_id" field.
func DramaIDNotIn(vs ...uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldNotIn(FieldDramaID, vs...))
}

// GenreIDEQ applies the EQ predicate on the "genre_id" field.
func GenreIDEQ(v uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldEQ(FieldGenreID, v))
}

// GenreIDNEQ applies the NEQ predicate on the "genre_id" field.
func GenreIDNEQ(v uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldNEQ(FieldGenreID, v))
}

// GenreIDIn applies the In predicate on the "genre_id" field.
func GenreIDIn(vs ...uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldIn(FieldGenreID, vs...))
}

// GenreIDNotIn applies the NotIn predicate on the "genre_id" field.
func GenreIDNotIn(vs ...uint64) predicate.DramaGenre {
	return predicate.DramaGenre(sql.FieldNotIn(FieldGenreID, vs...))
}

// HasDrama applies the HasEdge predicate on the "drama" edge.
func HasDrama() predicate.DramaGenre {
	return predicate.DramaGenre(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, DramaColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, DramaTable, DramaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDramaWith applies the HasEdge predicate on the "drama" edge with a given conditions (other predicates).
func HasDramaWith(preds ...predicate.Drama) predicate.DramaGenre {
	return predicate.DramaGenre(func(s *sql.Selector) {
		step := newDramaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGenre applies the HasEdge predicate on the "genre" edge.
func HasGenre() predicate.DramaGenre {
	return predicate.DramaGenre(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, GenreColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, GenreTable, GenreColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGenreWith applies the HasEdge predicate on the "genre" edge with a given conditions (other predicates).
func HasGenreWith(preds ...predicate.Genre) predicate.DramaGenre {
	return predicate.DramaGenre(func(s *sql.Selector) {
		step := newGenreStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DramaGenre) predicate.DramaGenre {
	return predicate.DramaGenre(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DramaGenre) predicate.DramaGenre {
	return predicate.DramaGenre(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DramaGenre) predicate.DramaGenre {
	return predicate.DramaGenre(sql.NotPredicates(p))
}
