// Code generated by ent, DO NOT EDIT.

package drama

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the drama type in the database.
	Label = "drama"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldSubtitle holds the string denoting the subtitle field in the database.
	FieldSubtitle = "subtitle"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldCover holds the string denoting the cover field in the database.
	FieldCover = "cover"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// FieldTotalEpisodes holds the string denoting the total_episodes field in the database.
	FieldTotalEpisodes = "total_episodes"
	// FieldIsPaid holds the string denoting the is_paid field in the database.
	FieldIsPaid = "is_paid"
	// FieldPriceCents holds the string denoting the price_cents field in the database.
	FieldPriceCents = "price_cents"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldPopularity holds the string denoting the popularity field in the database.
	FieldPopularity = "popularity"
	// FieldCompletionRate holds the string denoting the completion_rate field in the database.
	FieldCompletionRate = "completion_rate"
	// FieldPayRate holds the string denoting the pay_rate field in the database.
	FieldPayRate = "pay_rate"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeEpisodes holds the string denoting the episodes edge name in mutations.
	EdgeEpisodes = "episodes"
	// EdgeGenres holds the string denoting the genres edge name in mutations.
	EdgeGenres = "genres"
	// EdgeTags holds the string denoting the tags edge name in mutations.
	EdgeTags = "tags"
	// EdgeDramaGenres holds the string denoting the drama_genres edge name in mutations.
	EdgeDramaGenres = "drama_genres"
	// EdgeDramaTags holds the string denoting the drama_tags edge name in mutations.
	EdgeDramaTags = "drama_tags"
	// Table holds the table name of the drama in the database.
	Table = "dramas"
	// EpisodesTable is the table that holds the episodes relation/edge.
	EpisodesTable = "episodes"
	// EpisodesInverseTable is the table name for the Episode entity.
	// It exists in this package in order to avoid circular dependency with the "episode" package.
	EpisodesInverseTable = "episodes"
	// EpisodesColumn is the table column denoting the episodes relation/edge.
	EpisodesColumn = "drama_id"
	// GenresTable is the table that holds the genres relation/edge. The primary key declared below.
	GenresTable = "drama_genres"
	// GenresInverseTable is the table name for the Genre entity.
	// It exists in this package in order to avoid circular dependency with the "genre" package.
	GenresInverseTable = "genres"
	// TagsTable is the table that holds the tags relation/edge. The primary key declared below.
	TagsTable = "drama_tags"
	// TagsInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagsInverseTable = "tags"
	// DramaGenresTable is the table that holds the drama_genres relation/edge.
	DramaGenresTable = "drama_genres"
	// DramaGenresInverseTable is the table name for the DramaGenre entity.
	// It exists in this package in order to avoid circular dependency with the "dramagenre" package.
	DramaGenresInverseTable = "drama_genres"
	// DramaGenresColumn is the table column denoting the drama_genres relation/edge.
	DramaGenresColumn = "drama_id"
	// DramaTagsTable is the table that holds the drama_tags relation/edge.
	DramaTagsTable = "drama_tags"
	// DramaTagsInverseTable is the table name for the DramaTag entity.
	// It exists in this package in order to avoid circular dependency with the "dramatag" package.
	DramaTagsInverseTable = "drama_tags"
	// DramaTagsColumn is the table column denoting the drama_tags relation/edge.
	DramaTagsColumn = "drama_id"
)

// Columns holds all SQL columns for drama fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldSubtitle,
	FieldDescription,
	FieldCover,
	FieldCountry,
	FieldLanguage,
	FieldTotalEpisodes,
	FieldIsPaid,
	FieldPriceCents,
	FieldCurrency,
	FieldStatus,
	FieldPopularity,
	FieldCompletionRate,
	FieldPayRate,
	FieldPublishedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

var (
	// GenresPrimaryKey and GenresColumn2 are the table columns denoting the
	// primary key for the genres relation (M2M).
	GenresPrimaryKey = []string{"drama_id", "genre_id"}
	// TagsPrimaryKey and TagsColumn2 are the table columns denoting the
	// primary key for the tags relation (M2M).
	TagsPrimaryKey = []string{"drama_id", "tag_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSubtitle holds the default value on creation for the "subtitle" field.
	DefaultSubtitle string
	// DefaultCover holds the default value on creation for the "cover" field.
	DefaultCover string
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
	// DefaultTotalEpisodes holds the default value on creation for the "total_episodes" field.
	DefaultTotalEpisodes uint32
	// DefaultIsPaid holds the default value on creation for the "is_paid" field.
	DefaultIsPaid bool
	// DefaultPriceCents holds the default value on creation for the "price_cents" field.
	DefaultPriceCents uint64
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
	// DefaultPopularity holds the default value on creation for the "popularity" field.
	DefaultPopularity float64
	// DefaultCompletionRate holds the default value on creation for the "completion_rate" field.
	DefaultCompletionRate float64
	// DefaultPayRate holds the default value on creation for the "pay_rate" field.
	DefaultPayRate float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Drama queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// BySubtitle orders the results by the subtitle field.
func BySubtitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubtitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByCover orders the results by the cover field.
func ByCover(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCover, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByLanguage orders the results by the language field.
func ByLanguage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLanguage, opts...).ToFunc()
}

// ByTotalEpisodes orders the results by the total_episodes field.
func ByTotalEpisodes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalEpisodes, opts...).ToFunc()
}

// ByIsPaid orders the results by the is_paid field.
func ByIsPaid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPaid, opts...).ToFunc()
}

// ByPriceCents orders the results by the price_cents field.
func ByPriceCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceCents, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPopularity orders the results by the popularity field.
func ByPopularity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPopularity, opts...).ToFunc()
}

// ByCompletionRate orders the results by the completion_rate field.
func ByCompletionRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompletionRate, opts...).ToFunc()
}

// ByPayRate orders the results by the pay_rate field.
func ByPayRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayRate, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEpisodesCount orders the results by episodes count.
func ByEpisodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEpisodesStep(), opts...)
	}
}

// ByEpisodes orders the results by episodes terms.
func ByEpisodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEpisodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByGenresCount orders the results by genres count.
func ByGenresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newGenresStep(), opts...)
	}
}

// ByGenres orders the results by genres terms.
func ByGenres(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGenresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTagsCount orders the results by tags count.
func ByTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTagsStep(), opts...)
	}
}

// ByTags orders the results by tags terms.
func ByTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDramaGenresCount orders the results by drama_genres count.
func ByDramaGenresCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDramaGenresStep(), opts...)
	}
}

// ByDramaGenres orders the results by drama_genres terms.
func ByDramaGenres(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDramaGenresStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDramaTagsCount orders the results by drama_tags count.
func ByDramaTagsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDramaTagsStep(), opts...)
	}
}

// ByDramaTags orders the results by drama_tags terms.
func ByDramaTags(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDramaTagsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newEpisodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EpisodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EpisodesTable, EpisodesColumn),
	)
}
func newGenresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GenresInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, GenresTable, GenresPrimaryKey...),
	)
}
func newTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TagsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
	)
}
func newDramaGenresStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DramaGenresInverseTable, DramaGenresColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, DramaGenresTable, DramaGenresColumn),
	)
}
func newDramaTagsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DramaTagsInverseTable, DramaTagsColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, DramaTagsTable, DramaTagsColumn),
	)
}
