// Code generated by ent, DO NOT EDIT.

package drama

import (
	"short-drama-recommend/rpc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldTitle, v))
}

// Subtitle applies equality check predicate on the "subtitle" field. It's identical to SubtitleEQ.
func Subtitle(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldSubtitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldDescription, v))
}

// Cover applies equality check predicate on the "cover" field. It's identical to CoverEQ.
func Cover(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCover, v))
}

// Country applies equality check predicate on the "country" field. It's identical to CountryEQ.
func Country(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCountry, v))
}

// Language applies equality check predicate on the "language" field. It's identical to LanguageEQ.
func Language(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldLanguage, v))
}

// TotalEpisodes applies equality check predicate on the "total_episodes" field. It's identical to TotalEpisodesEQ.
func TotalEpisodes(v uint32) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldTotalEpisodes, v))
}

// IsPaid applies equality check predicate on the "is_paid" field. It's identical to IsPaidEQ.
func IsPaid(v bool) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldIsPaid, v))
}

// PriceCents applies equality check predicate on the "price_cents" field. It's identical to PriceCentsEQ.
func PriceCents(v uint64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldPriceCents, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCurrency, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldStatus, v))
}

// Popularity applies equality check predicate on the "popularity" field. It's identical to PopularityEQ.
func Popularity(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldPopularity, v))
}

// CompletionRate applies equality check predicate on the "completion_rate" field. It's identical to CompletionRateEQ.
func CompletionRate(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCompletionRate, v))
}

// PayRate applies equality check predicate on the "pay_rate" field. It's identical to PayRateEQ.
func PayRate(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldPayRate, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldPublishedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContainsFold(FieldTitle, v))
}

// SubtitleEQ applies the EQ predicate on the "subtitle" field.
func SubtitleEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldSubtitle, v))
}

// SubtitleNEQ applies the NEQ predicate on the "subtitle" field.
func SubtitleNEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldSubtitle, v))
}

// SubtitleIn applies the In predicate on the "subtitle" field.
func SubtitleIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldSubtitle, vs...))
}

// SubtitleNotIn applies the NotIn predicate on the "subtitle" field.
func SubtitleNotIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldSubtitle, vs...))
}

// SubtitleGT applies the GT predicate on the "subtitle" field.
func SubtitleGT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldSubtitle, v))
}

// SubtitleGTE applies the GTE predicate on the "subtitle" field.
func SubtitleGTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldSubtitle, v))
}

// SubtitleLT applies the LT predicate on the "subtitle" field.
func SubtitleLT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldSubtitle, v))
}

// SubtitleLTE applies the LTE predicate on the "subtitle" field.
func SubtitleLTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldSubtitle, v))
}

// SubtitleContains applies the Contains predicate on the "subtitle" field.
func SubtitleContains(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContains(FieldSubtitle, v))
}

// SubtitleHasPrefix applies the HasPrefix predicate on the "subtitle" field.
func SubtitleHasPrefix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasPrefix(FieldSubtitle, v))
}

// SubtitleHasSuffix applies the HasSuffix predicate on the "subtitle" field.
func SubtitleHasSuffix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasSuffix(FieldSubtitle, v))
}

// SubtitleEqualFold applies the EqualFold predicate on the "subtitle" field.
func SubtitleEqualFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEqualFold(FieldSubtitle, v))
}

// SubtitleContainsFold applies the ContainsFold predicate on the "subtitle" field.
func SubtitleContainsFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContainsFold(FieldSubtitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContainsFold(FieldDescription, v))
}

// CoverEQ applies the EQ predicate on the "cover" field.
func CoverEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCover, v))
}

// CoverNEQ applies the NEQ predicate on the "cover" field.
func CoverNEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldCover, v))
}

// CoverIn applies the In predicate on the "cover" field.
func CoverIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldCover, vs...))
}

// CoverNotIn applies the NotIn predicate on the "cover" field.
func CoverNotIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldCover, vs...))
}

// CoverGT applies the GT predicate on the "cover" field.
func CoverGT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldCover, v))
}

// CoverGTE applies the GTE predicate on the "cover" field.
func CoverGTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldCover, v))
}

// CoverLT applies the LT predicate on the "cover" field.
func CoverLT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldCover, v))
}

// CoverLTE applies the LTE predicate on the "cover" field.
func CoverLTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldCover, v))
}

// CoverContains applies the Contains predicate on the "cover" field.
func CoverContains(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContains(FieldCover, v))
}

// CoverHasPrefix applies the HasPrefix predicate on the "cover" field.
func CoverHasPrefix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasPrefix(FieldCover, v))
}

// CoverHasSuffix applies the HasSuffix predicate on the "cover" field.
func CoverHasSuffix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasSuffix(FieldCover, v))
}

// CoverEqualFold applies the EqualFold predicate on the "cover" field.
func CoverEqualFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEqualFold(FieldCover, v))
}

// CoverContainsFold applies the ContainsFold predicate on the "cover" field.
func CoverContainsFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContainsFold(FieldCover, v))
}

// CountryEQ applies the EQ predicate on the "country" field.
func CountryEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCountry, v))
}

// CountryNEQ applies the NEQ predicate on the "country" field.
func CountryNEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldCountry, v))
}

// CountryIn applies the In predicate on the "country" field.
func CountryIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldCountry, vs...))
}

// CountryNotIn applies the NotIn predicate on the "country" field.
func CountryNotIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldCountry, vs...))
}

// CountryGT applies the GT predicate on the "country" field.
func CountryGT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldCountry, v))
}

// CountryGTE applies the GTE predicate on the "country" field.
func CountryGTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldCountry, v))
}

// CountryLT applies the LT predicate on the "country" field.
func CountryLT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldCountry, v))
}

// CountryLTE applies the LTE predicate on the "country" field.
func CountryLTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldCountry, v))
}

// CountryContains applies the Contains predicate on the "country" field.
func CountryContains(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContains(FieldCountry, v))
}

// CountryHasPrefix applies the HasPrefix predicate on the "country" field.
func CountryHasPrefix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasPrefix(FieldCountry, v))
}

// CountryHasSuffix applies the HasSuffix predicate on the "country" field.
func CountryHasSuffix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasSuffix(FieldCountry, v))
}

// CountryEqualFold applies the EqualFold predicate on the "country" field.
func CountryEqualFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEqualFold(FieldCountry, v))
}

// CountryContainsFold applies the ContainsFold predicate on the "country" field.
func CountryContainsFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContainsFold(FieldCountry, v))
}

// LanguageEQ applies the EQ predicate on the "language" field.
func LanguageEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldLanguage, v))
}

// LanguageNEQ applies the NEQ predicate on the "language" field.
func LanguageNEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldLanguage, v))
}

// LanguageIn applies the In predicate on the "language" field.
func LanguageIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldLanguage, vs...))
}

// LanguageNotIn applies the NotIn predicate on the "language" field.
func LanguageNotIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldLanguage, vs...))
}

// LanguageGT applies the GT predicate on the "language" field.
func LanguageGT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldLanguage, v))
}

// LanguageGTE applies the GTE predicate on the "language" field.
func LanguageGTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldLanguage, v))
}

// LanguageLT applies the LT predicate on the "language" field.
func LanguageLT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldLanguage, v))
}

// LanguageLTE applies the LTE predicate on the "language" field.
func LanguageLTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldLanguage, v))
}

// LanguageContains applies the Contains predicate on the "language" field.
func LanguageContains(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContains(FieldLanguage, v))
}

// LanguageHasPrefix applies the HasPrefix predicate on the "language" field.
func LanguageHasPrefix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasPrefix(FieldLanguage, v))
}

// LanguageHasSuffix applies the HasSuffix predicate on the "language" field.
func LanguageHasSuffix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasSuffix(FieldLanguage, v))
}

// LanguageEqualFold applies the EqualFold predicate on the "language" field.
func LanguageEqualFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEqualFold(FieldLanguage, v))
}

// LanguageContainsFold applies the ContainsFold predicate on the "language" field.
func LanguageContainsFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContainsFold(FieldLanguage, v))
}

// TotalEpisodesEQ applies the EQ predicate on the "total_episodes" field.
func TotalEpisodesEQ(v uint32) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldTotalEpisodes, v))
}

// TotalEpisodesNEQ applies the NEQ predicate on the "total_episodes" field.
func TotalEpisodesNEQ(v uint32) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldTotalEpisodes, v))
}

// TotalEpisodesIn applies the In predicate on the "total_episodes" field.
func TotalEpisodesIn(vs ...uint32) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldTotalEpisodes, vs...))
}

// TotalEpisodesNotIn applies the NotIn predicate on the "total_episodes" field.
func TotalEpisodesNotIn(vs ...uint32) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldTotalEpisodes, vs...))
}

// TotalEpisodesGT applies the GT predicate on the "total_episodes" field.
func TotalEpisodesGT(v uint32) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldTotalEpisodes, v))
}

// TotalEpisodesGTE applies the GTE predicate on the "total_episodes" field.
func TotalEpisodesGTE(v uint32) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldTotalEpisodes, v))
}

// TotalEpisodesLT applies the LT predicate on the "total_episodes" field.
func TotalEpisodesLT(v uint32) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldTotalEpisodes, v))
}

// TotalEpisodesLTE applies the LTE predicate on the "total_episodes" field.
func TotalEpisodesLTE(v uint32) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldTotalEpisodes, v))
}

// IsPaidEQ applies the EQ predicate on the "is_paid" field.
func IsPaidEQ(v bool) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldIsPaid, v))
}

// IsPaidNEQ applies the NEQ predicate on the "is_paid" field.
func IsPaidNEQ(v bool) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldIsPaid, v))
}

// PriceCentsEQ applies the EQ predicate on the "price_cents" field.
func PriceCentsEQ(v uint64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldPriceCents, v))
}

// PriceCentsNEQ applies the NEQ predicate on the "price_cents" field.
func PriceCentsNEQ(v uint64) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldPriceCents, v))
}

// PriceCentsIn applies the In predicate on the "price_cents" field.
func PriceCentsIn(vs ...uint64) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldPriceCents, vs...))
}

// PriceCentsNotIn applies the NotIn predicate on the "price_cents" field.
func PriceCentsNotIn(vs ...uint64) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldPriceCents, vs...))
}

// PriceCentsGT applies the GT predicate on the "price_cents" field.
func PriceCentsGT(v uint64) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldPriceCents, v))
}

// PriceCentsGTE applies the GTE predicate on the "price_cents" field.
func PriceCentsGTE(v uint64) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldPriceCents, v))
}

// PriceCentsLT applies the LT predicate on the "price_cents" field.
func PriceCentsLT(v uint64) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldPriceCents, v))
}

// PriceCentsLTE applies the LTE predicate on the "price_cents" field.
func PriceCentsLTE(v uint64) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldPriceCents, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.Drama {
	return predicate.Drama(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.Drama {
	return predicate.Drama(sql.FieldContainsFold(FieldCurrency, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldStatus, v))
}

// PopularityEQ applies the EQ predicate on the "popularity" field.
func PopularityEQ(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldPopularity, v))
}

// PopularityNEQ applies the NEQ predicate on the "popularity" field.
func PopularityNEQ(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldPopularity, v))
}

// PopularityIn applies the In predicate on the "popularity" field.
func PopularityIn(vs ...float64) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldPopularity, vs...))
}

// PopularityNotIn applies the NotIn predicate on the "popularity" field.
func PopularityNotIn(vs ...float64) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldPopularity, vs...))
}

// PopularityGT applies the GT predicate on the "popularity" field.
func PopularityGT(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldPopularity, v))
}

// PopularityGTE applies the GTE predicate on the "popularity" field.
func PopularityGTE(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldPopularity, v))
}

// PopularityLT applies the LT predicate on the "popularity" field.
func PopularityLT(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldPopularity, v))
}

// PopularityLTE applies the LTE predicate on the "popularity" field.
func PopularityLTE(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldPopularity, v))
}

// CompletionRateEQ applies the EQ predicate on the "completion_rate" field.
func CompletionRateEQ(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCompletionRate, v))
}

// CompletionRateNEQ applies the NEQ predicate on the "completion_rate" field.
func CompletionRateNEQ(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldCompletionRate, v))
}

// CompletionRateIn applies the In predicate on the "completion_rate" field.
func CompletionRateIn(vs ...float64) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldCompletionRate, vs...))
}

// CompletionRateNotIn applies the NotIn predicate on the "completion_rate" field.
func CompletionRateNotIn(vs ...float64) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldCompletionRate, vs...))
}

// CompletionRateGT applies the GT predicate on the "completion_rate" field.
func CompletionRateGT(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldCompletionRate, v))
}

// CompletionRateGTE applies the GTE predicate on the "completion_rate" field.
func CompletionRateGTE(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldCompletionRate, v))
}

// CompletionRateLT applies the LT predicate on the "completion_rate" field.
func CompletionRateLT(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldCompletionRate, v))
}

// CompletionRateLTE applies the LTE predicate on the "completion_rate" field.
func CompletionRateLTE(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldCompletionRate, v))
}

// PayRateEQ applies the EQ predicate on the "pay_rate" field.
func PayRateEQ(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldPayRate, v))
}

// PayRateNEQ applies the NEQ predicate on the "pay_rate" field.
func PayRateNEQ(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldPayRate, v))
}

// PayRateIn applies the In predicate on the "pay_rate" field.
func PayRateIn(vs ...float64) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldPayRate, vs...))
}

// PayRateNotIn applies the NotIn predicate on the "pay_rate" field.
func PayRateNotIn(vs ...float64) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldPayRate, vs...))
}

// PayRateGT applies the GT predicate on the "pay_rate" field.
func PayRateGT(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldPayRate, v))
}

// PayRateGTE applies the GTE predicate on the "pay_rate" field.
func PayRateGTE(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldPayRate, v))
}

// PayRateLT applies the LT predicate on the "pay_rate" field.
func PayRateLT(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldPayRate, v))
}

// PayRateLTE applies the LTE predicate on the "pay_rate" field.
func PayRateLTE(v float64) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldPayRate, v))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.Drama {
	return predicate.Drama(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.Drama {
	return predicate.Drama(sql.FieldNotNull(FieldPublishedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Drama {
	return predicate.Drama(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasEpisodes applies the HasEdge predicate on the "episodes" edge.
func HasEpisodes() predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EpisodesTable, EpisodesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEpisodesWith applies the HasEdge predicate on the "episodes" edge with a given conditions (other predicates).
func HasEpisodesWith(preds ...predicate.Episode) predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := newEpisodesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGenres applies the HasEdge predicate on the "genres" edge.
func HasGenres() predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, GenresTable, GenresPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGenresWith applies the HasEdge predicate on the "genres" edge with a given conditions (other predicates).
func HasGenresWith(preds ...predicate.Genre) predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := newGenresStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTags applies the HasEdge predicate on the "tags" edge.
func HasTags() predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, TagsTable, TagsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTagsWith applies the HasEdge predicate on the "tags" edge with a given conditions (other predicates).
func HasTagsWith(preds ...predicate.Tag) predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := newTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDramaGenres applies the HasEdge predicate on the "drama_genres" edge.
func HasDramaGenres() predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, DramaGenresTable, DramaGenresColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDramaGenresWith applies the HasEdge predicate on the "drama_genres" edge with a given conditions (other predicates).
func HasDramaGenresWith(preds ...predicate.DramaGenre) predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := newDramaGenresStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDramaTags applies the HasEdge predicate on the "drama_tags" edge.
func HasDramaTags() predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, DramaTagsTable, DramaTagsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDramaTagsWith applies the HasEdge predicate on the "drama_tags" edge with a given conditions (other predicates).
func HasDramaTagsWith(preds ...predicate.DramaTag) predicate.Drama {
	return predicate.Drama(func(s *sql.Selector) {
		step := newDramaTagsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Drama) predicate.Drama {
	return predicate.Drama(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Drama) predicate.Drama {
	return predicate.Drama(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Drama) predicate.Drama {
	return predicate.Drama(sql.NotPredicates(p))
}
