// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: media.proto

package mediaservice

import (
	"context"

	"short-drama-recommend/rpc/media-rpc/pb/short-drama-recommend/rpc/media-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CompleteUploadRequest = pb.CompleteUploadRequest
	CreateUploadRequest   = pb.CreateUploadRequest
	CreateUploadResponse  = pb.CreateUploadResponse
	GetPlaybackRequest    = pb.GetPlaybackRequest
	MediaAsset            = pb.MediaAsset
	PlaybackResponse      = pb.PlaybackResponse

	MediaService interface {
		CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error)
		CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*MediaAsset, error)
		GetPlayback(ctx context.Context, in *GetPlaybackRequest, opts ...grpc.CallOption) (*PlaybackResponse, error)
	}

	defaultMediaService struct {
		cli zrpc.Client
	}
)

func NewMediaService(cli zrpc.Client) MediaService {
	return &defaultMediaService{
		cli: cli,
	}
}

func (m *defaultMediaService) CreateUpload(ctx context.Context, in *CreateUploadRequest, opts ...grpc.CallOption) (*CreateUploadResponse, error) {
	client := pb.NewMediaServiceClient(m.cli.Conn())
	return client.CreateUpload(ctx, in, opts...)
}

func (m *defaultMediaService) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*MediaAsset, error) {
	client := pb.NewMediaServiceClient(m.cli.Conn())
	return client.CompleteUpload(ctx, in, opts...)
}

func (m *defaultMediaService) GetPlayback(ctx context.Context, in *GetPlaybackRequest, opts ...grpc.CallOption) (*PlaybackResponse, error) {
	client := pb.NewMediaServiceClient(m.cli.Conn())
	return client.GetPlayback(ctx, in, opts...)
}
