<script setup lang="ts">
import {reactive,ref,onMounted} from 'vue'
import {ElMessage} from 'element-plus'
import {request} from '../../api/client'
const tab=ref('payment'),loading=ref(false)
const form=reactive<any>({payment:{stripe_enabled:true,stripe_publishable_key:'',stripe_secret_key:'',stripe_webhook_secret:'',paypal_enabled:true,paypal_env:'sandbox',paypal_client_id:'',paypal_client_secret:'',paypal_webhook_id:''},storage:{default_provider:'OSS',oss_enabled:false,oss_endpoint:'',oss_region:'',oss_bucket:'',oss_access_key:'',oss_secret_key:'',s3_enabled:false,s3_region:'',s3_bucket:'',s3_endpoint:'',s3_access_key:'',s3_secret_key:'',cdn_base_url:''}})
async function load(){loading.value=true;try{const [p,s]=await Promise.all([request('/api/v1/admin/settings/payment'),request('/api/v1/admin/settings/storage')]);Object.assign(form.payment,p);Object.assign(form.storage,s)}catch(e:any){ElMessage.error(e.message)}finally{loading.value=false}}
async function save(group:string){try{await request('/api/v1/admin/settings/'+group,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(form[group])});ElMessage.success('保存成功')}catch(e:any){ElMessage.error(e.message)}}
async function test(group:string,provider:string){try{const r=await request('/api/v1/admin/settings/'+group+'/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider})});ElMessage.success(r.message||'测试通过')}catch(e:any){ElMessage.error(e.message)}}
onMounted(load)
</script>
<template><div class="settings" v-loading="loading"><h2>系统设置</h2><el-tabs v-model="tab">
<el-tab-pane label="支付设置" name="payment">
<el-card><template #header>Stripe</template><el-form label-width="150px"><el-form-item label="启用"><el-switch v-model="form.payment.stripe_enabled"/></el-form-item><el-form-item label="Publishable Key"><el-input v-model="form.payment.stripe_publishable_key"/></el-form-item><el-form-item label="Secret Key"><el-input v-model="form.payment.stripe_secret_key" show-password placeholder="留空保持原值"/></el-form-item><el-form-item label="Webhook Secret"><el-input v-model="form.payment.stripe_webhook_secret" show-password placeholder="留空保持原值"/></el-form-item><el-button type="primary" @click="save('payment')">保存支付配置</el-button><el-button @click="test('payment','stripe')">测试 Stripe</el-button></el-form></el-card>
<el-card style="margin-top:16px"><template #header>PayPal</template><el-form label-width="150px"><el-form-item label="启用"><el-switch v-model="form.payment.paypal_enabled"/></el-form-item><el-form-item label="环境"><el-select v-model="form.payment.paypal_env"><el-option label="Sandbox" value="sandbox"/><el-option label="Live" value="live"/></el-select></el-form-item><el-form-item label="Client ID"><el-input v-model="form.payment.paypal_client_id"/></el-form-item><el-form-item label="Client Secret"><el-input v-model="form.payment.paypal_client_secret" show-password placeholder="留空保持原值"/></el-form-item><el-form-item label="Webhook ID"><el-input v-model="form.payment.paypal_webhook_id"/></el-form-item><el-button type="primary" @click="save('payment')">保存 PayPal</el-button><el-button @click="test('payment','paypal')">测试 PayPal</el-button></el-form></el-card></el-tab-pane>
<el-tab-pane label="存储设置" name="storage">
<el-card><template #header>默认视频存储</template><el-form label-width="150px"><el-form-item label="默认 Provider"><el-select v-model="form.storage.default_provider"><el-option label="Aliyun OSS" value="OSS"/><el-option label="AWS S3" value="S3"/></el-select></el-form-item></el-form></el-card>
<el-card style="margin-top:16px"><template #header>Aliyun OSS</template><el-form label-width="150px"><el-form-item label="启用"><el-switch v-model="form.storage.oss_enabled"/></el-form-item><el-form-item label="Endpoint"><el-input v-model="form.storage.oss_endpoint"/></el-form-item><el-form-item label="Region"><el-input v-model="form.storage.oss_region"/></el-form-item><el-form-item label="Bucket"><el-input v-model="form.storage.oss_bucket"/></el-form-item><el-form-item label="AccessKey"><el-input v-model="form.storage.oss_access_key"/></el-form-item><el-form-item label="SecretKey"><el-input v-model="form.storage.oss_secret_key" show-password placeholder="留空保持原值"/></el-form-item></el-form></el-card>
<el-card style="margin-top:16px"><template #header>AWS S3</template><el-form label-width="150px"><el-form-item label="启用"><el-switch v-model="form.storage.s3_enabled"/></el-form-item><el-form-item label="Region"><el-input v-model="form.storage.s3_region"/></el-form-item><el-form-item label="Bucket"><el-input v-model="form.storage.s3_bucket"/></el-form-item><el-form-item label="Endpoint"><el-input v-model="form.storage.s3_endpoint"/></el-form-item><el-form-item label="Access Key"><el-input v-model="form.storage.s3_access_key"/></el-form-item><el-form-item label="Secret Key"><el-input v-model="form.storage.s3_secret_key" show-password placeholder="留空保持原值"/></el-form-item><el-form-item label="CDN Base URL"><el-input v-model="form.storage.cdn_base_url"/></el-form-item><el-button type="primary" @click="save('storage')">保存存储配置</el-button><el-button @click="test('storage','oss')">测试 OSS 参数</el-button><el-button @click="test('storage','s3')">测试 S3 参数</el-button></el-form></el-card></el-tab-pane>
</el-tabs></div></template>
