<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
const API='http://127.0.0.1:8081'
const page=ref('dashboard'), loggedIn=ref(false), loading=ref(false), items=ref<any[]>([])
const loginForm=ref({username:'admin',password:''})
const form=ref({title:'',description:'',cover:'',country:'US',language:'en',total_episodes:1,is_paid:false,price_cents:499,currency:'USD'})
const selectedDramaId=ref<number|null>(null), episodeList=ref<any[]>([])
const episodeForm=ref({episode_no:1,title:'Episode 1',duration_seconds:90,video_url:'https://example.com/video.m3u8',poster_url:'',is_paid:false})
const menu=[{key:'dashboard',label:'数据概览'},{key:'dramas',label:'短剧管理'},{key:'publish',label:'短剧发布'},{key:'episodes',label:'剧集管理'},{key:'orders',label:'订单 / 支付'},{key:'users',label:'用户管理'}]
async function load(){loading.value=true;try{const r=await fetch(API+'/api/v1/admin/dramas?page=1&page_size=100');if(!r.ok)throw Error('加载失败');const j=await r.json();items.value=j.items||[]}catch(e:any){ElMessage.error(e.message)}finally{loading.value=false}}
async function login(){if(!loginForm.value.username||!loginForm.value.password){ElMessage.warning('请输入账号和密码');return}loggedIn.value=true;await load();ElMessage.success('进入后台')}
async function create(){if(!form.value.title.trim()){ElMessage.warning('请输入短剧标题');return}try{const r=await fetch(API+'/api/v1/admin/dramas',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form.value)});if(!r.ok)throw Error('创建失败');ElMessage.success('创建成功');page.value='dramas';await load()}catch(e:any){ElMessage.error(e.message)}}
async function loadEpisodes(id:number){selectedDramaId.value=id;try{const r=await fetch(API+'/api/v1/admin/dramas/'+id+'/episodes?status=1');const j=await r.json();episodeList.value=j.items||[]}catch(e:any){ElMessage.error(e.message)}}
async function createEpisode(){if(!selectedDramaId.value){ElMessage.warning('先选择短剧');return}try{const r=await fetch(API+'/api/v1/admin/dramas/'+selectedDramaId.value+'/episodes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(episodeForm.value)});if(!r.ok)throw Error('剧集创建失败');ElMessage.success('剧集已保存');await loadEpisodes(selectedDramaId.value)}catch(e:any){ElMessage.error(e.message)}}
async function toggle(x:any){const status=x.status===1?2:1;const r=await fetch(API+'/api/v1/admin/dramas/'+x.id+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});if(r.ok){ElMessage.success(status===1?'已发布':'已下架');await load()}else ElMessage.error('状态更新失败')}
async function edit(x:any){try{const v=await ElMessageBox.prompt('请输入新的标题','编辑短剧',{inputValue:x.title,confirmButtonText:'保存'});if(v.value)await fetch(API+'/api/v1/admin/dramas/'+x.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...x,title:v.value})});await load()}catch{}}
const published=computed(()=>items.value.filter(x=>x.status===1).length)
const paid=computed(()=>items.value.filter(x=>x.is_paid).length)
onMounted(()=>{if(loggedIn.value)load()})
</script>
<template>
<div v-if="loggedIn" class="admin-shell">
 <header class="topbar"><div><div class="brand">SHORT<span>DRAMA</span></div><small>Global Short Drama Operations</small></div><div class="top-actions"><span>管理员：{{loginForm.username}}</span><el-button text @click="loggedIn=false">退出</el-button></div></header>
 <div class="body">
  <aside><div class="menu-title">运营中心</div><el-menu :default-active="page" @select="page=$event"><el-menu-item v-for="m in menu" :key="m.key" :index="m.key">{{m.label}}</el-menu-item></el-menu></aside>
  <main class="main">
   <section v-if="page==='dashboard'"><div class="title"><p>OVERVIEW</p><h1>数据概览</h1><span>海外短剧运营核心指标</span></div><div class="stats"><el-card><small>短剧总数</small><strong>{{items.length}}</strong></el-card><el-card><small>已发布</small><strong>{{published}}</strong></el-card><el-card><small>付费剧</small><strong>{{paid}}</strong></el-card><el-card><small>待处理订单</small><strong>—</strong></el-card></div><el-card class="panel"><template #header>最近短剧</template><el-table :data="items.slice(0,8)"><el-table-column prop="id" label="ID" width="80"/><el-table-column prop="title" label="标题"/><el-table-column prop="country" label="国家"/><el-table-column prop="language" label="语言"/><el-table-column prop="status" label="状态"/></el-table></el-card></section>

   <section v-else-if="page==='dramas'"><div class="title"><p>CONTENT</p><h1>短剧管理</h1><span>发布、下架、编辑短剧</span></div><el-card><template #header><div class="head">短剧列表 <el-button type="primary" @click="page='publish'">+ 发布短剧</el-button></div></template><el-table :data="items" stripe><el-table-column prop="id" label="ID" width="70"/><el-table-column prop="title" label="标题" min-width="220"/><el-table-column prop="country" label="国家"/><el-table-column prop="language" label="语言"/><el-table-column label="价格"><template #default="{row}">{{row.is_paid?'付费':'免费'}}</template></el-table-column><el-table-column prop="status" label="状态"/><el-table-column label="操作" width="180"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link @click="toggle(row)">{{row.status===1?'下架':'发布'}}</el-button></template></el-table-column></el-table></el-card></section>

   <section v-else-if="page==='publish'"><div class="title"><p>CONTENT / CREATE</p><h1>发布短剧</h1><span>创建草稿后在短剧管理中发布</span></div><el-card><el-form label-width="110px" class="form"><el-form-item label="标题"><el-input v-model="form.title" placeholder="The Contract Wife"/></el-form-item><el-form-item label="简介"><el-input v-model="form.description" type="textarea"/></el-form-item><el-form-item label="封面 URL"><el-input v-model="form.cover" placeholder="CDN URL"/></el-form-item><el-form-item label="国家"><el-input v-model="form.country"/></el-form-item><el-form-item label="语言"><el-input v-model="form.language"/></el-form-item><el-form-item label="总集数"><el-input-number v-model="form.total_episodes" :min="1"/></el-form-item><el-form-item label="付费"><el-switch v-model="form.is_paid"/></el-form-item><el-form-item v-if="form.is_paid" label="价格"><el-input-number v-model="form.price_cents" :min="1"/><span class="hint">分</span></el-form-item><el-form-item v-if="form.is_paid" label="币种"><el-input v-model="form.currency"/></el-form-item><el-button type="primary" size="large" @click="create">创建短剧</el-button></el-form></el-card></section>

   <section v-else-if="page==='episodes'"><div class="title"><p>CONTENT / EPISODES</p><h1>剧集管理</h1><span>真实连接 Episode API</span></div><el-card><template #header>选择短剧</template><el-select placeholder="选择短剧" @change="loadEpisodes" style="width:420px"><el-option v-for="x in items" :key="x.id" :label="x.title" :value="x.id"/></el-select></el-card><el-card v-if="selectedDramaId" class="panel"><template #header>新增 / 更新剧集</template><el-form label-width="110px"><el-form-item label="集数"><el-input-number v-model="episodeForm.episode_no" :min="1"/></el-form-item><el-form-item label="标题"><el-input v-model="episodeForm.title"/></el-form-item><el-form-item label="时长"><el-input-number v-model="episodeForm.duration_seconds" :min="0"/></el-form-item><el-form-item label="视频 URL"><el-input v-model="episodeForm.video_url"/></el-form-item><el-form-item label="海报 URL"><el-input v-model="episodeForm.poster_url"/></el-form-item><el-form-item label="付费"><el-switch v-model="episodeForm.is_paid"/></el-form-item><el-button type="primary" @click="createEpisode">保存剧集</el-button><el-divider/><el-table :data="episodeList"><el-table-column prop="episode_no" label="集数"/><el-table-column prop="title" label="标题"/><el-table-column prop="duration_seconds" label="时长"/><el-table-column prop="video_url" label="视频地址"/></el-table></el-card></section>
   <section v-else-if="page==='orders'"><div class="title"><p>COMMERCE</p><h1>订单 / 支付</h1><span>Stripe 与 PayPal 订单中心</span></div><div class="payment-cards"><el-card><h3>Stripe</h3><p>PaymentIntent / Webhook</p><el-tag>已接后端 RPC</el-tag></el-card><el-card><h3>PayPal</h3><p>Orders v2 / Capture / Webhook</p><el-tag>Sandbox / Live</el-tag></el-card></div><el-card class="panel"><el-empty description="订单列表 API 下一步接入；支付服务已独立为 payment-rpc:9005。"/></el-card></section>
   <section v-else><div class="title"><p>USERS</p><h1>用户管理</h1><span>国家、语言、时区与观看画像</span></div><el-card><el-empty description="用户列表与画像 API 下一步接入。"/></el-card></section>
  </main>
 </div>
</div>
<div v-else class="login-page"><el-card class="login-card"><div class="brand">SHORT<span>DRAMA</span></div><h1>运营管理后台</h1><p>Global short drama console</p><el-form @submit.prevent="login"><el-form-item><el-input v-model="loginForm.username" placeholder="管理员账号"/></el-form-item><el-form-item><el-input v-model="loginForm.password" type="password" show-password placeholder="管理员密码"/></el-form-item><el-button type="primary" class="full" @click="login">登录后台</el-button></el-form></el-card></div>
</template>