// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: payment.proto

package paymentservice

import (
	"context"

	"short-drama-recommend/rpc/payment-rpc/pb/short-drama-recommend/rpc/payment-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CapturePaymentRequest  = pb.CapturePaymentRequest
	CapturePaymentResponse = pb.CapturePaymentResponse
	CreateOrderRequest     = pb.CreateOrderRequest
	CreateOrderResponse    = pb.CreateOrderResponse
	GetOrderRequest        = pb.GetOrderRequest
	GetOrderResponse       = pb.GetOrderResponse
	ListOrdersRequest      = pb.ListOrdersRequest
	ListOrdersResponse     = pb.ListOrdersResponse
	WebhookRequest         = pb.WebhookRequest
	WebhookResponse        = pb.WebhookResponse

	PaymentService interface {
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		CapturePayment(ctx context.Context, in *CapturePaymentRequest, opts ...grpc.CallOption) (*CapturePaymentResponse, error)
		GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
		ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
		HandleWebhook(ctx context.Context, in *WebhookRequest, opts ...grpc.CallOption) (*WebhookResponse, error)
	}

	defaultPaymentService struct {
		cli zrpc.Client
	}
)

func NewPaymentService(cli zrpc.Client) PaymentService {
	return &defaultPaymentService{
		cli: cli,
	}
}

func (m *defaultPaymentService) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := pb.NewPaymentServiceClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultPaymentService) CapturePayment(ctx context.Context, in *CapturePaymentRequest, opts ...grpc.CallOption) (*CapturePaymentResponse, error) {
	client := pb.NewPaymentServiceClient(m.cli.Conn())
	return client.CapturePayment(ctx, in, opts...)
}

func (m *defaultPaymentService) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	client := pb.NewPaymentServiceClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultPaymentService) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	client := pb.NewPaymentServiceClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultPaymentService) HandleWebhook(ctx context.Context, in *WebhookRequest, opts ...grpc.CallOption) (*WebhookResponse, error) {
	client := pb.NewPaymentServiceClient(m.cli.Conn())
	return client.HandleWebhook(ctx, in, opts...)
}
