// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: recommend.proto

package recommendservice

import (
	"context"

	"short-drama-recommend/rpc/recommend-rpc/pb/short-drama-recommend/rpc/recommend-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	FeedItem     = pb.FeedItem
	FeedRequest  = pb.FeedRequest
	FeedResponse = pb.FeedResponse

	RecommendService interface {
		GetFeed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
	}

	defaultRecommendService struct {
		cli zrpc.Client
	}
)

func NewRecommendService(cli zrpc.Client) RecommendService {
	return &defaultRecommendService{
		cli: cli,
	}
}

func (m *defaultRecommendService) GetFeed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	client := pb.NewRecommendServiceClient(m.cli.Conn())
	return client.GetFeed(ctx, in, opts...)
}
