// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: drama.proto

package dramaservice

import (
	"context"

	"short-drama-recommend/rpc/drama-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Drama                = pb.Drama
	DramaEpisode         = pb.DramaEpisode
	GetDramaRequest      = pb.GetDramaRequest
	GetDramaResponse     = pb.GetDramaResponse
	ListDramaRequest     = pb.ListDramaRequest
	ListDramaResponse    = pb.ListDramaResponse
	ListEpisodesRequest  = pb.ListEpisodesRequest
	ListEpisodesResponse = pb.ListEpisodesResponse

	DramaService interface {
		GetDrama(ctx context.Context, in *GetDramaRequest, opts ...grpc.CallOption) (*GetDramaResponse, error)
		ListDrama(ctx context.Context, in *ListDramaRequest, opts ...grpc.CallOption) (*ListDramaResponse, error)
		ListEpisodes(ctx context.Context, in *ListEpisodesRequest, opts ...grpc.CallOption) (*ListEpisodesResponse, error)
	}

	defaultDramaService struct {
		cli zrpc.Client
	}
)

func NewDramaService(cli zrpc.Client) DramaService {
	return &defaultDramaService{
		cli: cli,
	}
}

func (m *defaultDramaService) GetDrama(ctx context.Context, in *GetDramaRequest, opts ...grpc.CallOption) (*GetDramaResponse, error) {
	client := pb.NewDramaServiceClient(m.cli.Conn())
	return client.GetDrama(ctx, in, opts...)
}

func (m *defaultDramaService) ListDrama(ctx context.Context, in *ListDramaRequest, opts ...grpc.CallOption) (*ListDramaResponse, error) {
	client := pb.NewDramaServiceClient(m.cli.Conn())
	return client.ListDrama(ctx, in, opts...)
}

func (m *defaultDramaService) ListEpisodes(ctx context.Context, in *ListEpisodesRequest, opts ...grpc.CallOption) (*ListEpisodesResponse, error) {
	client := pb.NewDramaServiceClient(m.cli.Conn())
	return client.ListEpisodes(ctx, in, opts...)
}
