package logic
import("context";"errors";"short-drama-recommend/internal/model";"short-drama-recommend/rpc/drama-rpc/internal/svc";"short-drama-recommend/rpc/drama-rpc/pb")
type DramaAdminServer struct{pb.UnimplementedDramaAdminServiceServer;svcCtx *svc.ServiceContext}
func NewDramaAdminServer(s *svc.ServiceContext)*DramaAdminServer{return &DramaAdminServer{svcCtx:s}}
func(s *DramaAdminServer)CreateDrama(ctx context.Context,r *pb.CreateDramaRequest)(*pb.CreateDramaResponse,error){if r.GetTitle()==""{return nil,errors.New("title is required")};d:=&model.Drama{Title:r.GetTitle(),Description:r.GetDescription(),Cover:r.GetCover(),Country:r.GetCountry(),Language:r.GetLanguage(),TotalEpisodes:uint32(nonneg(r.GetTotalEpisodes())),IsPaid:r.GetIsPaid(),PriceCents:uint64(nonneg64(r.GetPriceCents())),Currency:r.GetCurrency()};if d.Currency==""{d.Currency="USD"};if e:=s.svcCtx.DramaAdminRepo.Create(ctx,d);e!=nil{return nil,e};return &pb.CreateDramaResponse{Drama:toPBDrama(d)},nil}
func(s *DramaAdminServer)UpdateDrama(ctx context.Context,r *pb.UpdateDramaRequest)(*pb.UpdateDramaResponse,error){if r.GetId()<=0{return nil,errors.New("drama id is required")};d:=&model.Drama{ID:uint64(r.GetId()),Title:r.GetTitle(),Description:r.GetDescription(),Cover:r.GetCover(),Country:r.GetCountry(),Language:r.GetLanguage(),TotalEpisodes:uint32(nonneg(r.GetTotalEpisodes())),IsPaid:r.GetIsPaid(),PriceCents:uint64(nonneg64(r.GetPriceCents())),Currency:r.GetCurrency()};if d.Currency==""{d.Currency="USD"};if e:=s.svcCtx.DramaAdminRepo.Update(ctx,d);e!=nil{return nil,e};if old,e:=s.svcCtx.DramaRepo.GetByID(ctx,d.ID);e==nil{d.Status=old.Status};return &pb.UpdateDramaResponse{Drama:toPBDrama(d)},nil}
func(s *DramaAdminServer)SetDramaStatus(ctx context.Context,r *pb.SetDramaStatusRequest)(*pb.SetDramaStatusResponse,error){if r.GetId()<=0||r.GetStatus()<0||r.GetStatus()>2{return nil,errors.New("invalid drama status")};if e:=s.svcCtx.DramaAdminRepo.SetStatus(ctx,uint64(r.GetId()),int8(r.GetStatus()));e!=nil{return nil,e};return &pb.SetDramaStatusResponse{Success:true},nil}
func(s *DramaAdminServer)AdminListDrama(ctx context.Context,r *pb.AdminListDramaRequest)(*pb.AdminListDramaResponse,error){p:=int(r.GetPage());if p<1{p=1};n:=int(r.GetPageSize());if n<=0{n=20};if n>100{n=100};var st *int8;if r.GetStatus()>=0&&r.GetStatus()<=2{v:=int8(r.GetStatus());st=&v};ds,total,e:=s.svcCtx.DramaAdminRepo.List(ctx,r.GetKeyword(),r.GetCountry(),r.GetLanguage(),st,n,(p-1)*n);if e!=nil{return nil,e};o:=&pb.AdminListDramaResponse{Total:total,Items:make([]*pb.Drama,0,len(ds))};for _,d:=range ds{o.Items=append(o.Items,toPBDrama(d))};return o,nil}
func(s *DramaAdminServer)CreateEpisode(ctx context.Context,r *pb.CreateEpisodeRequest)(*pb.CreateEpisodeResponse,error){if r.GetDramaId()<=0||r.GetEpisodeNo()<=0{return nil,errors.New("drama_id and episode_no are required")};e:=&model.Episode{DramaID:uint64(r.GetDramaId()),EpisodeNo:uint32(r.GetEpisodeNo()),Title:r.GetTitle(),DurationSeconds:uint32(nonneg(r.GetDurationSeconds())),VideoURL:r.GetVideoUrl(),PosterURL:r.GetPosterUrl(),IsPaid:r.GetIsPaid()};if x:=s.svcCtx.EpisodeRepo.Create(ctx,e);x!=nil{return nil,x};return &pb.CreateEpisodeResponse{Episode:toPBEpisode(e)},nil}
func(s *DramaAdminServer)ListEpisode(ctx context.Context,r *pb.ListEpisodeRequest)(*pb.ListEpisodeResponse,error){if r.GetDramaId()<=0{return nil,errors.New("drama id is required")};var st *int8;if r.GetStatus()>=0&&r.GetStatus()<=2{v:=int8(r.GetStatus());st=&v};es,e:=s.svcCtx.EpisodeRepo.ListByDrama(ctx,uint64(r.GetDramaId()),st);if e!=nil{return nil,e};o:=&pb.ListEpisodeResponse{Items:make([]*pb.Episode,0,len(es))};for _,x:=range es{o.Items=append(o.Items,toPBEpisode(x))};return o,nil}
func(s *DramaAdminServer)SetEpisodeStatus(ctx context.Context,r *pb.SetEpisodeStatusRequest)(*pb.SetEpisodeStatusResponse,error){if r.GetId()<=0||r.GetStatus()<0||r.GetStatus()>2{return nil,errors.New("invalid episode status")};if e:=s.svcCtx.EpisodeRepo.SetStatus(ctx,uint64(r.GetId()),int8(r.GetStatus()));e!=nil{return nil,e};return &pb.SetEpisodeStatusResponse{Success:true},nil}
func nonneg(v int32)int32{if v<0{return 0};return v}
func nonneg64(v int64)int64{if v<0{return 0};return v}
