name: "mmoe"
platform: "onnxruntime_onnx"
max_batch_size: 64
input [
  { name: "user_id" data_type: TYPE_INT64 dims: [ 1 ] },
  { name: "drama_id" data_type: TYPE_INT64 dims: [ 1 ] },
  { name: "region_id" data_type: TYPE_INT64 dims: [ 1 ] },
  { name: "language_id" data_type: TYPE_INT64 dims: [ 1 ] },
  { name: "genre_id" data_type: TYPE_INT64 dims: [ 1 ] },
  { name: "dense_features" data_type: TYPE_FP32 dims: [ 8 ] }
]
output [
  { name: "p_ctr" data_type: TYPE_FP32 dims: [ 1 ] },
  { name: "watch_logits" data_type: TYPE_FP32 dims: [ 7 ] },
  { name: "p_completion" data_type: TYPE_FP32 dims: [ 1 ] },
  { name: "p_pay" data_type: TYPE_FP32 dims: [ 1 ] }
]
instance_group [{ kind: KIND_CPU count: 2 }]
