// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type Drama struct {
	Id             int64    `json:"id"`
	Title          string   `json:"title"`
	Subtitle       string   `json:"subtitle"`
	Description    string   `json:"description"`
	Cover          string   `json:"cover"`
	Country        string   `json:"country"`
	Language       string   `json:"language"`
	Genres         []string `json:"genres"`
	Tags           []string `json:"tags"`
	TotalEpisodes  int      `json:"total_episodes"`
	IsPaid         bool     `json:"is_paid"`
	PriceCents     int64    `json:"price_cents"`
	Currency       string   `json:"currency"`
	Popularity     float64  `json:"popularity"`
	CompletionRate float64  `json:"completion_rate"`
	PayRate        float64  `json:"pay_rate"`
	PublishedAt    string   `json:"published_at"`
}

type FeedItem struct {
	DramaId int64    `json:"drama_id"`
	Title   string   `json:"title"`
	Cover   string   `json:"cover"`
	Score   float32  `json:"score"`
	Reasons []string `json:"reasons"`
}

type FeedReq struct {
	UserId   int64  `form:"user_id,optional"`
	Country  string `form:"country,optional"`
	Language string `form:"language,optional"`
	PageSize int    `form:"page_size,optional"`
	Cursor   string `form:"cursor,optional"`
}

type FeedResp struct {
	Items      []FeedItem `json:"items"`
	NextCursor string     `json:"next_cursor"`
}

type GetDramaReq struct {
	Id int64 `path:"id"`
}

type GetDramaResp struct {
	Drama Drama `json:"drama"`
}

type ListDramaReq struct {
	Country  string `form:"country,optional"`
	Language string `form:"language,optional"`
	Page     int    `form:"page,optional"`
	PageSize int    `form:"page_size,optional"`
}

type ListDramaResp struct {
	Items []Drama `json:"items"`
}

type RecordBehaviorReq struct {
	UserId          int64  `json:"user_id"`
	DramaId         int64  `json:"drama_id"`
	EpisodeId       int64  `json:"episode_id"`
	EventType       string `json:"event_type"`
	WatchSeconds    int    `json:"watch_seconds"`
	DurationSeconds int    `json:"duration_seconds"`
	Country         string `json:"country"`
	Language        string `json:"language"`
	Device          string `json:"device"`
	Source          string `json:"source"`
	RequestId       string `json:"request_id"`
}

type RecordBehaviorResp struct {
	Success bool `json:"success"`
}
