// Code generated by ent, DO NOT EDIT.

package episode

import (
	"short-drama-recommend/rpc/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldID, id))
}

// DramaID applies equality check predicate on the "drama_id" field. It's identical to DramaIDEQ.
func DramaID(v uint64) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldDramaID, v))
}

// EpisodeNo applies equality check predicate on the "episode_no" field. It's identical to EpisodeNoEQ.
func EpisodeNo(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldEpisodeNo, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldDescription, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldDurationSeconds, v))
}

// VideoURL applies equality check predicate on the "video_url" field. It's identical to VideoURLEQ.
func VideoURL(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldVideoURL, v))
}

// PosterURL applies equality check predicate on the "poster_url" field. It's identical to PosterURLEQ.
func PosterURL(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldPosterURL, v))
}

// IsPaid applies equality check predicate on the "is_paid" field. It's identical to IsPaidEQ.
func IsPaid(v bool) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldIsPaid, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldUpdatedAt, v))
}

// DramaIDEQ applies the EQ predicate on the "drama_id" field.
func DramaIDEQ(v uint64) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldDramaID, v))
}

// DramaIDNEQ applies the NEQ predicate on the "drama_id" field.
func DramaIDNEQ(v uint64) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldDramaID, v))
}

// DramaIDIn applies the In predicate on the "drama_id" field.
func DramaIDIn(vs ...uint64) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldDramaID, vs...))
}

// DramaIDNotIn applies the NotIn predicate on the "drama_id" field.
func DramaIDNotIn(vs ...uint64) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldDramaID, vs...))
}

// EpisodeNoEQ applies the EQ predicate on the "episode_no" field.
func EpisodeNoEQ(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldEpisodeNo, v))
}

// EpisodeNoNEQ applies the NEQ predicate on the "episode_no" field.
func EpisodeNoNEQ(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldEpisodeNo, v))
}

// EpisodeNoIn applies the In predicate on the "episode_no" field.
func EpisodeNoIn(vs ...uint32) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldEpisodeNo, vs...))
}

// EpisodeNoNotIn applies the NotIn predicate on the "episode_no" field.
func EpisodeNoNotIn(vs ...uint32) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldEpisodeNo, vs...))
}

// EpisodeNoGT applies the GT predicate on the "episode_no" field.
func EpisodeNoGT(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldEpisodeNo, v))
}

// EpisodeNoGTE applies the GTE predicate on the "episode_no" field.
func EpisodeNoGTE(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldEpisodeNo, v))
}

// EpisodeNoLT applies the LT predicate on the "episode_no" field.
func EpisodeNoLT(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldEpisodeNo, v))
}

// EpisodeNoLTE applies the LTE predicate on the "episode_no" field.
func EpisodeNoLTE(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldEpisodeNo, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContainsFold(FieldDescription, v))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...uint32) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...uint32) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v uint32) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldDurationSeconds, v))
}

// VideoURLEQ applies the EQ predicate on the "video_url" field.
func VideoURLEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldVideoURL, v))
}

// VideoURLNEQ applies the NEQ predicate on the "video_url" field.
func VideoURLNEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldVideoURL, v))
}

// VideoURLIn applies the In predicate on the "video_url" field.
func VideoURLIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldVideoURL, vs...))
}

// VideoURLNotIn applies the NotIn predicate on the "video_url" field.
func VideoURLNotIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldVideoURL, vs...))
}

// VideoURLGT applies the GT predicate on the "video_url" field.
func VideoURLGT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldVideoURL, v))
}

// VideoURLGTE applies the GTE predicate on the "video_url" field.
func VideoURLGTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldVideoURL, v))
}

// VideoURLLT applies the LT predicate on the "video_url" field.
func VideoURLLT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldVideoURL, v))
}

// VideoURLLTE applies the LTE predicate on the "video_url" field.
func VideoURLLTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldVideoURL, v))
}

// VideoURLContains applies the Contains predicate on the "video_url" field.
func VideoURLContains(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContains(FieldVideoURL, v))
}

// VideoURLHasPrefix applies the HasPrefix predicate on the "video_url" field.
func VideoURLHasPrefix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasPrefix(FieldVideoURL, v))
}

// VideoURLHasSuffix applies the HasSuffix predicate on the "video_url" field.
func VideoURLHasSuffix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasSuffix(FieldVideoURL, v))
}

// VideoURLEqualFold applies the EqualFold predicate on the "video_url" field.
func VideoURLEqualFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEqualFold(FieldVideoURL, v))
}

// VideoURLContainsFold applies the ContainsFold predicate on the "video_url" field.
func VideoURLContainsFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContainsFold(FieldVideoURL, v))
}

// PosterURLEQ applies the EQ predicate on the "poster_url" field.
func PosterURLEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldPosterURL, v))
}

// PosterURLNEQ applies the NEQ predicate on the "poster_url" field.
func PosterURLNEQ(v string) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldPosterURL, v))
}

// PosterURLIn applies the In predicate on the "poster_url" field.
func PosterURLIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldPosterURL, vs...))
}

// PosterURLNotIn applies the NotIn predicate on the "poster_url" field.
func PosterURLNotIn(vs ...string) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldPosterURL, vs...))
}

// PosterURLGT applies the GT predicate on the "poster_url" field.
func PosterURLGT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldPosterURL, v))
}

// PosterURLGTE applies the GTE predicate on the "poster_url" field.
func PosterURLGTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldPosterURL, v))
}

// PosterURLLT applies the LT predicate on the "poster_url" field.
func PosterURLLT(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldPosterURL, v))
}

// PosterURLLTE applies the LTE predicate on the "poster_url" field.
func PosterURLLTE(v string) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldPosterURL, v))
}

// PosterURLContains applies the Contains predicate on the "poster_url" field.
func PosterURLContains(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContains(FieldPosterURL, v))
}

// PosterURLHasPrefix applies the HasPrefix predicate on the "poster_url" field.
func PosterURLHasPrefix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasPrefix(FieldPosterURL, v))
}

// PosterURLHasSuffix applies the HasSuffix predicate on the "poster_url" field.
func PosterURLHasSuffix(v string) predicate.Episode {
	return predicate.Episode(sql.FieldHasSuffix(FieldPosterURL, v))
}

// PosterURLEqualFold applies the EqualFold predicate on the "poster_url" field.
func PosterURLEqualFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldEqualFold(FieldPosterURL, v))
}

// PosterURLContainsFold applies the ContainsFold predicate on the "poster_url" field.
func PosterURLContainsFold(v string) predicate.Episode {
	return predicate.Episode(sql.FieldContainsFold(FieldPosterURL, v))
}

// IsPaidEQ applies the EQ predicate on the "is_paid" field.
func IsPaidEQ(v bool) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldIsPaid, v))
}

// IsPaidNEQ applies the NEQ predicate on the "is_paid" field.
func IsPaidNEQ(v bool) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldIsPaid, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Episode {
	return predicate.Episode(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasDrama applies the HasEdge predicate on the "drama" edge.
func HasDrama() predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DramaTable, DramaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDramaWith applies the HasEdge predicate on the "drama" edge with a given conditions (other predicates).
func HasDramaWith(preds ...predicate.Drama) predicate.Episode {
	return predicate.Episode(func(s *sql.Selector) {
		step := newDramaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Episode) predicate.Episode {
	return predicate.Episode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Episode) predicate.Episode {
	return predicate.Episode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Episode) predicate.Episode {
	return predicate.Episode(sql.NotPredicates(p))
}
