<script setup lang="ts">
import{onMounted,ref}from'vue';import{ElMessage}from'element-plus';import{request}from'../../api/client'
const dramas=ref<any[]>([]),selected=ref<number>(),episodes=ref<any[]>([]),dialog=ref(false),saving=ref(false)
const form=ref({episode_no:1,title:'',duration_seconds:60,video_url:'',poster_url:'',is_paid:true})
async function loadDramas(){try{dramas.value=(await request('/api/v1/admin/dramas?page=1&page_size=100')).items||[]}catch{dramas.value=[]}}
async function loadEpisodes(id:number){selected.value=id;try{episodes.value=(await request('/api/v1/admin/dramas/'+id+'/episodes?status=1')).items||[]}catch(e:any){ElMessage.error(e.message)}}
function openCreate(){if(!selected.value){ElMessage.warning('请先选择短剧');return}form.value={episode_no:(episodes.value.length?Math.max(...episodes.value.map(x=>x.episode_no))+1:1),title:'',duration_seconds:60,video_url:'',poster_url:'',is_paid:true};dialog.value=true}
async function create(){if(!selected.value||!form.value.title||!form.value.video_url){ElMessage.warning('标题和视频地址不能为空');return}saving.value=true;try{await request('/api/v1/admin/dramas/'+selected.value+'/episodes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form.value)});ElMessage.success('剧集创建成功');dialog.value=false;await loadEpisodes(selected.value)}catch(e:any){ElMessage.error(e.message)}finally{saving.value=false}}
async function toggle(e:any){try{await request('/api/v1/admin/episodes/'+e.id+'/status',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:e.status===1?2:1})});await loadEpisodes(selected.value!)}catch(e:any){ElMessage.error(e.message)}}
onMounted(loadDramas)
</script>
<template><section><div class="title"><p>CONTENT / EPISODES</p><h1>剧集管理</h1><span>创建、发布和维护每一集视频</span></div><el-card><div class="episode-toolbar"><el-select v-model="selected" placeholder="选择短剧" style="width:420px" @change="loadEpisodes"><el-option v-for="x in dramas" :key="x.id" :label="x.title" :value="x.id"/></el-select><el-button type="primary" @click="openCreate">+ 新增剧集</el-button></div></el-card><el-card v-if="selected" class="panel"><el-table :data="episodes" stripe><el-table-column prop="episode_no" label="集数" width="80"/><el-table-column prop="title" label="标题" min-width="180"/><el-table-column prop="duration_seconds" label="时长" width="90"/><el-table-column prop="is_paid" label="付费" width="80"><template #default="{row}">{{row.is_paid?'是':'否'}}</template></el-table-column><el-table-column prop="video_url" label="视频地址" min-width="300"/><el-table-column label="状态/操作" width="150"><template #default="{row}"><el-tag>{{row.status===1?'已发布':'下架'}}</el-tag><el-button link type="primary" @click="toggle(row)">{{row.status===1?'下架':'发布'}}</el-button></template></el-table-column></el-table><el-empty v-if="!episodes.length" description="暂无剧集"/></el-card><el-dialog v-model="dialog" title="新增剧集" width="620px"><el-form label-width="100px"><el-form-item label="集数"><el-input-number v-model="form.episode_no" :min="1"/></el-form-item><el-form-item label="标题"><el-input v-model="form.title" placeholder="Episode 1"/></el-form-item><el-form-item label="时长"><el-input-number v-model="form.duration_seconds" :min="1"/></el-form-item><el-form-item label="视频 URL"><el-input v-model="form.video_url" placeholder="https://.../episode-1.m3u8"/></el-form-item><el-form-item label="海报 URL"><el-input v-model="form.poster_url"/></el-form-item><el-form-item label="付费"><el-switch v-model="form.is_paid"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">创建</el-button></template></el-dialog></section></template>