// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: drama_admin.proto

package dramaadminservice

import (
	"context"

	"short-drama-recommend/rpc/drama-rpc/pb/short-drama-recommend/rpc/drama-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminListDramaRequest    = pb.AdminListDramaRequest
	AdminListDramaResponse   = pb.AdminListDramaResponse
	CreateDramaRequest       = pb.CreateDramaRequest
	CreateDramaResponse      = pb.CreateDramaResponse
	CreateEpisodeRequest     = pb.CreateEpisodeRequest
	CreateEpisodeResponse    = pb.CreateEpisodeResponse
	Episode                  = pb.Episode
	ListEpisodeRequest       = pb.ListEpisodeRequest
	ListEpisodeResponse      = pb.ListEpisodeResponse
	SetDramaStatusRequest    = pb.SetDramaStatusRequest
	SetDramaStatusResponse   = pb.SetDramaStatusResponse
	SetEpisodeStatusRequest  = pb.SetEpisodeStatusRequest
	SetEpisodeStatusResponse = pb.SetEpisodeStatusResponse
	UpdateDramaRequest       = pb.UpdateDramaRequest
	UpdateDramaResponse      = pb.UpdateDramaResponse

	DramaAdminService interface {
		CreateDrama(ctx context.Context, in *CreateDramaRequest, opts ...grpc.CallOption) (*CreateDramaResponse, error)
		UpdateDrama(ctx context.Context, in *UpdateDramaRequest, opts ...grpc.CallOption) (*UpdateDramaResponse, error)
		SetDramaStatus(ctx context.Context, in *SetDramaStatusRequest, opts ...grpc.CallOption) (*SetDramaStatusResponse, error)
		AdminListDrama(ctx context.Context, in *AdminListDramaRequest, opts ...grpc.CallOption) (*AdminListDramaResponse, error)
		CreateEpisode(ctx context.Context, in *CreateEpisodeRequest, opts ...grpc.CallOption) (*CreateEpisodeResponse, error)
		ListEpisode(ctx context.Context, in *ListEpisodeRequest, opts ...grpc.CallOption) (*ListEpisodeResponse, error)
		SetEpisodeStatus(ctx context.Context, in *SetEpisodeStatusRequest, opts ...grpc.CallOption) (*SetEpisodeStatusResponse, error)
	}

	defaultDramaAdminService struct {
		cli zrpc.Client
	}
)

func NewDramaAdminService(cli zrpc.Client) DramaAdminService {
	return &defaultDramaAdminService{
		cli: cli,
	}
}

func (m *defaultDramaAdminService) CreateDrama(ctx context.Context, in *CreateDramaRequest, opts ...grpc.CallOption) (*CreateDramaResponse, error) {
	client := pb.NewDramaAdminServiceClient(m.cli.Conn())
	return client.CreateDrama(ctx, in, opts...)
}

func (m *defaultDramaAdminService) UpdateDrama(ctx context.Context, in *UpdateDramaRequest, opts ...grpc.CallOption) (*UpdateDramaResponse, error) {
	client := pb.NewDramaAdminServiceClient(m.cli.Conn())
	return client.UpdateDrama(ctx, in, opts...)
}

func (m *defaultDramaAdminService) SetDramaStatus(ctx context.Context, in *SetDramaStatusRequest, opts ...grpc.CallOption) (*SetDramaStatusResponse, error) {
	client := pb.NewDramaAdminServiceClient(m.cli.Conn())
	return client.SetDramaStatus(ctx, in, opts...)
}

func (m *defaultDramaAdminService) AdminListDrama(ctx context.Context, in *AdminListDramaRequest, opts ...grpc.CallOption) (*AdminListDramaResponse, error) {
	client := pb.NewDramaAdminServiceClient(m.cli.Conn())
	return client.AdminListDrama(ctx, in, opts...)
}

func (m *defaultDramaAdminService) CreateEpisode(ctx context.Context, in *CreateEpisodeRequest, opts ...grpc.CallOption) (*CreateEpisodeResponse, error) {
	client := pb.NewDramaAdminServiceClient(m.cli.Conn())
	return client.CreateEpisode(ctx, in, opts...)
}

func (m *defaultDramaAdminService) ListEpisode(ctx context.Context, in *ListEpisodeRequest, opts ...grpc.CallOption) (*ListEpisodeResponse, error) {
	client := pb.NewDramaAdminServiceClient(m.cli.Conn())
	return client.ListEpisode(ctx, in, opts...)
}

func (m *defaultDramaAdminService) SetEpisodeStatus(ctx context.Context, in *SetEpisodeStatusRequest, opts ...grpc.CallOption) (*SetEpisodeStatusResponse, error) {
	client := pb.NewDramaAdminServiceClient(m.cli.Conn())
	return client.SetEpisodeStatus(ctx, in, opts...)
}
