package handler
import("database/sql";"encoding/json";"net/http";"strings";"time";"github.com/zeromicro/go-zero/rest";"github.com/zeromicro/go-zero/rest/httpx";"golang.org/x/crypto/bcrypt";"short-drama-recommend/api/auth-api/internal/config";"short-drama-recommend/pkg/auth";_ "github.com/go-sql-driver/mysql")
type service struct{db *sql.DB}
type credentials struct{Email string `json:"email"`;Password string `json:"password"`;DisplayName string `json:"display_name"`;Country string `json:"country"`;Language string `json:"language"`}
type response struct{Token string `json:"token"`;User any `json:"user"`}
func Register(s *rest.Server,c config.Config){db,err:=sql.Open("mysql",c.Mysql.DataSource);if err!=nil{panic(err)};h:=&service{db:db};s.AddRoutes([]rest.Route{{Method:http.MethodPost,Path:"/api/v1/auth/register",Handler:h.register},{Method:http.MethodPost,Path:"/api/v1/auth/login",Handler:h.login},{Method:http.MethodGet,Path:"/api/v1/auth/me",Handler:h.me}})}
func (h *service) register(w http.ResponseWriter,r *http.Request){var in credentials;if err:=json.NewDecoder(r.Body).Decode(&in);err!=nil||!strings.Contains(in.Email,"@")||len(in.Password)<8{httpx.Error(w,fmtErr("email or password invalid"));return};hash,e:=bcrypt.GenerateFromPassword([]byte(in.Password),bcrypt.DefaultCost);if e!=nil{httpx.Error(w,e);return};if in.Language==""{in.Language="en"};res,e:=h.db.Exec("INSERT INTO users(email,password_hash,display_name,country,language,locale) VALUES(?,?,?,?,?,?)",strings.ToLower(strings.TrimSpace(in.Email)),string(hash),in.DisplayName,in.Country,in.Language,in.Language+"-"+in.Country);if e!=nil{httpx.Error(w,e);return};id,_:=res.LastInsertId();token,_:=auth.Issue(id,in.Email,30*24*time.Hour);httpx.OkJson(w,response{Token:token,User:map[string]any{"id":id,"email":in.Email,"display_name":in.DisplayName,"country":in.Country,"language":in.Language}})}
func (h *service) login(w http.ResponseWriter,r *http.Request){var in credentials;if err:=json.NewDecoder(r.Body).Decode(&in);err!=nil{httpx.Error(w,err);return};var id int64;var hash,name,country,language string;e:=h.db.QueryRow("SELECT id,password_hash,display_name,country,language FROM users WHERE email=? AND status=1",strings.ToLower(strings.TrimSpace(in.Email))).Scan(&id,&hash,&name,&country,&language);if e!=nil||bcrypt.CompareHashAndPassword([]byte(hash),[]byte(in.Password))!=nil{httpx.Error(w,fmtErr("email or password invalid"));return};token,_:=auth.Issue(id,in.Email,30*24*time.Hour);httpx.OkJson(w,response{Token:token,User:map[string]any{"id":id,"email":in.Email,"display_name":name,"country":country,"language":language}})}
func (h *service) me(w http.ResponseWriter,r *http.Request){id,e:=auth.Bearer(r.Header.Get("Authorization"));if e!=nil{httpx.Error(w,e);return};var email,name,country,language string;if e=h.db.QueryRow("SELECT email,display_name,country,language FROM users WHERE id=? AND status=1",id).Scan(&email,&name,&country,&language);e!=nil{httpx.Error(w,e);return};httpx.OkJson(w,map[string]any{"id":id,"email":email,"display_name":name,"country":country,"language":language})}
type simpleErr string
func(x simpleErr)Error()string{return string(x)}
func fmtErr(s string)error{return simpleErr(s)}
